-include ../../../petscdir.mk

DIRS     = impls tutorials
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMLabel

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
