# $Id: makefile,v 1.5 2001/08/22 18:01:44 balay Exp $

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = bicg.c
SOURCEF  =
OBJSC    = bicg.o
OBJSF    =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/bicg/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
