
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = armijo.c
SOURCEF  = 
SOURCEH  = armijo.h
OBJSC    = armijo.o
OBJSF    = 
LIBBASE  = libtaolinesearch
MANSEC   = linesearch
LOCDIR   = src/linesearch/impls/armijo/

include ${TAO_DIR}/conf/tao_base

