-include ../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_MOAB'

LOCDIR          = src/dm/impls/moab/tests/
EXAMPLESC       = ex1.cxx ex2.cxx ex3.cxx
EXAMPLESF       =
MANSEC          = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
