# $Id: makefile,v 1.1 2003/06/30 02:59:13 kaushik Exp $ 

ALL: lib 

CFLAGS   = ${NETCDF_INCLUDE}
FFLAGS   =
SOURCEC  = vnetcdf.c
SOURCEF  =
SOURCEH  =
OBJSC    = vnetcdf.o
OBJSF    =
MANSEC   = Viewer
LIBBASE  = libpetsc
DIRS     = 
LOCDIR   = src/sys/src/viewer/impls/netcdf/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
