# -*- makefile -*-

.PHONY: all test petsc-232 petsc-233 petsc-240 petsc-dev

MPIEXEC  =
VALGRIND =
PYTHON   = python

PETSC_232=/usr/local/petsc/2.3.2
PETSC_233=/usr/local/petsc/2.3.3
PETSC_240=/usr/local/petsc/2.4.0
PETSC_DEV=${HOME}/Devel/PETSc/petsc-dev

PETSC_ARCH=linux-gnu

all: petsc-232 petsc-233 petsc-240 petsc-dev

MAKE_ARGS= -f misc/makefile.dev MPIEXEC='${MPIEXEC}' VALGRIND='${VALGRIND}' PYTHON='${PYTHON}'
petsc-232: 
	${MAKE} ${MAKE_ARGS} PETSC_DIR=${PETSC_232} test
petsc-233:
	${MAKE} ${MAKE_ARGS} PETSC_DIR=${PETSC_233} test
petsc-240:
	${MAKE} ${MAKE_ARGS} PETSC_DIR=${PETSC_240} test
petsc-dev:
	${MAKE} ${MAKE_ARGS} PETSC_DIR=${PETSC_DEV} test


TEST_DIR=/tmp/petsc4py-build-test
PETSC_OPTIONS='-malloc_dump -log_summary'
test:
	${RM} -r build ${TEST_DIR}/lib/python/petsc4py*
	${PYTHON} setup.py clean --all
	${PYTHON} setup.py install --home=${TEST_DIR}
	PYTHONPATH=${TEST_DIR}/lib/python PETSC_OPTIONS=${PETSC_OPTIONS} \
	${MPIEXEC} ${VALGRIND} ${PYTHON} test/runtests.py
	${RM} tests/*.py[co]
	${RM} -r build ${TEST_DIR}/lib/python/petsc4py*
