# -*- makefile -*-

.PHONY: all test petsc-30 petsc-31 petsc-dev

MPIEXEC  =
VALGRIND =
PYTHON   = python

PETSC_30=/usr/local/petsc/3.0.0
PETSC_31=/usr/local/petsc/3.1
PETSC_DEV=${HOME}/Devel/PETSc/petsc-dev

PETSC_ARCH=linux-gnu

all: petsc-30 petsc-31 petsc-dev

MAKE_ARGS= -f misc/makefile.dev MPIEXEC='${MPIEXEC}' VALGRIND='${VALGRIND}' PYTHON='${PYTHON}'
petsc-30:
	${MAKE} ${MAKE_ARGS} PETSC_DIR=${PETSC_30} PETSC_ARCH=${PETSC_ARCH} test
petsc-31:
	${MAKE} ${MAKE_ARGS} PETSC_DIR=${PETSC_31} PETSC_ARCH=${PETSC_ARCH} test
petsc-dev:
	${MAKE} ${MAKE_ARGS} PETSC_DIR=${PETSC_DEV} PETSC_ARCH=${PETSC_ARCH} test


TEST_DIR=/tmp/petsc4py-build-test
PETSC_OPTIONS='-malloc_dump -log_summary'
test:
	${RM} -r build ${TEST_DIR}/lib/python/petsc4py*
	${PYTHON} setup.py clean --all
	${PYTHON} setup.py install --home=${TEST_DIR}
	PYTHONPATH=${TEST_DIR}/lib/python PETSC_OPTIONS=${PETSC_OPTIONS} \
	${MPIEXEC} ${VALGRIND} ${PYTHON} test/runtests.py
	${RM} tests/*.py[co]
	${RM} -r build ${TEST_DIR}/lib/python/petsc4py*
