#requiresfunction 'PETSC_HAVE_DRAND48'

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = rand48.c
SOURCEF  =
SOURCEH  = 
OBJSC    = rand48.o 
OBJSF    =
LIBBASE  = libpetscsys
DIRS     = 
LOCDIR   = src/sys/random/impls/rand48/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

