# $Id: makefile,v 1.4 1998/04/23 23:46:26 balay Exp balay $ 

ALL: lib

SOURCEC  = snesmfj2.c snesnoise.c
SOURCEF  = snesdnest.F
SOURCEH  = 
OBJSC    = snesmfj2.o snesnoise.o
OBJSF    = snesdnest.o
LIBBASE  = libpetscsnes
MANSEC   = n
LOCDIR   = src/snes/interface/noise

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

