# $Id: makefile,v 1.5 1998/04/24 01:03:24 bsmith Exp balay $

ALL: lib


SOURCEH  = 
SOURCEF  = 
OBJSC    = elapack.o
OBJSF    = 
LIBBASE  = libpetscec
MANSEC   = 5
LOCDIR   = src/ec/impls/lapack/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
