# $Id: makefile,v 1.7 1998/06/12 21:40:47 balay Exp balay $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = elapack.c
SOURCEH  = 
SOURCEF  = 
OBJSC    = elapack.o
OBJSF    = 
LIBBASE  = libpetscec
MANSEC   = 5
LOCDIR   = src/ec/impls/lapack/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
