#requirespackage   'PETSC_HAVE_FORTRAN'

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zdmf.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = zdmf.o
OBJSF    = 
LIBBASE  = libpetscdm
MANSEC   = DMDA
LOCDIR   = src/dm/interface/ftn-custom/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


