
ALL: lib

SOURCEH  = ../../../include/private/kspimpl.h ../../../include/petscksp.h
DIRS     = interface impls examples utils
LOCDIR   = src/ksp/ksp/
MANSEC   = KSP

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
