
ALL: lib

SOURCEH  = ../../../include/petsc-private/kspimpl.h ../../../include/petscksp.h
DIRS     = interface impls examples utils
LOCDIR   = src/ksp/ksp/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
