# $Id: makefile,v 1.58 2001/08/22 17:58:52 balay Exp $ 

all: copyexamples

copyexamples: 
	cp -f ../src/sles/examples/tutorials/ex2.c c/sles/ex2.c
	cp -f ../src/sles/examples/tutorials/ex2.c c++/sles/ex2.cpp
	cp -f ../src/sles/examples/tutorials/ex2f.F fortran/sles/ex2f.F