
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gpcglinesearch.c
SOURCEF  = 
SOURCEH  = gpcglinesearch.h
OBJSC    = gpcglinesearch.o
OBJSF    = 
LIBBASE  = libtaolinesearch
MANSEC   = linesearch
LOCDIR   = src/linesearch/impls/gpcglinesearch/

include ${TAO_DIR}/conf/tao_base

