ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC	  = plog.c plogmpe.c
SOURCEF	  =
SOURCEH	  = plog.h ../../../include/petsclog.h
OBJSC	  = ${SOURCEC:.c=.o}
OBJSF	  =
MANSEC	  = Profiling
LIBBASE	  = libpetscsys
DIRS	  = utils
LOCDIR	  = src/sys/plog/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
