# $Id: makefile,v 1.3 2001/08/06 21:19:00 bsmith Exp balay $ 

#requireslanguage  CONLY
#requiresscalar    real 
#requiresprecision double

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  = 
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = PC
LOCDIR   = src/contrib/lahaye
DIRS     = ramg samg

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
