# $Id: makefile,v 1.2 2001/01/15 21:49:36 bsmith Exp bsmith $ 

#requireslanguage  CONLY
#requiresscalar    real 
#requiresprecision double

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  = 
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = PC
LOCDIR   = src/contrib/lahaye
DIRS     = ramg samg

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
