# $Id: makefile,v 1.28 1998/04/23 23:34:52 balay Exp balay $ 

ALL: lib 

CFLAGS   = 
SOURCEC  = tfqmr.c
SOURCEF  =
OBJSC    = tfqmr.o
OBJSF    =
LIBBASE  = libpetscsles
LOCDIR   = src/ksp/impls/tfqmr/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
