-include ../../../../../petscdir.mk

DIRS      = basic mapping memscalable
MANSEC    = Vec
SUBMANSEC = AO

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

