-include ../../../../../petscdir.mk

SOURCEC  = virs.c
SOURCEF  =
SOURCEH  = virsimpl.h
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/vi/rs/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

