-include ../../../../../petsckdir.mk

SOURCEC	  = iscomp.c iscoloring.c isdiff.c isblock.c
SOURCEF	  =
SOURCEH	  =
LIBBASE	  = libpetscvec
DIRS	  =
MANSEC	  = Vec
SUBMANSEC = IS
LOCDIR	  = src/vec/is/is/utils/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
