-include ../../../../../../petscdir.mk
#requiresfunction 'PETSC_HAVE_DRAND48'

LIBBASE  = libpetscsys
MANSEC	 = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

