#requiresfunction 'PETSC_HAVE_DRAND48'

SOURCEC  = rand48.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
DIRS     =
LOCDIR   = src/sys/classes/random/impls/rand48/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

