-include ../../../../../../petscdir.mk
#requiresfunction 'PETSC_HAVE_DRAND48'

SOURCEC  = rand48.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
DIRS     =
MANSEC	 = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

