
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bipartite.c valid.c weights.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
MANSEC   = MatOrderings
LOCDIR   = src/mat/color/utils/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
