
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = vinv.c vscat.c vpscat.c vecio.c comb.c vecstash.c vecmpitoseq.c vecs.c vsection.c projection.c vecglvis.c
SOURCEF  =
SOURCEH  = vpscat.h
DIRS     = matlab tagger
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/utils/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

