# $Id: makefile,v 1.6 1998/06/13 05:22:45 balay Exp balay $ 

ALL:

CFLAGS   = 
FFLAGS	 = 
SOURCEC	 = 
SOURCEF	 = 
SOURCEH	 = 
OBJSC	 = 
OBJSF	 = 
LIBBASE	 = libpetscvec
LOCDIR	 = src/contrib/sda/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
