# $Id: makefile,v 1.9 2000/08/17 04:53:27 bsmith Exp balay $ 

ALL:

LOCDIR	 = src/contrib/sda/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
