
ALL:

LOCDIR	 = src/vec/pf/examples/
DIRS	 = tutorials
MANSEC   = Vec

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
