#PETSC_DIR = ../../..

ALL: lib

CFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = dvecimpl.h
OBJSC    =  
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = seq mpi
LOCDIR   = src/vec/impls/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base

