# $Id: makefile,v 1.32 2001/09/07 20:08:59 bsmith Exp $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = dvecimpl.h
OBJSC    =  
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = seq mpi shared esi hypre
LOCDIR   = src/vec/impls/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

