-include ../../../../petscdir.mk
#requiresdefine    'PETSC_USE_LOG'

SOURCEC	  = classlog.c stagelog.c eventlog.c stack.c
MANSEC	  = Profiling
LIBBASE	  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
