.. warning::

  **THIS SECTION IS IN NEED OF EXPERT COPYEDITING!**
  This documentation is being moved from the old, LaTeX-based manual
  to a web-friendlier format using Sphinx. The content below
  was mostly automatically converted from LaTeX source, and almost certainly
  includes multiple formatting errors, missing images, etc.
  If you are a developer/contributor/expert and would like to claim this section
  to clean it up (and if so inspired, improve and/or streamline it),
  please make an initial MR to remove this banner and replace it with a note
  identifying it as being edited by you. Then, edit using Sphinx tools and when ready,
  submit your changes. Note that developer information on Sphinx lives here:
  :ref:`sphinx_documentation`.
