# $Id: makefile,v 1.3 1998/06/12 21:33:12 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = 
DIRS     = 2d
LOCDIR   = src/usg/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
