# $Id: makefile,v 1.1 1998/04/03 20:33:06 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   = ${CPPFLAGS}  -D__SDIR__='"${LOCDIR}"'
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = 
DIRS     = 2d
LOCDIR   = src/usg/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
