# $Id: makefile,v 1.2 1998/04/24 01:04:04 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   = ${CPPFLAGS}  -D__SDIR__='"${LOCDIR}"' 
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = 
DIRS     = src  examples blas lapack makefile
LOCDIR   = src/adic/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

