
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sliced.c
SOURCEF  = 
SOURCEH  = ../../../../include/petscdmsliced.h
OBJSC    = sliced.o
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMSLICED
LOCDIR   = src/dm/impls/sliced

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
