-include ../../../../petscdir.mk

SOURCEC  = sliced.c
SOURCEF  =
SOURCEH  = ../../../../include/petscdmsliced.h
LIBBASE  = libpetscdm
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
