-include ../../../../petscdir.mk

LOCDIR		 = src/tao/leastsquares/tutorials/
MANSEC		 =
EXAMPLESC        = chwirut1.c chwirut2.c cs1.c tomography.c
EXAMPLESCH       =
EXAMPLESF        = chwirut1f.F90 chwirut2f.F90
EXAMPLESFH       = chwirut2f.h
TUTORIALS        = chwirut1.c chwirut2.c chwirut1f.F90 chwirut2f.F90 cs1.c tomography.c
DOCS		 =
DIRS		 = matlab
CLEANFILES       = chwirut1 chwirut2 chwirut1f chwirut2f cs1 tomography

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


