-include ../../../../petscdir.mk

LOCDIR		 = src/tao/leastsquares/tutorials/
MANSEC		 = Tao
DOCS		 =
DIRS		 = matlab
CLEANFILES       = chwirut1 chwirut2 chwirut1f chwirut2f cs1 tomography

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


