-include ../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_HYPRE'

SOURCEC  = mhyp.c
SOURCEF  =
SOURCEH  = mhyp.h
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMDA
DIRS     =
LOCDIR   = src/dm/impls/da/hypre/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
