# $Id: makefile,v 1.36 1997/09/10 18:53:20 balay Exp balay $ 

ALL: ex1

CFLAGS	        = ${CPPFLAGS} ${CONF} -D__SDIR__='"${LOCDIR}"'
FFLAGS	        = 
SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        =
LIBBASE	        = libpetscsys
LOCDIR          = src/sys/examples/
DIRS            = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
