# $Id: makefile,v 1.40 1998/06/15 16:18:53 balay Exp bsmith $ 

ALL: ex1

CFLAGS	 = 
FFLAGS	 = 
SOURCEC	 = 
SOURCEF	 = 
SOURCEH	 = 
OBJSC	 = 
OBJSF	 = 
LIBBASE	 = libpetsc
LOCDIR	 = src/sys/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
