-include ../../../../../../petscdir.mk
#requirespackage   'PETSC_HAVE_MUMPS'

CFLAGS   = ${MUMPS_INCLUDE}
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
