#requirespackage   'PETSC_USE_MATFRAMEWORK"
ALL: lib

CPPFLAGS = 
CFLAGS   = 
FFLAGS   =
SOURCEC  = mframework.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = mframework.o
OBJSF    =
DIRS     = 
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/framework/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
