#requirespackage 'PETSC_HAVE_ELEMENTAL'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCECXX= elemental.cxx
SOURCEF  =
SOURCEH  =
MANSEC   = Sys
LIBBASE  = libpetscsys
LOCDIR   = src/sys/objects/cxx/
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

