-include ../../../../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fft.c
SOURCEH  = fft.h
LIBBASE  = libpetscmat
DIRS     = fftw
LOCDIR   = src/mat/impls/fft/
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
