
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fft.c 
SOURCEH  = fft.h
OBJSC    = fft.o 
LIBBASE  = libpetscmat
DIRS     = fftw
LOCDIR   = src/mat/impls/fft/
MANSEC   = Mat

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
