
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bjacobi.c
SOURCEF  =
SOURCEH  = bjacobi.h
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/bjacobi/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
