
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = adda.c
SOURCEF  =
OBJSC    = adda.o
OBJSF    =
LIBBASE  = libpetscdm
DIRS     = examples
LOCDIR   = src/dm/adda/
MANSEC   = DM
SUBMANSEC= DMADDA

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
