ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bqpip.c
SOURCEF  =
SOURCEH  = bqpip.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/bound/impls/bqpip/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

