# $Id: makefile,v 1.31 2000/08/17 04:52:26 bsmith Exp balay $

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = cgs.c
SOURCEF  =
OBJSC    = cgs.o
OBJSF    = 
LIBBASE  = libpetscsles
LOCDIR   = src/sles/ksp/impls/cgs/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
