ALL: lib 
ITOOLSDIR = ../../../

CFLAGS   = $(OPT) $(CONF) -I$(ITOOLSDIR) -I$(ITOOLSDIR)/include \
           -I$(ITOOLSDIR)/pinclude -I../../ 
SOURCEC  = cgs.c
WSOURCEC = 
SOURCEF  =
OBJSC    = cgs.o
WOBJS    = 
OBJSF    = 
LIBBASE  = libpetscksp
LINCLUDE = 

include $(ITOOLSDIR)/bmake/$(PARCH)
