
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taolinesearch.c dlregis_taolinesearch.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetsctao
MANSEC   = TaoLineSearch
LOCDIR   = src/tao/linesearch/interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


