# $Id: makefile,v 1.6 2001/08/22 18:02:45 balay Exp $ 

#requiresscalar real

DIRS     = laplacian_q1 burgers_vertex_based_q1 burgers_df_based_q1 ns_q1q0 ns_q2q1
LOCDIR   = src/contrib/oberman/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

