# $Id: makefile,v 1.2 1999/11/05 14:48:09 bsmith Exp bsmith $ 

#requiresscalar real

DIRS     = laplacian_q1 burgers_vertex_based_q1
LOCDIR   = src/contrib/oberman

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

