# $Id: makefile,v 1.5 2000/08/17 04:53:29 bsmith Exp balay $ 

#requiresscalar real

DIRS     = laplacian_q1 burgers_vertex_based_q1 burgers_df_based_q1 ns_q1q0 ns_q2q1
LOCDIR   = src/contrib/oberman

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

