# $Id: makefile,v 1.13 2000/08/17 19:56:51 balay Exp balay $ 

ALL:

LOCDIR   = src/sys/src/draw/examples/
DIRS     = tests tutorials

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
