# $Id: makefile,v 1.8 1998/06/12 21:15:29 balay Exp balay $ 

ALL:

CFLAGS   =
FFLAGS   =
SOURCEC	 = 
SOURCEF	 =
SOURCEH	 =
OBJSC	 =
OBJSF	 = 
LIBBASE	 = libpetscdraw
LOCDIR   = src/draw/examples/
DIRS     = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
