#PETSC_DIR = ../../..
ALL:

CFLAGS	        = $(CPPFLAGS) -D__DIR__='"$(LOCDIR)"'
FFLAGS	        = 
SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        = 
LIBBASE	        = libpetscdraw
LOCDIR          = src/draw/examples/
DIRS            = tests tutorials

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base
