# $Id: makefile,v 1.26 1998/06/15 16:02:09 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ls.c
SOURCEF  =
SOURCEH  = ls.h
OBJSC    = ls.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/ls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

