-include ../petscdir.mk
#requiresdefine   'PETSC_HAVE_ATTRIBUTEALIGNED'
CFLAGS	         =
FFLAGS	         =
CPPFLAGS         =
FPPFLAGS         =
EXAMPLESC        = ex1.c ex2.c ex1_nest.c
LOCDIR		 = src/ksp/ksp/tutorials/network/
MANSEC           = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
