-include ../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_ATTRIBUTEALIGNED'

EXAMPLESC        = ex1.c ex2.c ex1_nest.c ex3.c ex4.c
LOCDIR		 = src/ksp/ksp/tutorials/network/
MANSEC           = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
