ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = linesearchbasic.c
SOURCEF  =
SOURCEH  = basicimpls.h
OBJSC    = linesearchbasic.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/linesearch/impls/basic/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
