#requirespackage  'PETSC_HAVE_BOOST'
#requireslanguage CXXONLY

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = supportgraph.c lowstretch.cpp
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/supportgraph/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
