#requireslanguage CXXONLY

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = supportgraph.c lowstretch.cpp
SOURCEF  =
SOURCEH  = 
OBJSC    = supportgraph.o lowstretch.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/supportgraph/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
