
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = supportgraph.c
SOURCEF  =
SOURCEH  = 
OBJSC    = supportgraph.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/supportgraph/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
