
ALL: lib

SOURCEH = 
DIRS    = tutorials
LOCDIR  = src/vec/vec/utils/tagger/examples
MANSEC  = Vec

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

