
# $Id: makefile,v 1.33 1998/06/15 15:55:29 balay Exp bsmith $

ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  = ${X11_INCLUDE} 
SOURCEC   = xinit.c  frame.c wmap.c xcolor.c xops.c text.c tone.c drawopenx.c
SOURCEF   =
SOURCEH   = ximpl.h
OBJSC     = xinit.o frame.o wmap.o xcolor.o xops.o text.o tone.o drawopenx.o
OBJSF     =
MANSEC    = x
LIBBASE   = libpetsc
DIRS      = 
LOCDIR    = src/draw/impls/x/
NOADIC    = true

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
