ITOOLSDIR = ../../..

ALL: lib 
CFLAGS    = $(OPT) -I../.. $(INCLUDEDIRS) -I$(ITOOLSDIR)/pinclude \
            $(XINCLUDEDIR) $(CONF)
SOURCEC   = xinit.c  
SOURCEF   =
SOURCEH   =
OBJSC     = xinit.o
OBJSF     =
WSOURCEC  =   
WOBJS     = 
MANSEC    = 7
LINCLUDE  = $(SOURCEH)
LIBBASE   = libpetscdraw
DIRS      = 

include $(ITOOLSDIR)/bmake/$(PARCH)/$(PARCH)
