# $Id: makefile,v 1.1 1999/04/21 02:04:12 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
LOCDIR   = src/mat/impls/maij/seq/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
