# $Id: makefile,v 1.2 1999/04/21 18:16:43 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = maij.c 
SOURCEF  =
SOURCEH  = 
OBJSC    = maij.o
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
LOCDIR   = src/mat/impls/maij/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
