#! /bin/csh
# $Id: buildtest,v 1.6 2001/04/05 15:41:00 curfman Exp $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set TMP=/home/petsc/petsc-test
set MACH=petsc@eris.disturbed.net
set ARCH=freebsd
set TEST=testexamples_
set NICE=''
set RSH=ssh
set RSYNCSSH='-z -e ssh'
set RCP='scp -q -B'
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=g_complex 
  set JOBS=(1 2 3 5 10 13)       
else if ($day == Mon) then
  set BOPT=O_complex    
  set JOBS=(1 2 3 5 10 13)
else if ($day == Tue) then
  set BOPT=O        
  set JOBS=(1 2 3 6 8)
else if ($day == Wed) then
  set BOPT=g_c++
  set JOBS=(1 2 3 6 8 13)
else if ($day == Thu) then
  set BOPT=O_c++
  set JOBS=(1 2 3 6 8 13)
else if ($day == Fri) then
  set BOPT=O        
  set JOBS=(1 2 3 6 8)        
else if ($day == Sat) then
  set BOPT=g    
  set JOBS=(1 2 3 6 8 13)        
endif
