# $Id: makefile,v 1.4 1998/04/24 01:03:56 bsmith Exp balay $ 

ALL: lib

SOURCEC  =
SOURCEF  =
SOURCEH  = ecimpl.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = interface impls examples
LOCDIR   = src/ec/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
