#! /bin/csh
#
#  Tests many of the DA variants
#
#  w = degress of freedom per node
#  s = stencil width
#  M,N,P = global dimension in each direction of array
#  m,n,p = number of processors in each dimension
#  star = star stencil

  foreach np (2 4 8 16)
  foreach M (16 31)
  foreach N (14 35)
  foreach w (1 2 3)
  foreach s (1 2 3)
    echo 'lmpirun -np' $np' ex4 -nox -test_order -w' $w ' -s' $s
    mpirun ex4 -nox -test_order -w $w -s $s -M $M -N $N
  end
  end
  end
  end
  end
  echo " "


