# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = blmvm.c
SOURCEF  = 
SOURCEH  = blmvm.h
OBJSC    = blmvm.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = solver
LOCDIR   = src/bound/impls/blmvm/

include ${TAO_DIR}/conf/tao_base

