ALL: lib

DIRS     = lmvm nls neldermead cg ntl ntr owlqn bmrm
LOCDIR   = src/tao/unconstrained/impls/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

