
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = dmakkt.c
OBJSC    = $(SOURCEC:.c=.o)
SOURCEH  = dmakkt.h
LIBBASE  = libpetscdm
DIRS     = 
LOCDIR   = src/dm/impls/akkt/
MANSEC   = DM


include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

