
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = ../../../include/petsc/private/vecimpl.h ../../../include/petscvec.h
DIRS     = impls interface tests
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vscat/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
