
ALL: lib

DIRS      = socket ascii binary string draw vu mathematica hdf5 matlab ams vtk glvis adios adios2
LOCDIR    = src/sys/classes/viewer/impls/
MANSEC    = Sys
SUBMANSEC = Viewer

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
