
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/vec/vscat/tests/
EXAMPLESC       = ex1.c ex4.c ex5.c ex6.c ex7.c ex8.c ex9.c
EXAMPLESF       =
MANSEC          = Vec

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
