# $Id: makefile,v 1.9 2001/01/23 20:52:32 balay Exp balay $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = drawv.c
SOURCEF  =
SOURCEH  = vdraw.h
OBJSC    = drawv.o
OBJSF    =
MANSEC   = Viewer
LIBBASE  = libpetsc
DIRS     = 
LOCDIR   = src/sys/src/viewer/impls/draw/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
