# $Id: makefile,v 1.2 1998/12/03 04:05:06 bsmith Exp bsmith $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = drawv.c
SOURCEF  =
SOURCEH  =
OBJSC    = drawv.o
OBJSF    =
MANSEC   = v
LIBBASE  = libpetsc
DIRS     = 
LOCDIR   = src/viewer/impls/draw/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
