
#requirespackage 	'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS=
FFLAGS=
SOURCEC=ztaosolverf.c ztaof.c
OBJSC =ztaosolverf.o ztaof.o
SOURCEF=
SOURCEH=
DIR=
LIBBASE=libtao
LOCDIR=src/interface/ftn-custom/

include ${TAO_DIR}/conf/tao_base 
