#requiresscalar    real
ALL: lib

SOURCEH  = 
DIRS     = impls examples
LOCDIR   = src/tao/leastsquares/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

