#requiresscalar    real

SOURCEH  =
DIRS     = impls tests tutorials
LOCDIR   = src/tao/leastsquares/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

