ALL: lib

CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = patchcreate.c patch.c
SOURCEF  =
SOURCEH  =
DIRS     = examples
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPATCH
LOCDIR   = src/dm/impls/patch/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
