
ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC   = tcqmr.c
SOURCEF   =
SOURCEH   = tcqmrimpl.h
OBJSC     = tcqmr.o
OBJSF     = 
EXAMPLESC = 
LIBBASE   = libpetscksp
LOCDIR    = src/ksp/ksp/impls/tcqmr/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
