-include ../../../../../petscdir.mk

SOURCEC   = tcqmr.c
SOURCEF   =
SOURCEH   = tcqmrimpl.h
LIBBASE   = libpetscksp
LOCDIR    = src/ksp/ksp/impls/tcqmr/
MANSEC    = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
