-include ../../../../../petscdir.mk

LOCDIR          = src/dm/impls/plex/tutorials/
MANSEC          = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
