# $Id: makefile,v 1.2 2001/06/21 21:18:01 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pbjacobi.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pbjacobi.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/pbjacobi/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
