# $Id: makefile,v 1.3 2001/08/22 18:01:34 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pbjacobi.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pbjacobi.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/pbjacobi/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
