
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = matcoloring.c matcoloringregi.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
MANSEC   = MatColoring
LOCDIR   = src/mat/color/interface

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
