-include ../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_H2OPUS'

SOURCEC   = pch2opus.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscksp
DIRS      =
MANSEC    = PC
LOCDIR    = src/ksp/pc/impls/h2opus/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
