-include ../../../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'
#requirespackage 'PETSC_HAVE_MKL_SPARSE_OPTIMIZE'

LIBBASE  = libpetscmat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
