-include ../../../../petscdir.mk

EXAMPLESC        = maros.c tomographyADMM.c ex1.c
EXAMPLESF        =
EXAMPLESCH       =
EXAMPLESFH       =
TUTORIALS        =
LOCDIR		 = src/tao/constrained/tutorials/
MANSEC		 =
DOCS		 =
DIRS		 =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

