-include ../petscdir.mk
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/dm/impls/stag/tutorials/
EXAMPLESC       = ex1.c ex2.c ex3.c ex4.c ex6.c
EXAMPLESF       =
MANSEC          = DMSTAG

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
