-include ../../../../../petscdir.mk

SOURCEC   = slda.c
LIBBASE   = libpetscts
MANSEC    = TS
SUBMANSEC = Characteristic

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
