ALL: lib

DIRS     = da sliced composite redundant plex shell patch moab network forest swarm
LOCDIR   = src/dm/impls/
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
