ALL: lib

DIRS     = da adda sliced composite mesh cartesian iga redundant complex shell
LOCDIR   = src/dm/impls
MANSEC   = DM

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
