# $Id: makefile,v 1.14 1998/06/15 16:07:56 balay Exp curfman $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = t
LOCDIR   = src/ts/impls/implicit/
DIRS     = beuler cn pvode

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

