PETSC_DIR = ../../../..

ALL: lib

CFLAGS   = 
SOURCEC  = 
SOURCEF  =
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = t
LOCDIR   = src/ts/impls/implicit/
DIRS     = beuler

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base

