# $Id: makefile,v 1.12 1998/03/19 02:11:15 balay Exp balay $ 

ALL: lib

SOURCEC  = 
SOURCEF  =
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = t
LOCDIR   = src/ts/impls/implicit/
DIRS     = beuler pvode

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

