-include ../../../../../petscdir.mk

SOURCEC  = viss.c
SOURCEH  = vissimpl.h
LIBBASE  = libpetscsnes
MANSEC   = SNES

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

