# $Id: makefile,v 1.5 1998/06/12 21:41:50 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = composite.c
SOURCEF  =
SOURCEH  = 
OBJSC    = composite.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = 4
LOCDIR   = src/pc/impls/composite

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
