# $Id: makefile,v 1.4 1998/04/23 23:35:38 balay Exp balay $ 

ALL: lib

SOURCEC  = composite.c
SOURCEF  =
SOURCEH  = 
OBJSC    = composite.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = 4
LOCDIR   = src/pc/impls/composite

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
