-include ../../../../petscdir.mk

CFLAGS   = ${MATLAB_INCLUDE}
LIBBASE  = libpetscdm
DIRS     = usfft hypre kokkos tests
MANSEC   = DM
SUBMANSEC= DMDA

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
