-include ../../../petscdir.mk
ALL: lib

SOURCEH  =
DIRS     = interface impls tests
LOCDIR   = src/dm/partitioner/
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
