#!/bin/sh
#
#   Runs mpiJava program
#
JAVA=/usr/java1.2
MPIJAVA_DIR=/nfs/mcs-homes07/petsc/software/mpiJava-1.1

if [ $# -lt 1 ]
then
  echo "Usage: mpijavarun <procnum> <classname> <options>"
  exit 1
fi

PNUMBER=$1
shift

CLASSNAME=$1
shift

if test -f $CLASSNAME.jig
then
  rm -f $CLASSNAME.jig
#  echo "There is a $CLASSNAME.jig in the current dir ..."
#  exit 1
fi

cat > $CLASSNAME.jig <<EOF
#!/bin/sh
JAVA=/usr/java1.2
MPIJAVA_DIR=/nfs/mcs-homes07/petsc/software/mpiJava-1.1


if test "$CLASSPATH" = ""
then
    CLASSPATH=.:${MPIJAVA_DIR}/lib/classes
    export CLASSPATH
    LD_LIBRARY_PATH=${MPIJAVA_DIR}/lib
    export LD_LIBRARY_PATH
else
    CLASSPATH=.:${MPIJAVA_DIR}/lib/classes:$CLASSPATH
    export CLASSPATH
    LD_LIBRARY_PATH=${MPIJAVA_DIR}/lib
    export LD_LIBRARY_PATH
fi

cd \`dirname \$0\`

exec $JAVA/bin/java -native $CLASSNAME $CLASSNAME \$*

EOF

chmod a+x $CLASSNAME.jig

mpirun -np $PNUMBER $CLASSNAME.jig $*

rm -f $CLASSNAME.jig

