ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nothread.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
MANSEC   = PetscThreadComm
LOCDIR   = src/sys/threadcomm/impls/nothread/

include ${PETSC_DIR}/lib/petsc-conf/variables
include ${PETSC_DIR}/lib/petsc-conf/rules
include ${PETSC_DIR}/lib/petsc-conf/test

