
#if !defined(INCLUDED_PETSCCONF_H)
#define INCLUDED_PETSCCONF_H
 
#define PARCH_X1
#define PETSC_ARCH_NAME "X1"

#define PETSC_HAVE_POPEN
#define PETSC_HAVE_LIMITS_H
#define PETSC_HAVE_PWD_H 
#define PETSC_HAVE_STRING_H 
#define PETSC_HAVE_STROPTS_H 
#define PETSC_HAVE_MALLOC_H 
#define PETSC_HAVE_DRAND48 
#define PETSC_HAVE_GETDOMAINNAME 
#define PETSC_HAVE_UNAME 
#define PETSC_HAVE_UNISTD_H 
#define PETSC_HAVE_STDLIB_H
#define PETSC_HAVE_SYS_TIME_H 
#define PETSC_HAVE_SYS_UTSNAME_H
#define PETSC_HAVE_GETCWD
#define PETSC_HAVE_SYS_PARAM_H
#define PETSC_HAVE_SYS_STAT_H

#define PETSC_HAVE_FORTRAN_UNDERSCORE 
#define PETSC_SIZEOF_VOID_P 8
#define PETSC_SIZEOF_INT 4
#define PETSC_SIZEOF_DOUBLE 8
#define PETSC_BITS_PER_BYTE 8
#define PETSC_SIZEOF_FLOAT 4
#define PETSC_SIZEOF_LONG 8
#define PETSC_SIZEOF_LONG_LONG 8

#define PETSC_WORDS_BIGENDIAN 1

#define PETSC_HAVE_MEMMOVE

#define PETSC_HAVE_DOUBLES_ALIGNED
#define PETSC_HAVE_DOUBLE_ALIGN_MALLOC

#define PETSC_HAVE_MEMALIGN

#define PETSC_HAVE_FAST_MPI_WTIME

#define PETSC_USE_DBX_DEBUGGER
#define PETSC_HAVE_SYS_RESOURCE_H

#define PETSC_HAVE_RTLD_GLOBAL 1

#define PETSC_HAVE_SLEEP
#define PETSC_CAN_SLEEP_AFTER_ERROR

#define PETSC_USE_KBYTES_FOR_SIZE
#define PETSC_USE_P_FOR_DEBUGGER
#define PETSC_HAVE_PXFGETARG_NEW

#define PETSC_DIR_SEPARATOR '/'
#define PETSC_PATH_SEPARATOR ':'
#define PETSC_REPLACE_DIR_SEPARATOR '\\'
#define PETSC_HAVE_SOCKET
#define PETSC_HAVE_FORK
#define PETSC_USE_32BIT_INT

#define PETSC_HAVE_SYS_SOCKET_H
#define PETSC_HAVE_NETINET_IN_H
#define PETSC_HAVE_NETDB_H
#define PETSC_HAVE_FCNTL_H
#define PETSC_HAVE_STROPTS_H

#endif
