
SOURCEC  = almm.c almmutils.c
SOURCEF  =
SOURCEH  = almm.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/constrained/impls/almm/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

