
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = galerkin.c
SOURCEF  =
SOURCEH  = 
OBJSC    = galerkin.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/galerkin/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
