-include ../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zpythontaof.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetsctao
LOCDIR   = src/tao/python/ftn-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
