-include ../../../../petscdir.mk

SOURCEC  = vi.c
LIBBASE  = libpetscsnes
MANSEC   = SNES
DIRS     = ss rs

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

