
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vi.c
SOURCEF  =
SOURCEH  = viimpl.h
OBJSC    = vi.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/vi/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

