
ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC	  = bag.c
SOURCEF	  =
SOURCEH	  = ../../../include/petscbag.h
OBJSC	  = bag.o
OBJSF	  =
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = f2003-src
LOCDIR	  = src/sys/bag/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

