-include ../../../../petsckdir.mk

SOURCEC  = ntrdc.c
SOURCEF  =
SOURCEH  = ntrdcimpl.h
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/ntrdc/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

