
ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC   = partsimple.c
SOURCEH   =
LIBBASE   = libpetscdm
LOCDIR    = src/dm/partitioner/impls/simple/
MANSEC    = DM
SUBMANSEC =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
