ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = tron.c
SOURCEF  =
SOURCEH  = tron.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/bound/impls/tron/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

