ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = tron.c
SOURCEF  = 
SOURCEH  = tron.h
OBJSC    = tron.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/bound/impls/tron/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

