
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = filev.c vcreatea.c
SOURCEF  =
SOURCEH  =
OBJSC    = filev.o vcreatea.o
OBJSF    =
MANSEC   = Viewer
LIBBASE  = libpetscsys
DIRS     = 
LOCDIR   = src/sys/viewer/impls/ascii/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
