-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_KOKKOS_KERNELS'

SOURCEC  =
SOURCECU =
SOURCEKOKKOS = veckok.kokkos.cxx
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscvec
MANSEC   = Vec
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

