# $Id: makefile,v 1.9 1999/03/17 23:23:28 bsmith Exp bsmith $ 
#
ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS = 
SOURCEC  = partition.c spartition.c
SOURCEH  = 
OBJSC    = partition.o spartition.o
DOCS     = 
LIBBASE  = libpetscmat
LOCDIR   = src/mat/partition/
MANSEC   = MatOrderings
DIRS     = impls

runexamples:

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
