
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = zts.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = zts.o
OBJSF    = 
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/ftn-custom/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


