ALL: lib

SOURCEH	 =
SOURCEC  = dlregissf.c sfregi.c sf.c sftype.c
LIBBASE	 = libpetscvec
DIRS	 =
LOCDIR   = src/vec/is/sf/interface/
MANSEC   = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

