ALL: lib

SOURCEH	 =
SOURCEC  = dlregissf.c sfregi.c sf.c sftype.c
LIBBASE	 = libpetscvec
DIRS	 =
LOCDIR   = src/vec/is/sf/interface/
MANSEC   = PetscSF

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

