
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = spacepoly.c
SOURCEF   =
LIBBASE   = libpetscdm
DIRS      =
LOCDIR    = src/dm/dt/space/impls/poly/
MANSEC    = DM
SUBMANSEC = SPACE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
