# $Id: makefile,v 1.13 2000/08/17 04:51:34 bsmith Exp balay $ 

ALL: lib

DIRS     = seq mpi
LOCDIR   = src/mat/impls/baij/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
