
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = broyden.c
SOURCEF  =
SOURCEH  = broydenimpl.h
OBJSC    = broyden.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/broyden/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
