
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ksponly.c
SOURCEF  =
SOURCEH  =
OBJSC    = $(SOURCEC:.c=.o)
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/ksponly/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

