# http://travis-ci.org/petsc/petsc

#notifications:
#  email: false

language: cpp
compiler: gcc

os: linux
sudo: false
dist: trusty

env:

  global:
    - FC=gfortran
    - BLASLAPACK=
    - PETSC_OPTIONS='-check_pointer_intensity 0 -malloc_test'
    - OPTFLAGS='-O'

  matrix:

    - INT64=0  SCALAR=real     PRECISION=single
    - INT64=0  SCALAR=real     PRECISION=double
    - INT64=0  SCALAR=complex  PRECISION=single
    - INT64=0  SCALAR=complex  PRECISION=double

    - INT64=1  SCALAR=real     PRECISION=single
    - INT64=1  SCALAR=real     PRECISION=double
    - INT64=1  SCALAR=complex  PRECISION=single
    - INT64=1  SCALAR=complex  PRECISION=double

    - INT64=0  SCALAR=complex  PRECISION=single  LANGUAGE=C++
    - INT64=0  SCALAR=complex  PRECISION=double  LANGUAGE=C++
    - INT64=1  SCALAR=complex  PRECISION=single  LANGUAGE=C++
    - INT64=1  SCALAR=complex  PRECISION=double  LANGUAGE=C++

    - INT64=0  SCALAR=real     PRECISION=__float128 BLASLAPACK="--download-f2cblaslapack=1"
    - INT64=0  SCALAR=complex  PRECISION=__float128 BLASLAPACK="--download-f2cblaslapack=1"
    - INT64=1  SCALAR=real     PRECISION=__float128 BLASLAPACK="--download-f2cblaslapack=1"
    - INT64=1  SCALAR=complex  PRECISION=__float128 BLASLAPACK="--download-f2cblaslapack=1"

matrix:

  include:

    - env: INT64=1 SCALAR=complex LANGUAGE=C
      compiler: clang

    - env: INT64=1 SCALAR=complex LANGUAGE=C++
      compiler: clang

#   - env: INT64=0 SCALAR=real LANGUAGE=C
#     compiler: clang
#     os: osx
#   - env: INT64=1 SCALAR=complex LANGUAGE=C++
#     compiler: clang
#     os: osx

#   - env: MPI=mpich
#     compiler: clang
#     os: osx
#   - env: MPI=mpich INT64=1 SCALAR=complex LANGUAGE=C++
#     compiler: clang
#     os: osx

#   - env: MPI=openmpi
#     compiler: clang
#     os: osx
#   - env: MPI=openmpi INT64=1 SCALAR=complex LANGUAGE=C++
#     compiler: clang
#     os: osx

git:
  depth: 3
branches:
  only:
    - release
    - master
    - /^pr\/.*$/
    - /^ci\/.*$/

addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev

osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export TMPDIR=/tmp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc $MPI; fi
  - if [[ -n "$MPI" ]]; then export CC=mpicc CXX=mpicxx FC=mpifort; fi
  - export NBUILD=`getconf _NPROCESSORS_ONLN`
install:
  - ./configure --with-cc=$CC --with-cxx=$CXX --with-fc=$FC --with-clanguage=${LANGUAGE:-C} --with-64-bit-indices=${INT64:-0} --with-scalar-type=${SCALAR:-real} --with-precision=${PRECISION:-double} --with-mpi=${MPI:-0} $BLASLAPACK COPTFLAGS="$OPTFLAGS" CXXOPTFLAGS="$OPTFLAGS" FOPTFLAGS="$OPTFLAGS" --with-cxx-dialect=0
  - make -j$NBUILD

script:
  - make check
# - make alltests ALLTESTS_CHECK_FAILURES=yes TIMEOUT=600
