-include ../../../../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pythontao.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetsctao
DIRS     =
LOCDIR   = src/tao/python/
MANSEC   = TAO

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
