# $Id: makefile,v 1.3 2000/08/17 04:50:32 bsmith Exp balay $

ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  = 
SOURCEC   = pops.c
SOURCEF   =
SOURCEH   = psimpl.h
OBJSC     = pops.o
OBJSF     =
MANSEC    = Draw
LIBBASE   = libpetsc
DIRS      = 
LOCDIR    = src/sys/src/draw/impls/ps/
NOADIC    = true

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
