# $Id: makefile,v 1.27 2000/08/17 04:50:17 bsmith Exp balay $

ALL: lib

DIRS     = socket ascii binary string ams draw
LOCDIR   = src/sys/src/viewer/impls/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
