ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = poundersb.c
SOURCEF  = 
SOURCEH  = poundersb.h 
OBJSC    = poundersb.o 
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = 
LOCDIR   = src/tao/leastsquares/impls/poundersb/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

