ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = poundersb.c
SOURCEF  = 
SOURCEH  = poundersb.h 
LIBBASE  = libpetsctao
MANSEC   = 
LOCDIR   = src/tao/leastsquares/impls/poundersb/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

