
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = multiblock.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/multiblock/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
