ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vtkv.c
SOURCEF  =
SOURCEH  = vtkvimpl.h
OBJSC    = $(SOURCEC:.c=.o)
OBJSF    =
MANSEC   = Viewer
LIBBASE  = libpetscsys
DIRS     =
LOCDIR   = src/sys/viewer/impls/vtk/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
