-include ../../../../../petscdir.mk

LIBBASE  = libpetscksp
DIRS     = cgne gltr nash stcg pipecg pipecgrr groppcg pipelcg pipeprcg pipecg2
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
