
ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = cputime.c fdate.c nt_time.c rs6000_time.c
SOURCEF	  =
SOURCEH	  = 
OBJSC	  = cputime.o fdate.o nt_time.o rs6000_time.o
OBJSF	  =
MANSEC	  = Sys
LIBBASE	  = libpetsc
DIRS	  = 
LOCDIR	  = src/sys/src/time/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
