-include ../../../petsckdir.mk

SOURCEC	  = cputime.c fdate.c
SOURCEF	  =
SOURCEH	  = ../../../include/petsctime.h
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/time/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
