-include ../../../../../petscdir.mk

SOURCEC  =
SOURCEF  =
SOURCEH  =
DIRS     = interface impls
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPlex
LOCDIR   = src/dm/impls/plex/transform/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
