# $Id: makefile,v 1.4 1999/04/07 02:49:56 bsmith Exp bsmith $ 

ALL:

LOCDIR	 = src/contrib/pc/spai/examples
DIRS	 = tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test