# $Id: makefile,v 1.2 1998/06/15 16:31:37 balay Exp balay $ 

ALL:

CFLAGS   = 
FFLAGS	 = 
SOURCEC	 = 
SOURCEF	 = 
SOURCEH	 = 
OBJSC	 = 
OBJSF	 = 
LIBBASE	 = libpetscmat
LOCDIR	 = src/mat/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
