ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taocg.c
SOURCEF  =
SOURCEH  = taocg.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/unconstrained/impls/cg/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

