ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = cg.c
SOURCEF  = 
SOURCEH  = cg.h
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/tao/unconstrained/impls/cg/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

