ALL: lib

CPPFLAGS = 
CFLAGS   = 
FFLAGS   =
SOURCEC  = ddlayout.c vecdd.c
SOURCEF  = 
SOURCEH  = ddlayout.h
OBJSC    = ddlayout.o vecdd.o
OBJSF    =
DIRS     = 
LIBBASE  = libpetscdm
MANSEC   = Mat
LOCDIR   = src/dm/dd/vecdd/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
