#! /bin/csh

foreach matrix (arco1 cfd.1.10)

  foreach blocksize (1 2 3 4 5 6 23)

    echo "LU matrix $matrix blocksize $blocksize"
    mpirun.ch_p4 ex10 -f0 /home/bsmith/petsc/src/mat/examples/matrices/$matrix -pc_type lu -mat_block_size $blocksize -mat_seqbaij -log_summary

    foreach level (0 1 2 3 4 5 )

      echo "matrix $matrix blocksize $blocksize level $level "
      mpirun.ch_p4 ex10 -f0 /home/bsmith/petsc/src/mat/examples/matrices/$matrix -pc_type ilu -pc_ilu_levels $level -matload_block_size $blocksize -mat_seqbaij -log_summary

    end

  end

end
