# $Id: makefile,v 1.29 1999/02/03 16:11:18 balay Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = view.c flush.c viewregall.c viewreg.c viewa.c dlregis.c dlregispetsc.c viewers.c
SOURCEF  =
SOURCEH  = 
OBJSC    = view.o flush.o viewregall.o viewreg.o viewa.o dlregis.o dlregispetsc.o viewers.o
OBJSF    =
LIBBASE  = libpetsc
MANSEC   = Viewer
LOCDIR   = src/sys/src/viewer/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

