# $Id: makefile,v 1.21 1998/04/23 23:30:15 balay Exp balay $

ALL: lib

SOURCEC  = view.c 
SOURCEF  =
SOURCEH  = 
OBJSC    = view.o 
OBJSF    =
LIBBASE  = libpetscsys
MANSEC   = v
LOCDIR   = src/viewer/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

