#
ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS = 
SOURCEC  = hem.c
SOURCEH  = 
LIBBASE  = libpetscmat
LOCDIR   = src/mat/coarsen/impls/hem/
MANSEC   = MatOrderings

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
