-include ../../../../../petscdir.mk

SOURCEC   = hem.c
SOURCEH   =
LIBBASE   = libpetscmat
MANSEC    = Mat
SUBMANSEC = MatOrderings

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
