ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nasm.c
SOURCEF  =
SOURCEH  =
OBJSC    = nasm.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/nasm/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
