-include ../../../../petscdir.mk

SOURCEC  = nasm.c aspin.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/nasm/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
