-include ../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = matdummy.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscmat
MANSEC   = Mat
DIRS     =
LOCDIR   = src/mat/impls/dummy/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
