# $Id: makefile,v 1.28 1999/01/31 16:08:02 bsmith Exp bsmith $ 

ALL: lib

SOURCEH  = pcimpl.h
DIRS     = interface impls  examples
LOCDIR   = src/sles/pc/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
