# $Id: makefile,v 1.31 2001/08/22 18:01:15 balay Exp $ 

ALL: lib

SOURCEH  = pcimpl.h ../../../include/petscpc.h
DIRS     = interface impls  examples
LOCDIR   = src/sles/pc/
MANSEC   = PC

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
