# $Id: makefile,v 1.31 1998/04/23 23:33:02 balay Exp balay $

ALL: lib 

CFLAGS   = 
FFLAGS   =
SOURCEC  = cg.c cgeig.c cgtype.c
SOURCEF  =
SOURCEH  = cgctx.h 
OBJSC    = cg.o cgeig.o cgtype.o
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = 5
LOCDIR   = src/ksp/impls/cg/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
