
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = damg.c damgsnes.c
SOURCEF  =
SOURCEH  = 
OBJSC    = damg.o damgsnes.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = DA
DIRS     = 
EDIRS    = 
LOCDIR   = src/snes/utils/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

