
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dmsnes.c dmdasnes.c dmlocalsnes.c dmplexsnes.c convest.c dmadapt.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES
DIRS     =
EDIRS    =
LOCDIR   = src/snes/utils/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

