-include ../../../petscdir.mk

SOURCEC  = dmsnes.c dmdasnes.c dmlocalsnes.c dmplexsnes.c convest.c dmadapt.c
LIBBASE  = libpetscsnes
MANSEC   = SNES

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

