ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pounders.c gqt.c
SOURCEF  = 
SOURCEH  = pounders.h 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/tao/leastsquares/impls/pounders/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

