
SOURCEC  = tsadapt.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/adapt/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

