# $Id: matrix.c,v 1.378 2000/08/17 04:51:22 bsmith Exp $
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nn.c
SOURCEF  =
SOURCEH  = nn.h
OBJSC    = nn.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/itersub/nn/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
