# $Id: makefile,v 1.4 2001/04/19 22:37:49 balay Exp balay $
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nn.c
SOURCEF  =
SOURCEH  = nn.h
OBJSC    = nn.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/is/nn/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
