ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nn.c
SOURCEF  =
SOURCEH  = nn.h
OBJSC    = nn.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/itersub/nn/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
