
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sysshell.c
SOURCEF  =
SOURCEH  = 
OBJSC    = sysshell.o
OBJSF    =
LIBBASE  = libpetscsys
MANSEC   = Sys
LOCDIR   = src/sys/shell/interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

