-include ../../../../../../petscdir.mk

SOURCEC  = symbrdn.c symbadbrdn.c
SOURCEH  = symbrdn.h
LIBBASE  = libpetscksp
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
