
ALL: lib

SOURCEH  = ../../include/petsc-private/threadcommimpl.h ../../include/petscthreadcomm.h
DIRS     = interface impls
LOCDIR   = src/sys/
MANSEC   = PetscThreadComm

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules


