ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = linesearchcp.c
SOURCEF  =
SOURCEH  =
OBJSC    = linesearchcp.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/linesearch/impls/cp/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
