ALL: lib

SOURCEH	 =
SOURCEC  = dlregissf.c sfregi.c sf.c sftype.c
LIBBASE	 = libpetscsys
DIRS	 =
LOCDIR   = src/sys/classes/sf/interface/
MANSEC   = PetscSF

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

