-include ../../../../../../../petscdir.mk

SOURCEC   = sfallgatherv.c
LIBBASE   = libpetscvec
MANSEC    = Vec
SUBMANSEC = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
