
SOURCEH  =
DIRS     = interface impls
LOCDIR   = src/ts/adapt/
MANSEC   = TS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

