
#requirespackage 'PETSC_HAVE_YAML'

ALL: lib
SOURCEH   =
SOURCEC   = yamlimpls.c
DIRS      =
LOCDIR    = src/sys/yaml/
MANSEC    = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
