
#requirespackage 'PETSC_HAVE_YAML'

ALL: lib
SOURCEH   = yamlimpls.h
SOURCEC   = yamlimpls.c
DIRS      =
LOCDIR    = src/sys/yaml/
MANSEC    = Sys

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
