
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/blockmat/
DIRS     = seq

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
