# $Id: makefile,v 1.2 2001/09/19 16:09:57 bsmith Exp bsmith $

#requireslanguage  CPP
#requiresscalar    real 
#requiresprecision double
#requirespackage   'PETSC_HAVE_CXX_NAMESPACE'

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = esles.c
OBJSC    = esles.o
SOURCEH  = ../../../include/esi/petsc/solveriterative.h
LIBBASE  = libpetscsles
MANSEC   = 
LOCDIR   = src/sles/esi/


include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


