#! /bin/csh
# $Id: buildtest,v 1.4 2001/06/21 21:14:27 bsmith Exp $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set TMP=/sandbox/petsc/petsc-test
set MACH=lyre
set ARCH=linux_gcc_pgf90
set TEST=testexamples_
set NICE=''
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=g_c++
  set JOBS=(1 2 3 6 8 13 18)
else if ($day == Mon) then
  set BOPT=g    
  set JOBS=(1 2 3 6 8 13)        
else if ($day == Tue) then
  set BOPT=O        
  set JOBS=(1 2 3 6 8)        
else if ($day == Wed) then
  set BOPT=g_complex 
  set JOBS=(1 2 3 5 10)       
else if ($day == Thu) then
  set BOPT=O_c++
  set JOBS=(1 2 3 6 8 13 18)
else if ($day == Fri) then
  set BOPT=O_complex    
  set JOBS=(1 2 3 5 10 13)
else if ($day == Sat) then
  set BOPT=O        
  set JOBS=(1 2 3 6 8 13)
endif






