
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zdmdasnesf.c zdmlocalsnesf.c zdmsnesf.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES
DIRS     =
EDIRS    =
LOCDIR   = src/snes/utils/ftn-custom/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

