# $Id: makefile,v 1.3 2001/08/06 21:19:01 bsmith Exp balay $ 

#requirespackage  'PETSC_HAVE_SAMG'
#requireslanguage  CONLY
#requiresscalar    real 
#requiresprecision double

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  = 
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = PC
LOCDIR   = src/contrib/lahaye/samg

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
