
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = bcgsl.c
SOURCEH  = bcgslimpl.h
SOURCEF  =
OBJSC    = bcgsl.o
OBJSF    =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/bcgsl/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
