ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = linesearchbt.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/linesearch/impls/bt/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
