-include ../../../../../petscdir.mk
#requirespackage   'PETSC_HAVE_SPAI'

CPPFLAGS  = ${SPAI_INCLUDE}
SOURCEC   = ispai.c dspai.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscksp
DIRS      =
MANSEC    = KSP
SUBMANSEC = PC

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


