-include ../../../../petscdir.mk

MANSEC		 = Tao
DOCS		 =
DIRS		 =
CLEANFILES       = minsurf1 blackscholes

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

