# $Id: makefile,v 1.10 1998/06/15 15:45:10 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscfortran
DIRS     = custom f90
EDIRS    = kernels
LOCDIR   = src/fortran/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

