# $Id: makefile,v 1.15 2001/08/22 18:02:56 balay Exp balay $ 

ALL: lib

DIRS     = auto custom f90 fsrc kernels
XDIRS    = auto
LOCDIR   = src/fortran/
MANSEC   = Sys

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

