PETSC_DIR = ../..

ALL: lib

CFLAGS   = 
SOURCEC  = 
SOURCEF  =
SOURCEH  = 
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscfortran
DIRS     = custom
LOCDIR   = src/fortran/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base

