#

#requirespackage   'PETSC_USING_F90'

CFLAGS    =
FFLAGS    =
SOURCEC   =
SOURCEF   =
SOURCEH   = tao.h tao_sys.h tao_util.h taosolver.h taolinesearch.h 
OBJSC     =
OBJSF     =
LIBBASE   = libtaosolver
DIRS      = 
MANSEC    = 
LOCDIR    = include/finclude/


include ${TAO_DIR}/conf/tao_base

