# $Id: makefile,v 1.23 1998/06/15 15:41:11 balay Exp balay $ 

CFLAGS    =
FFLAGS    =
SOURCEC   =
SOURCEF   =
SOURCEH   = petsc.h vec.h snes.h da.h draw.h mat.h ksp.h pc.h sles.h viewer.h is.h \
            ao.h mg.h petsclog.h sys.h ts.h is.h90 vec.h90 mat.h90 da.h90
OBJSC     =
OBJSF     =
LIBBASE   = libpetscvec
DIRS      = 
MANSEC    = Sys
LOCDIR    = include/finclude/
NOADIC    = true

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

runexamples:




