# $Id: makefile,v 1.27 2000/05/08 15:10:00 balay Exp bsmith $ 

CFLAGS    =
FFLAGS    =
SOURCEC   =
SOURCEF   =
SOURCEH   = petsc.h petscdef.h petsclog.h petscvec.h petscsnes.h petscda.h petscdraw.h petscmat.h \
	    petscksp.h petscpc.h petscsles.h petscviewer.h petscis.h petscao.h petscmg.h \
	    petscsys.h petscts.h petscis.h90 petscvec.h90 petscmat.h90 petscda.h90
OBJSC     =
OBJSF     =
LIBBASE   = libpetscvec
DIRS      = 
MANSEC    = Sys
LOCDIR    = include/finclude/
NOADIC    = true

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test







