#
ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS = 
SOURCEC  = mis.c
SOURCEH  = 
OBJSC    = mis.o
LIBBASE  = libpetscmat
LOCDIR   = src/mat/coarsen/impls/mis/
MANSEC   = MatOrderings

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
