
#requiresdefine 'PETSC_USING_F90'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zbinvf90.c
SOURCEF  = 
SOURCEH  = 
LIBBASE  = libpetscsys
LOCDIR   = src/sys/viewer/impls/binary/f90-custom/


include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


