-include ../../../../../petscdir.mk

SOURCEC  = ipm.c pdipm.c
SOURCEH  = ipm.h
LIBBASE  = libpetsctao
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

