
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ao.c dlregisdm.c aoreg.c aoregall.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscvec
MANSEC   = AO
LOCDIR   = src/vec/is/ao/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
