
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ao.c dlregisdm.c aoreg.c aoregall.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscdm
MANSEC   = AO
LOCDIR   = src/vec/is/ao/interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
