# $Id: makefile,v 1.3 1998/06/15 16:14:43 balay Exp $ 

ALL:

CFLAGS   =
FFLAGS   =
SOURCEC	 = 
SOURCEF	 =
SOURCEH	 =
OBJSC	 =
OBJSF	 = 
LIBBASE	 = 
LOCDIR   = src/adic/examples/
DIRS     = tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
