# $Id: makefile,v 1.5 1997/09/10 18:50:55 balay Exp balay $ 

ALL:

CFLAGS	        = ${CPPFLAGS} -D__SDIR__='"${LOCDIR}"'
FFLAGS	        = 
SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        = 
LIBBASE	        = libpetscvec
LOCDIR          = src/da/examples/
DIRS            = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
