# $Id: makefile,v 1.9 1999/01/31 16:11:36 bsmith Exp bsmith $ 

ALL:

LOCDIR   = src/dm/da/examples/
DIRS     = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
