# $Id: makefile,v 1.7 1998/06/13 05:03:58 balay Exp balay $ 

ALL:

CFLAGS   =
FFLAGS   =
SOURCEC	 = 
SOURCEF	 =
SOURCEH	 =
OBJSC	 =
OBJSF	 = 
LIBBASE	 = libpetscvec
LOCDIR   = src/da/examples/
DIRS     = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
