# $Id: makefile,v 1.5 1998/06/12 21:44:22 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = shvec.c
SOURCEF  =
SOURCEH  = 
OBJSC    = shvec.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 1
LOCDIR   = src/vec/impls/shared/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

