-include ../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_SCALAPACK'

SOURCEC  = matscalapack.c
LIBBASE  = libpetscmat
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
