-include ../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_SCALAPACK'

LIBBASE  = libpetscmat
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
