# $Id: makefile,v 1.23 1998/06/03 21:31:16 balay Exp balay $ 

ALL: lib

CFLAGS   = 
SOURCEC  = bdiag.c bdiag2.c bdfact.c
SOURCEF  =
SOURCEH  = bdiag.h
OBJSC    = bdiag.o bdiag2.o bdfact.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = 2
LOCDIR   = src/mat/impls/bdiag/seq/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
