# $Id: makefile,v 1.3 2000/08/17 04:52:33 bsmith Exp balay $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = minres.c
SOURCEF  =
OBJSC    = minres.o
OBJSF    =
LIBBASE  = libpetscsles
LOCDIR   = src/sles/ksp/impls/minres/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
