-include ../../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_PRAGMATIC'

LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPlex

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
