-include ../../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_PRAGMATIC'

SOURCEC  = pragmaticadapt.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPlex
LOCDIR   = src/dm/impls/plex/adaptors/pragmatic/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
