#requiresscalar    real
ALL: lib

SOURCEH  = 
DIRS     = impls  examples
LOCDIR   = src/tao/pde_constrained/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

