-include ../../../../petscdir.mk

DIRS     = parmetis ptscotch chaco simple shell gather matpart
LIBBASE  = libpetscdm
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

