-include ../../../../../petscdir.mk

SOURCEC   = partmatpart.c
LIBBASE   = libpetscdm
MANSEC    = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
