-include ../../../../../petsckdir.mk

SOURCEC   = partmatpart.c
SOURCEH   =
LIBBASE   = libpetscdm
LOCDIR    = src/dm/partitioner/impls/matpart/
MANSEC    = DM
SUBMANSEC =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
