
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taodm.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = taodm.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/tao/gridsequencing/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


