-include ../../../../petscdir.mk

LOCDIR          = src/dm/label/tutorials/
MANSEC          = DM
SUBMANSEC       = DMLABEL

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
