# $Id: makefile,v 1.31 2001/08/22 18:00:29 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = shell.c shellcnv.c
SOURCEF  =
SOURCEH  = 
OBJSC    = shell.o shellcnv.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/shell/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
