# $Id: makefile,v 1.26 1998/06/12 21:10:25 balay Exp balay $ 

ALL: lib

SOURCEC  = shell.c shellcnv.c
SOURCEF  =
SOURCEH  = 
OBJSC    = shell.o shellcnv.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = 2
LOCDIR   = src/mat/impls/shell/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
