ALL: lib

CFLAGS   = -fopenmp
FFLAGS   =
SOURCEC  = openmp.c
SOURCEF  =
SOURCEH  = 
OBJSC    = openmp.o
OBJSF    =
LIBBASE  = libpetscsys
MANSEC   = PetscThreadComm
LOCDIR   = src/sys/threadcomm/impls/openmp/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

