-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_SPRNG'

CFLAGS   = ${SPRNG_INCLUDE}
SOURCEC  = sprng.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
DIRS     =
MANSEC	 = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

