

/*
*
* List of examples 
*
*/

/** \example ts/examples/tutorials/ex12.c */
/** \example ts/examples/tutorials/ex20.c  */
/** \example ts/examples/tutorials/ex29.c  */
/** \example ts/examples/tutorials/ex24.c  */
/** \example ts/examples/tutorials/ex19.c  */
/** \example ts/examples/tutorials/ex13.c  */
/** \example ts/examples/tutorials/ex4.c  */
/** \example ts/examples/tutorials/ex26.c  */
/** \example ts/examples/tutorials/ex3.c  */
/** \example ts/examples/tutorials/ex14.c  */
/** \example ts/examples/tutorials/ex25.c  */
/** \example ts/examples/tutorials/ex23.c  */
/** \example ts/examples/tutorials/ex7.c  */
/** \example ts/examples/tutorials/ex8.c  */
/** \example ts/examples/tutorials/ex16.c  */
/** \example ts/examples/tutorials/ex5.c  */
/** \example ts/examples/tutorials/power_grid/ex5.c  */
/** \example ts/examples/tutorials/power_grid/ex1.c  */
/** \example ts/examples/tutorials/power_grid/ex2.c  */
/** \example ts/examples/tutorials/power_grid/stability_9bus/ex9bus.c  */
/** \example ts/examples/tutorials/ex6.c  */
/** \example ts/examples/tutorials/ex15.c  */
/** \example ts/examples/tutorials/ex11.c  */
/** \example ts/examples/tutorials/ex27.c  */
/** \example ts/examples/tutorials/ex9.c  */
/** \example ts/examples/tutorials/phasefield/heat.c  */
/** \example ts/examples/tutorials/phasefield/biharmonic2.c  */
/** \example ts/examples/tutorials/phasefield/biharmonic.c  */
/** \example ts/examples/tutorials/phasefield/potentials.c  */
/** \example ts/examples/tutorials/phasefield/biharmonic3.c  */
/** \example ts/examples/tutorials/ex1.c  */
/** \example ts/examples/tutorials/ex17.c  */
/** \example ts/examples/tutorials/advection-diffusion-reaction/ex4.c  */
/** \example ts/examples/tutorials/advection-diffusion-reaction/ex3.c  */
/** \example ts/examples/tutorials/advection-diffusion-reaction/ex7.c  */
/** \example ts/examples/tutorials/advection-diffusion-reaction/ex5.c  */
/** \example ts/examples/tutorials/advection-diffusion-reaction/ex1.c  */
/** \example ts/examples/tutorials/advection-diffusion-reaction/ex2.c  */
/** \example ts/examples/tutorials/advection-diffusion-reaction/ex10.c  */
/** \example ts/examples/tutorials/ex21.c  */
/** \example ts/examples/tutorials/ex2.c  */
/** \example ts/examples/tutorials/ex22.c  */
/** \example ts/examples/tutorials/ex28.c  */
/** \example ts/examples/tutorials/ex10.c  */

/** \example dm/ao/examples/tutorials/ex2.c  */
/** \example dm/impls/mesh/examples/tutorials/ex_coarsen.c  */
/** \example dm/impls/mesh/examples/tutorials/ex_coarsen_3.c  */
/** \example dm/impls/mesh/examples/tutorials/ex_coarsen_2.c  */
/** \example dm/impls/mesh/examples/tutorials/ex1.c  */
/** \example dm/impls/mesh/examples/tutorials/ex_interpolate_1.c  */
/** \example dm/examples/tutorials/ex51.c  */
/** \example dm/examples/tutorials/ex12.c  */
/** \example dm/examples/tutorials/ex19.c  */
/** \example dm/examples/tutorials/ex4.c  */
/** \example dm/examples/tutorials/ex3.c  */
/** \example dm/examples/tutorials/ex14.c  */
/** \example dm/examples/tutorials/ex7.c  */
/** \example dm/examples/tutorials/ex8.c  */
/** \example dm/examples/tutorials/ex5.c  */
/** \example dm/examples/tutorials/ex6.c  */
/** \example dm/examples/tutorials/ex65dm.c  */
/** \example dm/examples/tutorials/ex9.c  */
/** \example dm/examples/tutorials/ex1.c  */
/** \example dm/examples/tutorials/ex2.c  */
/** \example dm/examples/tutorials/ex10.c  */

/** \example vec/vec/examples/tutorials/ex42.c  */
/** \example vec/vec/examples/tutorials/ex12.c  */
/** \example vec/vec/examples/tutorials/ex19.c  */
/** \example vec/vec/examples/tutorials/ex3.c  */
/** \example vec/vec/examples/tutorials/ex7.c  */
/** \example vec/vec/examples/tutorials/ex8.c  */
/** \example vec/vec/examples/tutorials/ex42a.c  */
/** \example vec/vec/examples/tutorials/ex16.c  */
/** \example vec/vec/examples/tutorials/ex5.c  */
/** \example vec/vec/examples/tutorials/ex6.c  */
/** \example vec/vec/examples/tutorials/ex15.c  */
/** \example vec/vec/examples/tutorials/ex11.c  */
/** \example vec/vec/examples/tutorials/ex9.c  */
/** \example vec/vec/examples/tutorials/ex18.c  */
/** \example vec/vec/examples/tutorials/ex1.c  */
/** \example vec/vec/examples/tutorials/ex2.c  */
/** \example vec/vec/examples/tutorials/ex10.c  */
/** \example vec/is/examples/tutorials/ex4.c  */
/** \example vec/is/examples/tutorials/ex3.c  */
/** \example vec/is/examples/tutorials/ex1.c  */
/** \example vec/is/examples/tutorials/ex2.c  */

/** \example ksp/pc/examples/tutorials/ex1.c  */
/** \example ksp/pc/examples/tutorials/ex2.c  */
/** \example ksp/ksp/examples/tutorials/ex30.c  */
/** \example ksp/ksp/examples/tutorials/ex32.c  */
/** \example ksp/ksp/examples/tutorials/ex46.c  */
/** \example ksp/ksp/examples/tutorials/ex42.c  */
/** \example ksp/ksp/examples/tutorials/ex51.c  */
/** \example ksp/ksp/examples/tutorials/ex12.c  */
/** \example ksp/ksp/examples/tutorials/ex29.c  */
/** \example ksp/ksp/examples/tutorials/ex13.c  */
/** \example ksp/ksp/examples/tutorials/ex4.c  */
/** \example ksp/ksp/examples/tutorials/ex34.c  */
/** \example ksp/ksp/examples/tutorials/ex3.c  */
/** \example ksp/ksp/examples/tutorials/ex53.c  */
/** \example ksp/ksp/examples/tutorials/ex25.c  */
/** \example ksp/ksp/examples/tutorials/ex43.c  */
/** \example ksp/ksp/examples/tutorials/ex41.c  */
/** \example ksp/ksp/examples/tutorials/ex52.c  */
/** \example ksp/ksp/examples/tutorials/ex23.c  */
/** \example ksp/ksp/examples/tutorials/ex7.c  */
/** \example ksp/ksp/examples/tutorials/ex8.c  */
/** \example ksp/ksp/examples/tutorials/ex54.c  */
/** \example ksp/ksp/examples/tutorials/ex16.c  */
/** \example ksp/ksp/examples/tutorials/ex49.c  */
/** \example ksp/ksp/examples/tutorials/ex5.c  */
/** \example ksp/ksp/examples/tutorials/ex50.c  */
/** \example ksp/ksp/examples/tutorials/ex55.c  */
/** \example ksp/ksp/examples/tutorials/ex15.c  */
/** \example ksp/ksp/examples/tutorials/ex8g.c  */
/** \example ksp/ksp/examples/tutorials/ex11.c  */
/** \example ksp/ksp/examples/tutorials/ex56.c  */
/** \example ksp/ksp/examples/tutorials/ex40.c  */
/** \example ksp/ksp/examples/tutorials/ex27.c  */
/** \example ksp/ksp/examples/tutorials/ex31.c  */
/** \example ksp/ksp/examples/tutorials/ex9.c  */
/** \example ksp/ksp/examples/tutorials/ex18.c  */
/** \example ksp/ksp/examples/tutorials/ex1.c  */
/** \example ksp/ksp/examples/tutorials/ex39.c  */
/** \example ksp/ksp/examples/tutorials/ex58.c  */
/** \example ksp/ksp/examples/tutorials/ex38.c  */
/** \example ksp/ksp/examples/tutorials/ex2.c  */
/** \example ksp/ksp/examples/tutorials/ex28.c  */
/** \example ksp/ksp/examples/tutorials/ex10.c  */
/** \example ksp/ksp/examples/tutorials/ex45.c  */
/** \example ksp/ksp/examples/tutorials/ex59.c  */

/** \example sys/threadcomm/examples/tutorials/ex4.c  */
/** \example sys/threadcomm/examples/tutorials/ex3.c  */
/** \example sys/threadcomm/examples/tutorials/ex5.c  */
/** \example sys/threadcomm/examples/tutorials/ex1.c  */
/** \example sys/threadcomm/examples/tutorials/ex2.c  */
/** \example sys/shell/examples/tutorials/ex1.c  */
/** \example vec/is/sf/examples/tutorials/ex1.c  */
/** \example sys/classes/viewer/examples/tutorials/ex1.c  */
/** \example sys/classes/viewer/examples/tutorials/ex2.c  */
/** \example sys/classes/random/examples/tutorials/ex1.c  */
/** \example sys/classes/random/examples/tutorials/ex2.c  */
/** \example sys/examples/tutorials/ex4.c  */
/** \example sys/examples/tutorials/ex3.c  */
/** \example sys/examples/tutorials/ex7.c  */
/** \example sys/examples/tutorials/ex5.c  */
/** \example sys/examples/tutorials/ex6.c  */
/** \example sys/examples/tutorials/ex1.c  */
/** \example sys/examples/tutorials/ex2.c  */

/** \example mat/examples/tutorials/ex12.c  */
/** \example mat/examples/tutorials/ex13.c  */
/** \example mat/examples/tutorials/ex4.c  */
/** \example mat/examples/tutorials/ex14.c  */
/** \example mat/examples/tutorials/ex8.c  */
/** \example mat/examples/tutorials/ex16.c  */
/** \example mat/examples/tutorials/ex5.c  */
/** \example mat/examples/tutorials/ex15.c  */
/** \example mat/examples/tutorials/ex11.c  */
/** \example mat/examples/tutorials/ex9.c  */
/** \example mat/examples/tutorials/ex1.c  */
/** \example mat/examples/tutorials/ex17.c  */
/** \example mat/examples/tutorials/ex2.c  */
/** \example mat/examples/tutorials/ex10.c  */

/** \example snes/examples/tutorials/ex30.c  */
/** \example snes/examples/tutorials/ex653D.c  */
/** \example snes/examples/tutorials/ex70.c  */
/** \example snes/examples/tutorials/ex46.c  */
/** \example snes/examples/tutorials/ex42.c  */
/** \example snes/examples/tutorials/ex12.c  */
/** \example snes/examples/tutorials/ex20.c  */
/** \example snes/examples/tutorials/ex65.c  */
/** \example snes/examples/tutorials/ex19.c  */
/** \example snes/examples/tutorials/ex33.c  */
/** \example snes/examples/tutorials/ex4.c  */
/** \example snes/examples/tutorials/ex3.c  */
/** \example snes/examples/tutorials/ex64.c  */
/** \example snes/examples/tutorials/ex53.c  */
/** \example snes/examples/tutorials/ex14.c  */
/** \example snes/examples/tutorials/ex25.c  */
/** \example snes/examples/tutorials/ex43.c  */
/** \example snes/examples/tutorials/ex52.c  */
/** \example snes/examples/tutorials/ex7.c  */
/** \example snes/examples/tutorials/ex10d/ex10.c  */
/** \example snes/examples/tutorials/ex67.c  */
/** \example snes/examples/tutorials/ex54.c  */
/** \example snes/examples/tutorials/ex5.c  */
/** \example snes/examples/tutorials/ex61view.c  */
/** \example snes/examples/tutorials/ex55.c  */
/** \example snes/examples/tutorials/ex15.c  */
/** \example snes/examples/tutorials/ex5s.c  */
/** \example snes/examples/tutorials/ex56.c  */
/** \example snes/examples/tutorials/ex35.c  */
/** \example snes/examples/tutorials/ex62.c  */
/** \example snes/examples/tutorials/ex31.c  */
/** \example snes/examples/tutorials/ex9.c  */
/** \example snes/examples/tutorials/ex18.c  */
/** \example snes/examples/tutorials/ex633D_DB.c  */
/** \example snes/examples/tutorials/ex1.c  */
/** \example snes/examples/tutorials/ex63.c  */
/** \example snes/examples/tutorials/ex61.c  */
/** \example snes/examples/tutorials/ex58.c  */
/** \example snes/examples/tutorials/ex48.c  */
/** \example snes/examples/tutorials/ex21.c  */
/** \example snes/examples/tutorials/ex2.c  */
/** \example snes/examples/tutorials/ex60.c  */
/** \example snes/examples/tutorials/ex22.c  */
/** \example snes/examples/tutorials/ex28.c  */
/** \example snes/examples/tutorials/ex10.c  */
/** \example snes/examples/tutorials/ex72.c  */
/** \example snes/examples/tutorials/ex57.c  */
/** \example snes/examples/tutorials/ex59.c  */
/** \example snes/examples/tutorials/ex61gen.c  */

/** \example docs/doxygen/examples/ex1.c Demo to show that one can link into manuals from examples.
*
*  It's very simple. Just \ref dev-cross-reference-test " click here to get back to the respective section in the developer manual", that's it. :-)
*/

