
ALL: lib

SOURCEH  = ../../../include/petscviewer.h ../../../include/private/viewerimpl.h
DIRS     = impls examples interface
LOCDIR   = src/sys/viewer/
MANSEC   = Viewer

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
