-include ../../../../../petscdir.mk

SOURCEC	 = mpisell.c mmsell.c
SOURCEH	 = mpisell.h
LIBBASE	 = libpetscmat
MANSEC	 = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
