
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = mlocalref.c
SOURCEF  =
SOURCEH  = 
OBJSC    = $(SOURCEC:.c=.o)
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = 
LOCDIR   = src/mat/impls/localref/
MANSEC   = Mat

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

