-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_RANDOM123'

CFLAGS   = ${RANDOM123_INCLUDE}
LIBBASE  = libpetscsys
MANSEC	 = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

