-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_RANDOM123'

CFLAGS   = ${RANDOM123_INCLUDE}
SOURCEC  = random123.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
DIRS     =
LOCDIR   = src/sys/classes/random/impls/random123/
MANSEC	 = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

