-include ../../../../../../../petsckdir.mk

LOCDIR          = src/dm/dt/dualspace/impls/lagrange/tutorials/
EXAMPLESC       =
EXAMPLESF       =
MANSEC          = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

