#requirespackage  'PETSC_USE_SOCKET_VIEWER'
#
#
ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  = 
SOURCEC   = send.c 
SOURCEF   =
SOURCEH   = socket.h 
OBJSC     = send.o 
OBJSF     =
MANSEC    = Viewer
LIBBASE   = libpetscsys
DIRS      = matlab
LOCDIR    = src/sys/viewer/impls/socket/
NOADIC    = true

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


