# $Id: makefile,v 1.26 1998/06/12 21:34:32 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sles.c 
SOURCEF  = 
SOURCEH  = 
OBJSC    = sles.o 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = 3
LOCDIR   = src/sles/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
