# $Id: makefile,v 1.25 1998/04/23 23:29:48 balay Exp balay $ 

ALL: lib

SOURCEC  = sles.c 
SOURCEF  = 
SOURCEH  = 
OBJSC    = sles.o 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = 3
LOCDIR   = src/sles/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
