# $Id: makefile,v 1.32 2001/09/14 17:52:26 bsmith Exp $ 

ALL: lib

SOURCEH  = pcimpl.h ../../../include/petscpc.h
DIRS     = interface impls examples esi
LOCDIR   = src/ksp/pc/
MANSEC   = PC

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
