
ALL: lib

SOURCEH  = pcimpl.h ../../../include/petscpc.h
DIRS     = interface impls examples esi
LOCDIR   = src/ksp/pc/
MANSEC   = PC

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
