# $Id: makefile,v 1.21 1998/06/12 21:43:45 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = umls.c search.c
SOURCEF  = 
SOURCEH  = umls.h
OBJSC    = umls.o search.o
OBJSF    = 
LIBBASE  = libpetscsnes
MANSEC   = n
LOCDIR   = src/snes/impls/umls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

