-include ../../../../../petscdir.mk

SOURCEC  = bmrm.c
SOURCEF  =
SOURCEH  = bmrm.h
LIBBASE  = libpetsctao
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
