# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bmrm.c
SOURCEF  =
SOURCEH  = bmrm.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/unconstrained/impls/bmrm/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
