# $Id: makefile,v 1.34 1999/01/31 16:08:58 bsmith Exp balay $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = cheby.c 
SOURCEF  =
SOURCEH  = chebctx.h
OBJSC    = cheby.o 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = KSP
LOCDIR   = src/sles/ksp/impls/cheby/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
