
ALL: lib

MANSEC   = TS
LOCDIR   = src/ts/impls/symplectic/
DIRS     = bsi

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

