-include ../../../../../petscdir.mk

SOURCEC	 = mpisbaij.c mmsbaij.c sbaijov.c mpiaijsbaij.c
LIBBASE	 = libpetscmat
MANSEC	 = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test




