# $Id: makefile,v 1.4 2001/08/22 18:01:03 balay Exp $ 

ALL: lib

CFLAGS	 =
FFLAGS	 = 
CPPFLAGS = 
FPPFLAGS = 
SOURCEC	 = mpisbaij.c mmsbaij.c sbaijov.c
SOURCEF	 = 
SOURCEH	 = mpisbaij.h
OBJSC	 = mpisbaij.o mmsbaij.o sbaijov.o
OBJSF	 = 
LIBBASE	 = libpetscmat
DIRS	 = spooles
MANSEC	 = Mat
LOCDIR	 = src/mat/impls/sbaij/mpi/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test




