# $Id: makefile,v 1.2 2000/07/07 20:57:39 balay Exp bsmith $ 

ALL: lib

CFLAGS	 = 
FFLAGS	 = 
CPPFLAGS = 
FPPFLAGS = 
SOURCEC	 = mpisbaij.c mmsbaij.c sbaijov.c
SOURCEF	 = 
SOURCEH	 = mpisbaij.h
OBJSC	 = mpisbaij.o mmsbaij.o sbaijov.o
OBJSF	 = 
LIBBASE	 = libpetscmat
DIRS	 = 
MANSEC	 = Mat
LOCDIR	 = src/mat/impls/sbaij/mpi

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test




