# $Id: makefile,v 1.16 1999/04/01 17:10:02 balay Exp $ 

ALL: lib

CFLAGS	 = 
FFLAGS	 = 
CPPFLAGS = 
FPPFLAGS = 
SOURCEC	 = sbaij.c sbaij2.c sbaijfact.c sbaijfact2.c sro.c ss.c
SOURCEF	 = 
SOURCEH	 = sbaij.h
OBJSC	 = sbaij.o sbaij2.o sbaijfact.o sbaijfact2.o sro.o ss.o
OBJSF	 = 
LIBBASE	 = libpetscmat
DIRS     =
MANSEC	 = Mat
LOCDIR	 = src/mat/impls/sbaij/seq/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base





