
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = linesearch.c linesearchregi.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES
DIRS     =
LOCDIR   = src/snes/linesearch/interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

