
ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  = ${PTSCOTCH_INCLUDE}
SOURCEC   = partptscotch.c
SOURCEH   =
LIBBASE   = libpetscdm
LOCDIR    = src/dm/partitioner/impls/ptscotch/
MANSEC    = DM
SUBMANSEC =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
