-include ../../../../../petscdir.mk

CPPFLAGS  = ${PTSCOTCH_INCLUDE}
MANSEC    = Mat
SUBMANSEC = MatGraphOperations

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
