-include ../../../../../petscdir.mk

SOURCEC   = jp.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscmat
MANSEC    = Mat
SUBMANSEC = MatOrderings
LOCDIR    = src/mat/color/impls/jp/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
