# $Id: makefile,v 1.32 1998/06/11 19:54:50 bsmith Exp balay $

ALL: lib

SOURCEC  = vector.c map.c
SOURCEF  =
SOURCEH  = 
OBJSC    = vector.o map.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 1
LOCDIR   = src/vec/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

