# $Id: makefile,v 1.33 1998/06/12 21:34:49 balay Exp balay $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vector.c map.c
SOURCEF  =
SOURCEH  = 
OBJSC    = vector.o map.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 1
LOCDIR   = src/vec/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

