# $Id: makefile,v 1.34 1998/06/15 15:48:52 balay Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vector.c map.c vnake.c
SOURCEF  =
SOURCEH  = 
OBJSC    = vector.o map.o vnake.o
OBJSF    =
LIBBASE  = libpetsc
MANSEC   = 1
LOCDIR   = src/vec/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

