-include ../../../../petscdir.mk

SOURCEC  = matnest.c
SOURCEH  = matnestimpl.h
LIBBASE  = libpetscmat
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

