-include ../../../../petscdir.mk

SOURCEC  = matnest.c
SOURCEF  =
SOURCEH  = matnestimpl.h
LIBBASE  = libpetscmat
DIRS     =
LOCDIR   = src/mat/impls/nest/
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

