-include ../../../../../petscdir.mk

SOURCEC   = deflation.c deflationspace.c
SOURCEF   =
SOURCEH   = deflation.h
LIBBASE   = libpetscksp
DIRS      =
MANSEC    = KSP
SUBMANSEC = PC
LOCDIR    = src/ksp/pc/impls/deflation/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
