# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mfqnls.c
SOURCEF  = 
SOURCEH  = mfqnls.h
OBJSC    = mfqnls.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = solver
LOCDIR   = src/leastsquares/impls/mfqnls/

include ${TAO_DIR}/conf/tao_base

