-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_CUDA'

CXXFLAGS = ${HPDDM_INCLUDE}
LIBBASE  = libpetscksp

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
