#requirespackage 	'PETSC_HAVE_FORTRAN'

SOURCEC = zbrgnf.c
SOURCEF =
SOURCEH =
DIR     =
LIBBASE = libpetsctao
LOCDIR  = src/tao/leastsquares/impls/brgn/ftn-custom

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
