
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = power.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
MANSEC   = MatOrderings
LOCDIR   = src/mat/color/impls/power/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
