-include ../petscdir.mk
ALL: lib

LIBBASE  = libpetscdm
DIRS     = lagrange bdm simple
LOCDIR   = src/dm/dt/dualspace/impls

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
