-include ../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zgcommf.c zgtype.c zoptionsf.c zoptionsyamlf.c zpgnamef.c zpnamef.c zprefixf.c zdestroyf.c zstart.c zstartf.c zversionf.c zinheritf.c zptypef.c zpackage.c
SOURCEF  =
SOURCEH  =
MANSEC   = Sys
DIRS     =
LIBBASE  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
