-include ../../../../../petscdir.mk
#requiresdefine  'PETSC_HAVE_MATLAB'

LIBBASE  = libpetscvec
MANSEC   = Vec

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc


