
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = redistribute.c
SOURCEF  =
SOURCEH  = 
OBJSC    = redistribute.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/redistribute/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
