-include ../../../../petscdir.mk

LOCDIR          = src/ksp/pc/tests/
MANSEC          = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


