ALL: lib 
ITOOLSDIR = ../../../

CFLAGS   = $(OPT) $(CONF) -I$(ITOOLSDIR) -I$(ITOOLSDIR)/include \
           -I$(ITOOLSDIR)/pinclude  -I../../
SOURCEC  = tcqmr.c
SOURCEF  =
WSOURCEC = 
OBJSC    = tcqmr.o
OBJSF    = 
WOBJS    = 
LIBBASE  = libpetscksp
LINCLUDE = 

include $(ITOOLSDIR)/bmake/$(PARCH)

