# $Id: makefile,v 1.30 1998/06/12 21:07:30 balay Exp balay $ 

ALL: lib 

SOURCEC  = tcqmr.c
SOURCEF  =
SOURCEH  = tcqmrp.h
OBJSC    = tcqmr.o
OBJSF    = 
LIBBASE  = libpetscsles
LOCDIR   = src/ksp/impls/tcqmr/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
