#! /bin/csh
# $Id: buildtest,v 1.8 2001/09/07 18:59:02 bsmith Exp $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set TMP=/sandbox/petsc/petsc-test
set MACH=fire
set ARCH=solaris
set TEST=testexamples_
set NICE=''
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=O_complex
  set JOBS=(1 2 3 5 10 12 13 )        
else if ($day == Mon) then
  set BOPT=O
  set JOBS=(1 2 3 6 8 12 14  17)        
else if ($day == Tue) then
  set BOPT=g        
  set JOBS=(1 2 3 6 12 13 14  17)        
else if ($day == Wed) then
  set BOPT=g_c++ 
  set JOBS=(1 2 3 6 8 12 14   17 18)       
else if ($day == Thu) then
  set BOPT=g_complex
  set JOBS=(1 2 3 5 10 12 13 )       
else if ($day == Fri) then
  set BOPT=O_c++    
  set JOBS=(1 2 3 6 8 12 14  17 18)        
else if ($day == Sat) then
  set BOPT=O_single
  set JOBS=(1 3)        
endif






