#! /bin/csh
# $Id: buildtest,v 1.3 2000/02/22 14:56:23 bsmith Exp bsmith $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set TMP=/sandbox/balay/petsc
set MACH=fire
set ARCH=solaris
set TEST=testexamples_
set NICE=''
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=O_complex
  set JOBS=(1 2 3 5 10 13 15)        
else if ($day == Mon) then
  set BOPT=O_c++    
  set JOBS=(1 2 8 13 15 16 17)        
else if ($day == Tue) then
  set BOPT=g        
  set JOBS=(1 2 3 6 7 13 14 16 17)        
else if ($day == Wed) then
  set BOPT=g_c++ 
  set JOBS=(1 2 3 6 8 14 15 16 17)       
else if ($day == Thu) then
  set BOPT=g_complex
  set JOBS=(1 2 3 5 10 13 15)       
else if ($day == Fri) then
  set BOPT=O_c++    
  set JOBS=(1 2 3 6 8 14 15 16 17)        
else if ($day == Sat) then
  set BOPT=O        
  set JOBS=(1 2 3 6 7 8 14 15 17)        
endif






