ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ipm.c
SOURCEF  = 
SOURCEH  = ipm.h
OBJSC    = ipm.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/unconstrained/impls/ipm/

include ${TAO_DIR}/conf/tao_base

