
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pcdmmg.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pcdmmg.o
OBJSF    =
LIBBASE  = libpetscksp
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/mg/dmmg/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
