
ALL: lib

SOURCEH	 = ../../../include/petscdt.h
DIRS	 = interface examples
LOCDIR   = src/dm/dt/
MANSEC    = DM

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

