-include ../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zpartitioner.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscdm
MANSEC   = DM
LOCDIR   = src/dm/partitioner/interface/ftn-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
