
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dmredundant.c
SOURCEF  = 
SOURCEH  = ../../../../include/petscdmredundant.h
OBJSC    = $(SOURCEC:.c=.o)
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMREDUNDANT
LOCDIR   = src/dm/impls/redundant

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
