-include ../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dmredundant.c
SOURCEF  =
SOURCEH  = ../../../../include/petscdmredundant.h
LIBBASE  = libpetscdm
MANSEC   = DM
LOCDIR   = src/dm/impls/redundant/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
