-include ../../../../petscdir.mk

MANSEC     = DM
LOCDIR	   = src/dm/field/tutorials/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

