-include ../../../../petscdir.mk
CFLAGS		 =
FFLAGS		 =
CPPFLAGS   =
FPPFLAGS   =
MANSEC     = DM
LOCDIR		 = src/dm/field/tutorials/
EXAMPLESC	 = ex1.c

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

