
ALL: lib

DIRS     = dense aij shell baij adj maij is sbaij adic normal lrc scatter blockmat composite cufft mffd transpose python submat localref nest fft ij
LOCDIR   = src/mat/impls/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
