# $Id: makefile,v 1.36 2000/06/21 15:49:28 balay Exp balay $

ALL: lib

DIRS     = dense aij shell rowbs bdiag  baij adj maij nn sbaij
LOCDIR   = src/mat/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
