
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = linesearch.c dlregis_taolinesearch.c
SOURCEF  =
SOURCEH  = 
OBJSC    = linesearch.o dlregis_taolinesearch.o
OBJSF    =
LIBBASE  = libtaolinesearch
MANSEC   = LineSearch
LOCDIR   = src/linesearch/interface/

include ${TAO_DIR}/conf/tao_base


