-include ../../../petscdir.mk

SOURCEC   = plexrefbl.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = DMPLEX
LOCDIR    = src/dm/impls/plex/transform/impls/refine/bl

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
