-include ../../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_MMG'

SOURCEC  = mmgadapt.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPlex

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
