-include ../petscdir.mk
ALL: lib

DIRS     = mpi
LOCDIR   = src/mat/impls/adj/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
