# $Id: makefile,v 1.7 1998/06/12 21:23:45 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = seq mpi
LOCDIR   = src/mat/impls/adj/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
