# $Id: makefile,v 1.6 1998/03/19 02:08:28 balay Exp balay $ 

ALL: lib

SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = seq mpi
LOCDIR   = src/mat/impls/adj/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
