#requirespackage 'PETSC_HAVE_KOKKOS_KERNELS'
-include ../../../../../petscdir.mk

MANSEC    = DM
SUBMANSEC = DMPlex

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
