# $Id: makefile,v 1.2 2000/09/25 18:03:04 curfman Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = cholesky.c
SOURCEF  =
SOURCEH  = 
OBJSC    = cholesky.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/cholesky/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
