
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = openmp.c
SOURCEF  =
SOURCEH  = 
OBJSC    = openmp.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/openmp/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
