
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = hpc.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/openmp/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
