
ALL: lib

CFLAGS   = ${PLAPACK_INCLUDE}
FFLAGS   =
SOURCEC  = mpidense.c mmdense.c plapack.c
SOURCEF  =
SOURCEH  = mpidense.h
OBJSC    = mpidense.o mmdense.o plapack.o
OBJSF    =
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat
LOCDIR   = src/mat/impls/dense/mpi/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
