-include ../../../../../../petscdir.mk

SOURCEC   = aomemscalable.c
LIBBASE   = libpetscvec
MANSEC    = Vec
SUBMANSEC = AO

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

