# $Id: makefile,v 1.29 1999/01/31 16:08:11 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = shellpc.c 
SOURCEF  =
SOURCEH  = 
OBJSC    = shellpc.o 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/shell/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
