# $Id: makefile,v 1.5 1997/09/10 18:51:23 balay Exp balay $ 

ALL:

CFLAGS	        = ${CPPFLAGS} ${CONF} -D__SDIR__='"${LOCDIR}"'
FFLAGS	        = 
SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        = 
LIBBASE	        = libpetscsles
LOCDIR          = src/pc/examples/
DIRS            = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
