# $Id: makefile,v 1.7 1998/04/23 23:47:12 balay Exp balay $ 

ALL:

SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        = 
LIBBASE	        = libpetscsles
LOCDIR          = src/pc/examples/
DIRS            = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
