# $Id: makefile,v 1.10 1999/01/31 16:08:29 bsmith Exp bsmith $ 

ALL:

LIBBASE	= libpetscsles
LOCDIR	= src/sles/pc/examples/
DIRS	= tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
