ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ntl.c
SOURCEF  =
SOURCEH  = ntl.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/unconstrained/impls/ntl/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

