#requirespackage   'PETSC_HAVE_FORTRAN'

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  = somefort.F
SOURCEH  =
OBJSC    =
OBJSF    = somefort.o
LIBBASE  = libpetsc
MANSEC   = Sys
LOCDIR   = src/sys/fsrc/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test


