-include ../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_RAJA'

LOCDIR       = src/ksp/ksp/tests/raja/
EXAMPLESCXX  = ex1.raja.cxx
EXAMPLESCH   = memoryManager.hpp
EXAMPLESF    =
DIRS         =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
