-include ../../../../../petscdir.mk

SOURCEC   = fv.c
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = FV

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
