
#requirespackage  'PETSC_HAVE_PARMS'
#requiresprecision double


ALL: lib

CFLAGS   = ${PARMS_INCLUDE}
FFLAGS   =
SOURCEC  = parms.c
SOURCEF  =
SOURCEH  = 
OBJSC    = parms.o
OBJSF    =
LIBBASE  = libpetscksp
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/parms/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

