-include ../../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = spacesubspace.c
SOURCEF   =
LIBBASE   = libpetscdm
DIRS      =
LOCDIR    = src/dm/dt/space/impls/subspace/
MANSEC    = DM
SUBMANSEC = SPACE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
