# $Id: makefile,v 1.3 2000/08/17 04:52:15 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = redundant.c
SOURCEF  =
SOURCEH  = 
OBJSC    = redundant.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/redundant/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
