# $Id: makefile,v 1.1 1999/03/24 03:13:03 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = redundant.c
SOURCEF  =
SOURCEH  = 
OBJSC    = redundant.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/redundant/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
