#ifdef PETSC_RCS_HEADER
"$Id: petscconf.h,v 1.9 2000/11/28 17:26:31 bsmith Exp $"
"Defines the configuration for this machine"
#endif

#if !defined(INCLUDED_PETSCCONF_H)
#define INCLUDED_PETSCCONF_H
 
#define PARCH_IRIX5
#define PETSC_ARCH_NAME "IRIX5"

#define PETSC_HAVE_POPEN
#define PETSC_HAVE_LIMITS_H
#define PETSC_HAVE_PWD_H 
#define PETSC_HAVE_STRING_H 
#define PETSC_HAVE_STROPTS_H 
#define PETSC_HAVE_MALLOC_H 
#define PETSC_HAVE_DRAND48  
#define PETSC_HAVE_GETDOMAINNAME
#define PETSC_HAVE_UNAME 
#define PETSC_HAVE_UNISTD_H 
#define PETSC_HAVE_STDLIB_H
#define PETSC_HAVE_SYS_TIME_H
#define PETSC_HAVE_SYS_UTSNAME_H
#define PETSC_HAVE_GETCWD
#define PETSC_HAVE_SLEEP
#define PETSC_HAVE_SYS_PARAM_H
#define PETSC_HAVE_SYS_STAT_H

#define PETSC_HAVE_FORTRAN_UNDERSCORE
#define PETSC_HAVE_FORTRAN_UNDERSCORE_UNDERSCORE

#define PETSC_HAVE_MEMMOVE
#define PETSC_HAVE_DOUBLES_ALIGNED
#define PETSC_HAVE_DOUBLE_ALIGN_MALLOC

#define PETSC_SIZEOF_VOID_P 4
#define PETSC_SIZEOF_INT 4
#define PETSC_SIZEOF_DOUBLE 8
#define PETSC_BITS_PER_BYTE 8
#define PETSC_SIZEOF_FLOAT 4
#define PETSC_SIZEOF_LONG 4
#define PETSC_SIZEOF_LONG_LONG 8

#define PETSC_HAVE_MEMALIGN

#define PETSC_USE_DBX_DEBUGGER
#define PETSC_HAVE_SYS_RESOURCE_H

#define PETSC_WORDS_BIGENDIAN 1

#define PETSC_HAVE_RTLD_GLOBAL 1

#define PETSC_HAVE_4ARG_SIGNAL_HANDLER

#define PETSC_HAVE_TEMPLATED_COMPLEX
#define PETSC_USE_KBYTES_FOR_SIZE
#define PETSC_USE_P_FOR_DEBUGGER

#if defined(__cplusplus)
#define PETSC_SIGNAL_CAST (void (*)(int))
#endif

#define PETSC_HAVE_IRIX_STYLE_FPTRAP
#define PETSC_PRINTF_FORMAT_CHECK(a,b) __attribute__ ((format (printf, a,b)))
#endif
