# $Id: makefile,v 1.4 1998/04/24 01:03:32 bsmith Exp balay $ 

ALL: lib

SOURCEC  = ec.c ecall.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ec.o ecall.o
LIBBASE  = libpetscec
DIRS     =
MANSEC   = e
LOCDIR   = src/ec/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
