# $Id: makefile,v 1.32 1999/01/31 16:03:26 bsmith Exp curfman $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = general.c strgen.c
SOURCEF  =
SOURCEH  = general.h
OBJSC    = general.o strgen.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 9
LOCDIR   = src/vec/is/impls/seq/general/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

