ITOOLSDIR = ../../../../

ALL: lib

CFLAGS   = $(OPT) -I$(ITOOLSDIR)/include -I../../.. -I$(ITOOLSDIR) $(COPT)
SOURCEC  = general.c 
SOURCEF  =
WSOURCEC = 
SOURCEH  = 
OBJSC    = general.o 
WOBJS    = 
OBJSF    =
LIBBASE  = libpetscvec
SYSLIB   = $(LDIR)/system.a $(BLAS) $(SLIB) -lm 
LOCAL_INCLUDE = $(SOURCEH)

