-include ../../../../petscdir.mk

LOCDIR          = src/ts/tutorials/power_grid/
MANSEC          = TS
DIRS            = stability_9bus
CLEANFILES      = TS-data-*

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
