-include ../../../../petscdir.mk

MANSEC          = TS
DIRS            = stability_9bus
CLEANFILES      = TS-data-*

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
