
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = specest.c
SOURCEF  =
OBJSC    = specest.o
OBJSF    = 
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/specest/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
