#! /bin/csh
#
#  Tests many of the 2-dimensional DA variants
#
#  w = degress of freedom per node
#  s = stencil width
#  NX,NY = global dimension in each direction of array
#  m,n = number of processors in each dimension
#  np = number of processors
#

  foreach m (1 2 3)
   foreach n (1 2 3)
    foreach NX (16 17)
     foreach NY (14 15)
      foreach w (1 2 3)
       foreach s (1 2)
        foreach stencil ('-star' '-box')
         foreach xwrap ('-xperiodic' '-xghosted' '-xnonghosted')
          foreach ywrap ('-yperiodic' '-yghosted' '-ynonghosted')
           set np = `expr $m \* $n`
           echo 'mpiexec -n' $np' ./ex4 -testorder -nox -w' $w '-s' $s '-NX' $NX '-NY' $NY '-m' $m '-n' $n $xwrap $ywrap $stencil
           mpiexec -n $np ./ex4 -testorder -nox -w $w -s $s -NX $NX -NY $NY -m $m -n $n $xwrap $ywrap $stencil
          end
         end
        end
       end
      end
     end
    end
   end
  end
