#! /bin/csh
#
#  Tests many of the 3-dimensional DA variants
#
#  w = degress of freedom per node
#  s = stencil width
#  M,N,P = global dimension in each direction of array
#  m,n,p = number of processors in each dimension
#  np = number of processors
#

  foreach m (1 2 3)
   foreach n (1 2 3)
    foreach p (1 2 3)
     foreach NX (16 17)
      foreach NY (14 15)
       foreach NZ (13 12)
        foreach w (1 2 3)
         foreach s (1 2)
          foreach stencil ('-box' '-star')
           foreach xwrap ('-xperiodic' '-xghosted' '-xnonghosted')
            foreach ywrap ('-yperiodic' '-yghosted' '-ynonghosted')
             foreach zwrap ('-zperiodic' '-zghosted' '-znonghosted')
              set np = `expr $m \* $n \* $p`
              echo 'mpiexec -n' $np' ./ex6 -testorder -nox -w' $w '-s' $s '-NX' $NX '-NY' $NY '-NZ' $NZ '-m' $m '-n' $n '-p' $p $stencil $xwrap $ywrap $zwrap
              mpiexec -n $np ./ex6 -testorder -nox -w $w -s $s -NX $NX -NY $NY -NZ $NZ -m $m -n $n -p $p $stencil $xwrap $ywrap $zwrap
             end
            end
           end
          end
         end
        end
       end
      end
     end
    end
   end
  end


