-include ../../../../../../petscdir.mk

SOURCEC   = aomapping.c
SOURCEH   =
LIBBASE   = libpetscvec
DIRS      =
MANSEC    = Vec
SUBMANSEC = AO
LOCDIR    = src/vec/is/ao/impls/mapping/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
