# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = neldermead.c
SOURCEF  = 
SOURCEH  = neldermead.h
OBJSC    = neldermead.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = taosolver
LOCDIR   = src/unconstrained/impls/neldermead/

include ${TAO_DIR}/conf/tao_base

