
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taodm.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = taodm.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = tao
LOCDIR   = src/gridsequencing

include ${TAO_DIR}/conf/tao_base


