
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taodm.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = taodm.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = taodm
LOCDIR   = src/gridsequencing/

include ${TAO_DIR}/conf/tao_base


