#requiresscalar    real
ALL: lib

SOURCEH  = 
DIRS     = impls utils examples
LOCDIR   = src/tao/bound/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

