-include ../../../petsckdir.mk
#requiresscalar    real

SOURCEH  =
DIRS     = impls utils tutorials
LOCDIR   = src/tao/bound/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

