
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vecnest.c
SOURCEF  =
SOURCEH  = vecnestimpl.h
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/impls/nest/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

