
ALL: lib 
SOURCEH   = ctable.h
DIRS      = viewer draw error dll fileio memory objects time utils plog mpiuni matlabengine f90 \
            adic bag examples ftn-custom 
LOCDIR    = src/sys/
MANSEC    = Sys

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
