# $Id: makefile,v 1.37 1998/06/15 15:46:22 balay Exp balay $ 

ALL: lib 
CFLAGS    =
FFLAGS    =
SOURCEC   =
SOURCEF   =
SOURCEH   = nreg.h ctable.h
OBJSC     =
OBJSF     =
LIBBASE   = libpetscsys
DIRS      = src examples
LOCDIR    = src/sys/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
