-include ../../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = spaceptrimmed.c
SOURCEF   =
LIBBASE   = libpetscdm
DIRS      = tests
LOCDIR    = src/dm/dt/space/impls/ptrimmed/
MANSEC    = DM
SUBMANSEC = SPACE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
