ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taosolver.c taosolver_fg.c taosolverregi.c taosolver_hj.c dlregistaosolver.c
SOURCEF  =
SOURCEH  =
OBJSC    = taosolver.o taosolver_fg.o taosolverregi.o taosolver_hj.o dlregistaosolver.o
OBJSF    =
LIBBASE  = libtaosolver
MANSEC   = TAO_SOLVER
LOCDIR   = src/interface


include ${TAO_DIR}/conf/tao_base