ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taosolver.c taosolverfg.c taosolverregi.c taosolverhj.c dlregibstaosolver.c
SOURCEF  =
SOURCEH  =
OBJSC    = taosolver.o taosolverfg.o taosolverregi.o taosolverhj.o dlregistaosolver.o
OBJSF    =
LIBBASE  = libtaosolver
MANSEC   = TAO_SOLVER
LOCDIR   = src/interface


include ${TAO_DIR}/conf/tao_base