-include ../../../../../petscdir.mk

LIBBASE  = libpetscksp
DIRS     = lgmres fgmres dgmres pgmres pipefgmres agmres
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
