-include ../../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_CUDA'

SOURCECU = vecmpicupm.cu
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/impls/mpi/cupm/cuda/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
