#requirespackage  'PETSC_HAVE_TETGEN'

CPPFLAGS  =
CFLAGS    =
FFLAGS    =
SOURCECXX = tetgenerate.cxx
SOURCEF   =
SOURCEH   =
DIRS      =
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = DMPLEX
LOCDIR    = src/dm/impls/plex/generators/tetgen/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
