#! /bin/csh
#
#  Generates the include files in petsc/include/foldinclude from those in
#  petsc/include/finclude
#
#
#  
cd /home/bsmith/petsc/include/finclude
/bin/rm -f ../foldinclude/*.h
foreach i (*.h *.h90) 
  grep -v "define" $i | grep -v "else" | grep -v "endif" | grep -v "real " | grep -v "include" |grep -v SELECTED_REAL_KIND | sed " s/PetscDoubleExp(-2.0,0)/-2.0d0/" |sed "s/DoubleComplex/double complex/g"| sed "s/Scalar/double precision/g"  | sed "s/Double/double precision/"  |  sed "s/MPI_Comm/integer/g" | sed "s/PetscFortranAddr/integer/g" > ../foldinclude/$i
end
cd /home/bsmith/petsc/include/foldinclude
echo "!   You will have to adjust this line for your site" >> petsc.h
echo "      include 'mpif.h'" >> petsc.h
chmod g+w *.h *.h90
