
ALL: lib

DIRS     = glee basic cfl none
LOCDIR   = src/ts/adapt/impls/
MANSEC   = TS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


