-include ../../../../petscdir.mk

DIRS     = none basic dsp cfl glee history
LOCDIR   = src/ts/adapt/impls/
MANSEC   = TS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
