
ALL: lib

SOURCEH  = ../../../../include/petscviewer.h ../../../../include/petscviewertypes.h ../../../../include/petsc-private/viewerimpl.h
DIRS     = impls examples interface
LOCDIR   = src/sys/classes/viewer/
MANSEC   = Viewer

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
