
SOURCEH   = ../../../../include/petscviewer.h ../../../../include/petscviewertypes.h ../../../../include/petsc/private/viewerimpl.h
DIRS      = impls tests tutorials interface
LOCDIR    = src/sys/classes/viewer/
MANSEC    = Sys
SUBMANSEC = Viewer

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
