-include ../../../../petscdir.mk

DIRS      = impls tests tutorials interface
MANSEC    = Sys
SUBMANSEC = Viewer

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
