
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = zsnes.c zdmmg.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = zsnes.o zdmmg.o
OBJSF    = 
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/custom/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


