
ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC	  = bag.c
SOURCEF	  =
SOURCEH	  = ../../../../include/petscbag.h ../../../../include/petsc-private/bagimpl.h
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = f2003-src
LOCDIR	  = src/sys/classes/bag/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

