# $Id: makefile,v 1.19 1998/06/12 21:07:50 balay Exp balay $ 

ALL: lib 

SOURCEC  = qcg.c
SOURCEF  =
SOURCEH  = qcg.h 
OBJSC    = qcg.o
OBJSF    =
LIBBASE  = libpetscsles
LINCLUDE = 
LOCDIR   = src/ksp/impls/qcg/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
