# $Id: makefile,v 1.23 2000/08/17 04:52:31 bsmith Exp balay $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = qcg.c
SOURCEF  =
SOURCEH  = qcg.h 
OBJSC    = qcg.o
OBJSF    =
LIBBASE  = libpetscsles
LINCLUDE = 
LOCDIR   = src/sles/ksp/impls/qcg/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
