# $Id: makefile,v 1.20 1998/06/12 21:20:55 balay Exp balay $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = qcg.c
SOURCEF  =
SOURCEH  = qcg.h 
OBJSC    = qcg.o
OBJSF    =
LIBBASE  = libpetscsles
LINCLUDE = 
LOCDIR   = src/ksp/impls/qcg/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
