
SOURCEC	  = tv_data_display.c
SOURCEF	  =
SOURCEH	  = tv_data_display.h
MANSEC	  = Profiling
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/totalview/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
