
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vscreate.c dlregisvecscat.c vscatfce.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vscat/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
