
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lmvmmat.c adamat.c submatfree.c
SOURCEF  = 
SOURCEH  = lmvmmat.h submatfree.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/matrix/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


