-include ../../../../../../petsckdir.mk

SOURCEC  = simple.c absolute.c relative.c cdf.c andor.c or.c and.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/utils/tagger/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
