-include ../../../../../../petscdir.mk

SOURCEC  = simple.c absolute.c relative.c cdf.c andor.c or.c and.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscvec
MANSEC   = Vec

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
