-include ../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_H2OPUS'

LIBBASE   = libpetscmat
DIRS      = cuda
MANSEC    = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
