
ALL: lib 

SOURCEH  = randomimpl.h 
DIRS     = interface examples impls 
LOCDIR   = src/sys/random/
MANSEC   = Sys

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

 
