
SOURCEC   = index.c isregall.c isreg.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscvec
MANSEC    = Vec
SUBMANSEC = IS
LOCDIR    = src/vec/is/is/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

