-include ../../../../../petscdir.mk

LIBBASE  = libpetscsys
DIRS     = rand rand48 rander48 sprng random123 curand
MANSEC   = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

