
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
DIRS     = rand rand48 rander48 sprng random123 curand
LOCDIR   = src/sys/classes/random/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

