
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscsys
DIRS     = rand rand48 sprng
LOCDIR   = src/sys/random/impls/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

