-include ../../../../../../petscdir.mk
#requiresdefine  'PETSC_HAVE_MATLAB'

CFLAGS    = ${MATLAB_INCLUDE}
SOURCEC	  = vmatlab.c
SOURCEF	  =
SOURCEH	  =
MANSEC	  = Viewer
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/classes/viewer/impls/matlab/
DIRS      =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


