# $Id: makefile,v 1.26 2001/08/22 18:02:00 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = snestest.c
SOURCEF  =
SOURCEH  = 
OBJSC    = snestest.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/test/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

