# $Id: makefile,v 1.25 1998/04/23 23:32:47 balay Exp balay $

ALL: lib

CFLAGS   = 
SOURCEC  = stride.c
SOURCEF  =
SOURCEH  = 
OBJSC    = stride.o 
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 6
LOCDIR   = src/is/impls/seq/stride/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

