# $Id: makefile,v 1.27 1998/06/12 21:16:17 balay Exp balay $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = stride.c
SOURCEF  =
SOURCEH  = 
OBJSC    = stride.o 
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 6
LOCDIR   = src/is/impls/seq/stride/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

