
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mg.c fmg.c smg.c mgfunc.c 
SOURCEF  =
SOURCEH  = mgimpl.h ../../../../../include/petscpcmg.h
LIBBASE  = libpetscksp
MANSEC   = PC
SUBMANSEC= PCMG
LOCDIR   = src/ksp/pc/impls/mg/
DIRS     = 

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
