# $Id: makefile,v 1.4 1998/06/15 15:46:57 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS = 
SOURCEC  = adpetscadic.c petscadic.c
SOURCEF  =
SOURCEH  = 
OBJSC    = adpetscadic.o petscadic.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = 1
LOCDIR   = src/adic/src/

include ${PETSC_DIR}/conf/base

