
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = transm.c
SOURCEF  =
SOURCEH  = 
OBJSC    = transm.o
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = 
LOCDIR   = src/mat/impls/transpose/
MANSEC   = Mat

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test

