-include ../../../petscdir.mk

SOURCEC  = ts.c tscreate.c tsreg.c tsregall.c dlregists.c tseig.c tsrhssplit.c tshistory.c tsmon.c
SOURCEF  =
SOURCEH  =
DIRS     = sensitivity
LIBBASE  = libpetscts
MANSEC   = TS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
