# $Id: makefile,v 1.13 1998/06/12 21:34:44 balay Exp balay $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ts.c tsreg.c tsregall.c tsfd.c dlregis.c
SOURCEF  =
SOURCEH  = 
OBJSC    = ts.o tsreg.o tsregall.o tsfd.o dlregis.o
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = t
LOCDIR   = src/ts/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

