ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bnk.c bnls.c bntr.c bntl.c
SOURCEF  =
SOURCEH  = bnk.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/bound/impls/bnk/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

