# $Id: makefile,v 1.36 1999/01/27 19:45:44 bsmith Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vector.c map.c vnake.c
SOURCEF  =
SOURCEH  = 
OBJSC    = vector.o map.o vnake.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 1
LOCDIR   = src/vec/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

