# $Id: makefile,v 1.1 1999/01/28 22:33:30 bsmith Exp bsmith $

ALL: lib

DIRS     = src tests include
LOCDIR   = src/contrib/esi/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test


