PETSC_DIR = ../../../..

ALL: lib

CFLAGS   = $(CPPFLAGS) $(CONF) -D__DIR__='"$(LOCDIR)"'
SOURCEC  = none.c
SOURCEF  =
SOURCEH  = 
OBJSC    = none.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     =
LOCDIR   = src/pc/impls/none/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base
