# $Id: makefile,v 1.25 1998/03/19 02:06:17 balay Exp balay $ 

ALL: lib

CFLAGS   = ${CPPFLAGS} -D__SDIR__='"${LOCDIR}"'
SOURCEC  = none.c
SOURCEF  =
SOURCEH  = 
OBJSC    = none.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     =
LOCDIR   = src/pc/impls/none/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
