# $Id: makefile,v 1.30 2000/08/17 04:52:06 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = none.c
SOURCEF  =
SOURCEH  = 
OBJSC    = none.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     =
LOCDIR   = src/sles/pc/impls/none/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
