# $Id: makefile,v 1.51 2000/08/17 19:12:02 balay Exp balay $ 

LOCDIR   = src/vec/is/examples/
DIRS     = tests tutorials

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
