# $Id: makefile,v 1.49 1999/07/16 14:19:09 balay Exp bsmith $ 

LOCDIR   = src/vec/is/examples/
DIRS     = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test