#! /bin/csh
# $Id: buildtest,v 1.6 2000/10/13 16:06:11 balay Exp balay $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set TMP=/sandbox/petsc/petsc
set MACH=terra
set ARCH=linux_absoft
set TEST=testexamples_
set NICE=''
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=g
  set JOBS=(1 2 3 6 8)
else if ($day == Mon) then
  set BOPT=O_c++
  set JOBS=(1 2 3 6 8 13)
else if ($day == Tue) then
  set BOPT=O_complex
  set JOBS=(1 2 3 13)
else if ($day == Wed) then
  set BOPT=O
  set JOBS=(1 2 3 8 13)
else if ($day == Thu) then
  set BOPT=g_c++
  set JOBS=(1 2 3 6 8)
else if ($day == Fri) then
  set BOPT=g
  set JOBS=(1 2 3 6 8)
else if ($day == Sat) then
  set BOPT=O
  set JOBS=(1 2 6 8)
endif






