
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC	 = ismapgr.c
SOURCEF	 =
SOURCEH	 =
OBJSC	 = ismapgr.o 
OBJSF	 =
LIBBASE	 = libpetscdm
DIRS	 = 
MANSEC	 = SAMapping
LOCDIR	 = src/dm/ismap/impls/graph/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
