#requiresfunction 'PETSC_USE_NT_TIME'
ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = nt_time.c
SOURCEF	  =
SOURCEH	  =
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/time/nt_time/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
