
ALL: lib
#requiresdefine   'PETSC_USE_FORTRAN_KERNELS'

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF90= fcopy.F90
SOURCEH  =
LIBBASE  = libpetscsys
MANSEC   = Sys
LOCDIR   = src/sys/utils/ftn-kernels/
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


