
ALL: lib
#requirespackage   'PETSC_USE_FORTRAN_KERNELS'

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  = fcopy.F
SOURCEH  = 
OBJSC    = 
OBJSF    = fcopy.o
LIBBASE  = libpetscsys
MANSEC   = Sys
LOCDIR   = src/sys/utils/ftn-kernels/
DIRS     = bgl

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


