# $Id: makefile,v 1.4 1999/02/02 21:32:53 balay Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = snesmfj.c  snesmfjdef.c mfregis.c wp.c
SOURCEF  =
SOURCEH  = snesmfj.h
OBJSC    = snesmfj.o  snesmfjdef.o mfregis.o wp.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNESMF
DIRS     = 
LOCDIR   = src/snes/mf/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

