# $Id: makefile,v 1.1 1998/11/05 22:13:30 bsmith Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = snesmfj.c  snesmfjdef.c mfregis.c 
SOURCEF  =
SOURCEH  = snesmfj.h
OBJSC    = snesmfj.o  snesmfjdef.o mfregis.o 
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = n
DIRS     = 
LOCDIR   = src/snes/mf/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

