
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = snesmfj.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscsnes
MANSEC   = SNES
DIRS     = 
LOCDIR   = src/snes/mf/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

