# $Id: makefile,v 1.21 1999/02/01 20:38:19 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC	 = mpi.c
SOURCEF	 = 
SOURCEH	 = mpi.h mpif.h
OBJSC	 = mpi.o
OBJSF	 =
SCRIPTS  = mpirun
LIBBASE	 = libmpiuni
LOCDIR   = src/sys/src/mpiuni/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
