
ALL: lib

CPPFLAGS = 
CFLAGS   = 
FFLAGS   =
SOURCEC  = characteristic.c mocregis.c slregis.c
SOURCEF  =
SOURCEH  = 
OBJSC    = characteristic.o mocregis.o slregis.o
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = SemiLagrange
DIRS     = 
LOCDIR   = src/ts/characteristic/interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
