-include ../../../../petscdir.mk

SOURCEC   = characteristic.c mocregis.c slregis.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscts
MANSEC    = TS
SUBMANSEC = Characteristic
DIRS      =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
