-include ../../../../../../petscdir.mk

SOURCEC  = pipefgmres.c
SOURCEH  = pipefgmresimpl.h
SOURCEF  =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/gmres/pipefgmres/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


