#! /bin/csh
# $Id: buildtest,v 1.1 2000/02/20 21:41:22 bsmith Exp bsmith $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
# This handles tests for rs6000 and rs6000_gnu
#
set TMP=/tmp/petsc/petsc
set MACH=tri33
set TEST=testexamples_
set NICE=''
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set ARCH=rs6000
  set BOPT=O_c++
  set JOBS=(1 2 3 6 8 12)
else if ($day == Mon) then
  set ARCH=rs6000
  set BOPT=O
  set JOBS=(1 2 3 6 12 13)
else if ($day == Tue) then
  set ARCH=rs6000
  set BOPT=g
  set JOBS=(1 2 3 6 8 12)
else if ($day == Wed) then
  set ARCH=rs6000
  set BOPT=O_complex
  set JOBS=(1 2 3 5 10 12)
else if ($day == Thu) then
  set ARCH=rs6000_gnu
  set BOPT=O
  set JOBS=(1 2 3 6 8 13)
else if ($day == Fri) then
  set ARCH=rs6000_gnu
  set BOPT=g
  set JOBS=(1 2 3 6 8)
else if ($day == Sat) then
  set ARCH=rs6000_gnu
  set BOPT=O
  set JOBS=(1 2 3 6 13)
endif






