
#requiresfunction 'PETSC_USE_READ_REAL_TIME'

ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = rs6000_time.c
SOURCEF	  =
SOURCEH	  =
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/time/rs6000_time/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
