
ALL: lib

SOURCEC  = factor.c
SOURCEH  = 
OBJSC    = factor.o
LIBBASE  = libpetscksp
DIRS     = lu ilu icc cholesky
LOCDIR   = src/ksp/pc/impls/factor/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

