
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = factor.c factimpl.c
SOURCEH  = factor.h
OBJSC    = factor.o factimpl.o
LIBBASE  = libpetscksp
DIRS     = lu ilu icc cholesky
LOCDIR   = src/ksp/pc/impls/factor/
MANSEC   = PC

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

