#requirespackage 'PETSC_HAVE_PTHREADCLASSES'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = seqaijpthread.c
SOURCEF  =
SOURCEH  = seqaijpthread.h
OBJSC    = seqaijpthread.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/aij/seq/seqpthread/
DIRS     = 

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

