ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = iga.c igacreate.c
SOURCEF  =
SOURCEH  =
OBJSC    = iga.o igacreate.o
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMIGA
LOCDIR   = src/dm/impls/iga

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
