ITOOLSDIR = ../../../

ALL: lib

CFLAGS   = $(OPT) $(INCLUDEDIRS) -I../.. -I$(ITOOLSDIR)/pinclude\
           $(CONF)
SOURCEC  = sor.c
SOURCEF  =
WSOURCEC = 
SOURCEH  = 
OBJSC    = sor.o
WOBJS    = 
OBJSF    =
LIBBASE  = libpetscpc
LINCLUDE = $(SOURCEH)
DIRS     = 

include $(ITOOLSDIR)/bmake/$(PARCH)

