# $Id: makefile,v 1.27 1998/06/12 21:43:29 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sor.c
SOURCEF  =
SOURCEH  = 
OBJSC    = sor.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = 4
LOCDIR   = src/pc/impls/sor/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
