# $Id: makefile,v 1.12 1998/06/15 15:44:24 balay Exp $ 

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = sda
LOCDIR   = src/contrib/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

