
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = seqvscat.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vscat/impls/seq

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
