# $Id: makefile,v 1.4 1998/06/12 22:17:16 balay Exp balay $ 

ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  = -DPETSC_LDIR='"${LDIR}"' 
SOURCEC	  = ffpath.c     ftest.c      ghome.c      mpiuopen.c   rpath.c \
            fpath.c      fwd.c        grpath.c     mprint.c     sysio.c
SOURCEF	  =
SOURCEH	  = 
OBJSC	  = ffpath.o     ftest.o      ghome.o      mpiuopen.o   rpath.o \
            fpath.o      fwd.o        grpath.o     mprint.o     sysio.o
OBJSF	  =
MANSEC	  = 7
LIBBASE	  = libpetscsys
DIRS	  = 
LOCDIR	  = src/sys/src/fileio/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base




