# $Id: makefile,v 1.13 1999/01/31 16:03:29 bsmith Exp curfman $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = block.c 
SOURCEF  =
SOURCEH  = 
OBJSC    = block.o 
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 9
LOCDIR   = src/vec/is/impls/block/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

