-include ../../../../../../petscdir.mk

SOURCEC  = fgmres.c modpcf.c
SOURCEH  = fgmresimpl.h
SOURCEF  =
LIBBASE  = libpetscksp
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


