
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fgmres.c modpcf.c
SOURCEH  = fgmresimpl.h
SOURCEF  = 
OBJSC    = fgmres.o modpcf.o
OBJSF    = 
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/gmres/fgmres/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


