
ALL: lib

CFLAGS  =
FFLAGS  =
SOURCEC = mal.c   mem.c   mtr.c  mhbw.c
SOURCEF =
SOURCEH =
MANSEC  = Sys
LIBBASE = libpetscsys
DIRS    = cuda hip
LOCDIR  = src/sys/memory/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test



