
ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = mal.c   mem.c   mtr.c
SOURCEF	  =
SOURCEH	  = 
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = 
LOCDIR	  = src/sys/memory/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test



