#requiresscalar    real

ALL: lib

SOURCEH  = ../../../include/petsc/private/characteristicimpl.h ../../../include/petsccharacteristic.h
DIRS     = interface impls examples
LOCDIR   = src/ts/characteristic/
MANSEC   = SemiLagrange

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
