#requiresscalar    real

ALL: lib

SOURCEH  = ../../../include/private/characteristicimpl.h ../../../include/characteristic.h
DIRS     = interface impls examples
LOCDIR   = src/ts/characteristic/
MANSEC   = SemiLagrange

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
