
#requirespackage 'PETSC_USING_F90'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zindexf90.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    = 
LIBBASE  = libpetscvec
LOCDIR   = src/vec/is/interface/f90-custom/


include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test


