-include ../../../../petscdir.mk

SOURCEC  = matis.c
SOURCEF  =
SOURCEH  = matis.h
LIBBASE  = libpetscmat
MANSEC   = Mat
DIRS     =
LOCDIR   = src/mat/impls/is/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
