# $Id: makefile,v 1.2 2000/07/10 03:39:48 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nn.c 
SOURCEF  =
SOURCEH  = nn.h
OBJSC    = nn.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = Mat
DIRS     = 
LOCDIR   = src/mat/impls/nn/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
