ALL: lib

SOURCEH	 =
SOURCEC  =
LIBBASE	 = libpetscsys
DIRS	 = window
LOCDIR   = src/sys/classes/sf/impls/
MANSEC   = PetscSF

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

