
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/sys/examples/tests/
EXAMPLESC       = ex1.c ex2.c ex3.c ex7.c ex8.c ex9.c ex10.c ex11.c ex12.c \
                ex14.c ex15.c ex16.c ex18.c ex19.c ex20.c ex21.c \
                ex22.c ex23.c ex24.c ex27.c ex28.c ex29.c ex30.c ex31.c ex32.c
EXAMPLESF       = ex1f.F90 ex5f.F ex6f.F ex17f.F
MANSEC          = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

ex1: ex1.o chkopts
	-${CLINKER} -o ex1 ex1.o  ${PETSC_SYS_LIB}
	${RM} -f ex1.o

ex1f: ex1f.o chkopts
	-${FLINKER} -o ex1f ex1f.o  ${PETSC_SYS_LIB}
	${RM} -f ex1f.o

ex2: ex2.o chkopts
	-${CLINKER} -o ex2 ex2.o  ${PETSC_SYS_LIB}
	${RM} -f ex2.o

ex3: ex3.o chkopts
	-${CLINKER} -o ex3 ex3.o  ${PETSC_SYS_LIB}
	${RM} -f ex3.o

ex4: ex4.o chkopts
	-${CLINKER} -o ex4 ex4.o  ${PETSC_SYS_LIB}
	${RM} -f ex4.o

ex5f: ex5f.o chkopts
	-${FLINKER} -o ex5f ex5f.o  ${PETSC_SYS_LIB}
	${RM} -f ex5f.o

ex6f: ex6f.o chkopts
	-${FLINKER} -o ex6f ex6f.o  ${PETSC_SYS_LIB}
	${RM} -f ex6f.o

ex7: ex7.o chkopts
	-${CLINKER} -o ex7 ex7.o  ${PETSC_SYS_LIB}
	${RM} -f ex7.o

ex8: ex8.o chkopts
	-${CLINKER} -o ex8 ex8.o  ${PETSC_SYS_LIB}
	${RM} -f ex8.o

ex9: ex9.o chkopts
	-${CLINKER} -o ex9 ex9.o  ${PETSC_SYS_LIB}
	${RM} -f ex9.o

ex10: ex10.o chkopts
	-${CLINKER} -o ex10 ex10.o  ${PETSC_SYS_LIB}
	${RM} -f ex10.o

ex11: ex11.o chkopts
	-${CLINKER} -o ex11 ex11.o  ${PETSC_SYS_LIB}
	${RM} -f ex11.o

ex12: ex12.o chkopts
	-${CLINKER} -o ex12 ex12.o  ${PETSC_SYS_LIB}
	${RM} -f ex12.o

ex13: ex13.o chkopts
	-${CLINKER} -o ex13 ex13.o  ${PETSC_SYS_LIB}
	${RM} -f ex13.o

ex14: ex14.o chkopts
	-${CLINKER} -o ex14 ex14.o  ${PETSC_SYS_LIB}
	${RM} -f ex14.o
ex15: ex15.o chkopts
	-${CLINKER} -o ex15 ex15.o  ${PETSC_SYS_LIB}
	${RM} -f ex15.o
ex16: ex16.o chkopts
	-${CLINKER} -o ex16 ex16.o  ${PETSC_SYS_LIB}
	${RM} -f ex16.o
ex17f: ex17f.o chkopts
	-${FLINKER} -o ex17f ex17f.o  ${PETSC_SYS_LIB}
	${RM} -f ex17f.o
ex18: ex18.o chkopts
	-${CLINKER} -o ex18 ex18.o  ${PETSC_SYS_LIB}
	${RM} -f ex18.o
ex19: ex19.o chkopts
	-${CLINKER} -o ex19 ex19.o  ${PETSC_SYS_LIB}
	${RM} -f ex19.o
ex20: ex20.o chkopts
	-${CLINKER} -o ex20 ex20.o  ${PETSC_SYS_LIB}
	${RM} -f ex20.o
ex21: ex21.o chkopts
	-${CLINKER} -o ex21 ex21.o  ${PETSC_SYS_LIB}
	${RM} -f ex21.o
ex22: ex22.o chkopts
	-${CLINKER} -o ex22 ex22.o  ${PETSC_SYS_LIB}
	${RM} -f ex22.o
ex23: ex23.o chkopts
	-${CLINKER} -o ex23 ex23.o  ${PETSC_SYS_LIB}
	${RM} -f ex23.o
ex24: ex24.o chkopts
	-${CLINKER} -o ex24 ex24.o  ${PETSC_SYS_LIB}
	${RM} -f ex24.o
ex25: ex25.o chkopts
	-${CLINKER} -o ex25 ex25.o  ${PETSC_SYS_LIB}
	${RM} -f ex25.o
ex27: ex27.o chkopts
	-${CLINKER} -o ex27 ex27.o  ${PETSC_SYS_LIB}
	${RM} -f ex27.o
ex28: ex28.o chkopts
	-${CLINKER} -o ex28 ex28.o  ${PETSC_SYS_LIB}
	${RM} -f ex28.o
ex29: ex29.o chkopts
	-${CLINKER} -o ex29 ex29.o  ${PETSC_SYS_LIB}
	${RM} -f ex29.o
ex30: ex30.o chkopts
	-${CLINKER} -o ex30 ex30.o  ${PETSC_SYS_LIB}
	${RM} -f ex30.o
ex31: ex31.o chkopts
	-${CLINKER} -o ex31 ex31.o  ${PETSC_SYS_LIB}
	${RM} -f ex31.o
ex32: ex32.o chkopts
	-${CLINKER} -o ex32 ex32.o  ${PETSC_SYS_LIB}
	${RM} -f ex32.o
ex34: ex34.o chkopts
	-${CLINKER} -o ex34 ex34.o  ${PETSC_SYS_LIB}
	${RM} -f ex34.o

include ${PETSC_DIR}/lib/petsc/conf/test
