
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = wb.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
SUBMANSEC= PCExotic
LOCDIR   = src/ksp/pc/impls/wb/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
