
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = natural.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
MANSEC   = MatColoring
LOCDIR   = src/mat/color/impls/natural

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
