ALL: lib

SOURCEH	 =
SOURCEC  = sfbasic.c
LIBBASE	 = libpetscsys
DIRS	 =
LOCDIR   = src/sys/classes/sf/impls/basic/
MANSEC   = PetscSF

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

