-include ../../../../../petsckdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zpythontf.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscts
LOCDIR   = src/ts/impls/python/ftn-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
