# $Id: makefile,v 1.5 2001/08/22 18:00:54 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = feti.c 
SOURCEF  =
SOURCEH  = feti.h
OBJSC    = feti.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = Mat
DIRS     = 
LOCDIR   = src/mat/impls/feti/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
