-include ../../../../petscdir.mk
#requiresdefine  'PETSC_HAVE_MATLAB'

CFLAGS    = ${MATLAB_INCLUDE}
MANSEC	  = Sys
LIBBASE	  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc


