# $Id: makefile,v 1.2 1999/11/10 03:20:57 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fgmres.c modpcf.c
SOURCEH  = fgmresp.h
SOURCEF  = 
OBJSC    = fgmres.o modpcf.o
OBJSF    = 
LIBBASE  = libpetscsles
MANSEC   = KSP
LOCDIR   = src/sles/ksp/impls/fgmres/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base


