ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gpcg.c
SOURCEF  = 
SOURCEH  = gpcg.h
OBJSC    = gpcg.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/bound/impls/gpcg/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

