ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gpcg.c
SOURCEF  =
SOURCEH  = gpcg.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/bound/impls/gpcg/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

