-include ../../../../../petscdir.mk

SOURCEH	  =
SOURCEC   = section.c sectionhdf5.c
LIBBASE	  = libpetscvec
DIRS	    =
MANSEC    = Vec
SUBMANSEC = PetscSection

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
