ALL: lib

SOURCEH	  =
SOURCEC   = section.c sectionhdf5.c
LIBBASE	  = libpetscvec
DIRS	    =
LOCDIR    = src/vec/is/section/interface/
MANSEC    = Vec
SUBMANSEC = PetscSection

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
