-include ../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = pythonpc.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscksp
DIRS      =
LOCDIR    = src/ksp/pc/impls/python/
MANSEC    = KSP
SUBMANSEC = PC

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
