
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = pythonP.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscksp
DIRS     =
LOCDIR   = src/ksp/pc/impls/python/
MANSEC   = PC

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
