-include ../../../../../petscdir.mk

MANSEC	  = Sys
SUBMANSEC = Profiling
LIBBASE	  = libpetscsys
DIRS	  = default nested trace mpe perfstubs legacy

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

