#! /bin/csh
# $Id: buildconfigtest,v 1.2 2001/02/09 00:24:53 balay Exp balay $ 
#
# Defines the configuration for maint/buildconfigtest, this is sourced by that script

set TMP=/sandbox/petsc/petsc
set MACH=abacus
set ARCH=linux
set TEST=testexamples_


set WITH_BLAS='--with-blas=/home/petsc/software/blaslapack/blas_INTEL_linux.a'
set WITH_LAPACK='--with-lapack=/home/petsc/software/blaslapack/lapack_linux.a'
set WITH_MPI='--with-mpi=/home/petsc/software/mpich-1.2.0/linux/lib/libmpich.a'
set WITH_CC='--with-cc=gcc'
set WITH_FC='--with-fc=g77'
set WITH_CXX='--with-cxx=g++'

