#! /bin/csh
# $Id: buildconfigtest,v 1.1 2001/02/08 23:56:02 balay Exp balay $ 
#
# Defines the configuration for maint/buildconfigtest, this is sourced by that script

set TMP=/sandbox/petsc/petsc
set MACH=abacus
set ARCH=linux
set TEST=testexamples_


set WITH_BLAS='--with-blas=/home/petsc/software/blaslapack/blas_INTEL_linux.a'
set WITH_LAPACK='--with-lapack=/home/petsc/software/blaslapack/lapack_linux.a'
set WITH_MPI='--with-mpi=/home/petsc/software/mpich-1.2.0/linux'
