#! /bin/csh
# $Id: buildtest,v 1.1 2000/02/19 16:46:20 bsmith Exp bsmith $ 
#
# Defines the configuration for maint/buildtest on solaris systems
#
set TMP=/sandbox/balay/petsc
set MACH=fire
set ARCH=solaris
set TEST=testexamples_
set NICE=''
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=O_complex
  set JOBS=(1 2 3 5 10 13 15 16)        
elseif ($day == Mon) then
  set BOPT=O_c++    
  set JOBS=(1 2 8 13 15 16)        
elseif ($day == Tue) then
  set BOPT=g        
  set JOBS=(1 2 3 6 7 13 14 16)        
elseif ($day == Wed) then
  set BOPT=g_c++ 
  set JOBS=(1 2 3 6 8 14 15 16)       
elseif ($day == Thu) then
  set BOPT=g_complex
  set JOBS=(1 2 3 5 10 13 15 16)       
elseif ($day == Fri) then
  set BOPT=O_c++    
  set JOBS=(1 2 3 6 8 14 15 16)        
elseif ($day == Sat) then
  set BOPT=O        
  set JOBS=(1 2 3 6 7 8 14 15)        
endif

source /home/bsmith/petsc/maint/newbuildtest





