
CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = petscimpl.h petscfptimpl.h petscfvimpl.h
LIBBASE  = libpetscvec
DIRS     =
LOCDIR   = include/petsc/private/
MANSEC   = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
