
SOURCEC   = tikz.c
SOURCEF   =
SOURCEH   =
MANSEC    = Sys
SUBMANSEC = Draw
LIBBASE   = libpetscsys
DIRS      =
LOCDIR    = src/sys/classes/draw/impls/tikz/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
