-include ../../../../../petscdir.mk

SOURCEC  = tsirm.c
SOURCEH  =
SOURCEF  =
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
