-include ../../../../../petscdir.mk

LOCDIR          = src/dm/impls/patch/tests/
EXAMPLESC       = ex1.c
EXAMPLESF       =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
