-include ../../../../petsckdir.mk

DIRS     = bqpip gpcg
LOCDIR   = src/tao/quadratic/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

