-include ../../../../../../petscdir.mk
#requiresdefine  'PETSC_USE_SOCKET_VIEWER'

MANSEC    = Sys
SUBMANSEC = Viewer

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk


