-include ../../../../../../petscdir.mk
#requiresdefine  'PETSC_USE_SOCKET_VIEWER'

SOURCEC   = send.c
SOURCEH   = socket.h
MANSEC    = Sys
SUBMANSEC = Viewer
LIBBASE   = libpetscsys
DIRS      = matlab

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


