# $Id: makefile,v 1.8 1999/02/02 21:27:13 balay Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mpicsr.c
SOURCEF  =
SOURCEH  = mpicsr.h
OBJSC    = mpicsr.o
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
LOCDIR   = src/mat/impls/csr/mpi/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
