-include ../../../../../petscdir.mk
# This directory contains access to matlab test problems for the derivative free
# least squares solvers.

LOCDIR           = src/tao/leastsquares/tutorials/matlab/
MANSEC           = Tao
EXAMPLESMATLAB   = TestingInitialize.m TestingFinalize.m ProblemInitialize.m ProblemFinalize.m
DIRS             =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

