-include ../../../../../petscdir.mk
# This directory contains access to MATLAB test problems for the derivative free
# least squares solvers.

EXAMPLESMATLAB   = TestingInitialize.m TestingFinalize.m ProblemInitialize.m ProblemFinalize.m

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

