-include ../../../petscdir.mk

SOURCEH  = ../../../include/petsc/private/vecimpl.h ../../../include/petscvec.h ../../../include/petsc/private/kernels/petscaxpy.h ../../../include/petscviennacl.h ../../../include/petscvec_kokkos.hpp
DIRS     = utils interface impls tests tutorials
LOCDIR   = src/vec/vec/
MANSEC   = Vec

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

