
ALL: lib

SOURCEH  = ../../../include/petsc/private/vecimpl.h ../../../include/petscvec.h \
           ../../../include/petsc/private/kernels/petscaxpy.h ../../../include/petsccusp.h \
           ../../../include/petscviennacl.h
DIRS     = utils interface impls examples
LOCDIR   = src/vec/vec/
MANSEC   = Vec

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

