-include ../../../../../petscdir.mk

CFLAGS	         =
FFLAGS	         =
CPPFLAGS         =
FPPFLAGS         =
LOCDIR           = src/vec/is/sf/tutorials/
EXAMPLESC        = ex1.c ex2.c
EXAMPLESF        = ex1f.F90

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
