# $Id: makefile,v 1.25 1999/01/31 16:08:21 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = eisen.c
SOURCEF  =
SOURCEH  = 
OBJSC    = eisen.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/eisen/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
