# $Id: makefile,v 1.26 1999/02/02 21:28:07 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = eisen.c
SOURCEF  =
SOURCEH  = 
OBJSC    = eisen.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/eisens/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
