-include ../../../../../../petscdir.mk
ALL: lib1

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC   = icc.c
SOURCEF   =
SOURCEH   = icc.h
LIBBASE   = libpetscksp
DIRS      =
MANSEC    = KSP
SUBMANSEC = PC
LOCDIR    = src/ksp/pc/impls/factor/icc/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
