# $Id: makefile,v 1.32 2000/08/17 04:52:29 bsmith Exp balay $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = preonly.c
SOURCEF  =
OBJSC    = preonly.o
OBJSF    =
LIBBASE  = libpetscsles
LOCDIR   = src/sles/ksp/impls/preonly/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
