
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pipefcg.c
SOURCEF  =
SOURCEH  = pipefcgimpl.h
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/fcg/pipefcg/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
