#requirespackage 'PETSC_HAVE_CUDA'

SOURCEH       =
SOURCEC       =
SOURCECU      = sfcuda.cu
LIBBASE       = libpetscvec
DIRS          =
LOCDIR        = src/vec/is/sf/impls/basic/cuda
MANSEC        = Vec
SUBMANSEC     = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

