
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vpscat_mpi1.c
SOURCEF  =
SOURCEH  = vpscat_mpi1.h
DIRS     =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vscat/impls/mpi1/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
