
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC	 = iscomp.c iscoloring.c isltog.c isdiff.c isblock.c
SOURCEF	 =
SOURCEH	 =
LIBBASE	 = libpetscvec
DIRS	 = 
MANSEC	 = IS
LOCDIR	 = src/vec/is/utils/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
