# $Id: makefile,v 1.17 1999/02/01 21:45:00 curfman Exp balay $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC	 = iscomp.c iscoloring.c isltog.c isdiff.c
SOURCEF	 =
SOURCEH	 =
OBJSC	 = iscomp.o iscoloring.o isltog.o isdiff.o
OBJSF	 =
LIBBASE	 = libpetscvec
DIRS	 = 
MANSEC	 = IS
LOCDIR	 = src/is/utils/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
