-include ../../../../../../petsckdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zvsectionisf90.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscvec
LOCDIR   = src/vec/is/section/interface/f90-custom/


include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
