# $Id: makefile,v 1.29 1999/02/03 16:11:50 balay Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS = 
SOURCEC  = icc.c
SOURCEF  =
SOURCEH  = icc.h
OBJSC    = icc.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/icc/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
