#requirespackage 'PETSC_HAVE_MPI_WIN_CREATE'
#requirespackage 'PETSC_HAVE_MPI_TYPE_DUP'

ALL: lib

SOURCEH	 =
SOURCEC  = sfwindow.c
LIBBASE	 = libpetscsys
DIRS	 =
LOCDIR   = src/sys/classes/sf/impls/window/
MANSEC   = PetscSF

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

