#
ALL: lib

DIRS   = chaco party pmetis scotch hierarchpart
LOCDIR = src/mat/partition/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


