# $Id: makefile,v 1.4 2001/08/22 18:01:11 balay Exp $ 
#
ALL: lib

DIRS   = chaco jostle party pmetis scotch
LOCDIR = src/mat/partition/impls/
 
include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

