# $Id: makefile,v 1.3 2000/08/17 04:51:57 bsmith Exp balay $ 
#
ALL: lib

DIRS   = pmetis
LOCDIR = src/mat/partition/impls
 
include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

