# $Id: makefile,v 1.11 2001/08/22 18:01:31 balay Exp $ 

#requirespackage   'PETSC_HAVE_SPAI'
#requiresprecision double

ALL: lib

CFLAGS   = 
FFLAGS   = 
SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = src examples
LOCDIR   = src/sles/pc/impls/spai/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
