# $Id: makefile,v 1.4 1999/04/07 02:45:45 bsmith Exp bsmith $ 

#requirespackage '-DPETSC_HAVE_SPAI'
#requireslanguage CONLY

ALL: lib

CFLAGS   = 
FFLAGS   = 
SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = src
LOCDIR   = src/contrib/pc/spai/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
