# $Id: makefile,v 1.9 2001/06/21 21:17:55 bsmith Exp bsmith $ 

#requirespackage   'PETSC_HAVE_SPAI'
#requireslanguage  CONLY
#requiresprecision double

ALL: lib

CFLAGS   = 
FFLAGS   = 
SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = src examples
LOCDIR   = src/sles/pc/impls/spai/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
