# $Id: makefile,v 1.5 2001/08/31 15:38:10 knepley Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lgmres.c
SOURCEF  = 
SOURCEH  = lgmres.h lgmresp.h
OBJSC    = lgmres.o
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = KSP
LOCDIR   = src/sles/ksp/impls/lgmres/
DIRS     =

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
