#requiresdefine 'PETSC_HAVE_MPI_WIN_CREATE'

SOURCEH	  =
SOURCEC   = sfwindow.c
LIBBASE	  = libpetscvec
DIRS	  =
LOCDIR    = src/vec/is/sf/impls/window/
MANSEC    = Vec
SUBMANSEC = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

