#requirespackage  'PETSC_HAVE_CTETGEN'

CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = ctetgenerate.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPLEX
LOCDIR   = src/dm/impls/plex/generators/ctetgen/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
