ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vtkv.c
SOURCEF  =
SOURCEH  = vtkvimpl.h
MANSEC   = Viewer
LIBBASE  = libpetscsys
DIRS     =
LOCDIR   = src/sys/classes/viewer/impls/vtk/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
