
ALL: lib

SOURCEH   = ../../../../include/petscdt.h ../../../../include/petscfe.h ../../../../include/petscfetypes.h
DIRS      = interface impls
LOCDIR    = src/dm/dt/fe/
MANSEC    = DM
SUBMANSEC = FE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
