-include ../../../../../../petscdir.mk

SOURCEC  = tagger.c taggerregi.c dlregistagger.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/utils/tagger/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
