# $Id: makefile,v 1.53 2000/08/23 21:04:08 bsmith Exp $ 

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = f90_IRIX.h f90_nag.h f90_solaris_old.h f90_alpha.h f90_rs6000.h f90_t3e.h \
	   f90_hpux.h f90_solaris.h f90_win32.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = 
LOCDIR   = include/f90impl
MANSEC   = Sys

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
