# $Id: makefile,v 1.15 2001/08/22 18:02:42 balay Exp $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fdda.c pack.c dm.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = fdda.o pack.o dm.o
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = DA
LOCDIR   = src/dm/da/utils/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
