# $Id: makefile,v 1.9 1999/01/26 02:30:39 bsmith Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fdda.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = fdda.o
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = 6
LOCDIR   = src/dm/da/utils/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
