
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = none.c
SOURCEF  =
SOURCEH  = 
OBJSC    = none.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     =
LOCDIR   = src/ksp/pc/impls/none/
MANSEC   = PC

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
