# $Id: makefile,v 1.31 2001/08/22 18:01:21 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = none.c
SOURCEF  =
SOURCEH  = 
OBJSC    = none.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     =
LOCDIR   = src/ksp/pc/impls/none/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
