-include ../../../../../petscdir.mk

SOURCEC  = ibcgs.c
SOURCEF  =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/ibcgs/
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
