
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = ibcgs.c
SOURCEF  =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/ibcgs/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
