-include ../../../../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = partitioner.c partitionerreg.c
SOURCEF  =
SOURCEH  =
LOCDIR   = src/dm/partitioner/interface/
LIBBASE  = libpetscdm
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
