ALL: lib

SOURCEH	  =
SOURCEC   =
LIBBASE	  = libpetscvec
DIRS	  = window basic
LOCDIR    = src/vec/is/sf/impls/
MANSEC    = Vec
SUBMANSEC = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

