ALL: lib

SOURCEH	 =
SOURCEC  =
LIBBASE	 = libpetscsys
DIRS	 = window basic
LOCDIR   = src/vec/is/sf/impls/
MANSEC   = PetscSF

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

