-include ../../../petsckdir.mk

SOURCEH   = pfimpl.h ../../../include/petscpf.h
DIRS      = interface impls
LOCDIR    = src/vec/pf/
MANSEC    = Vec
SUBMANSEC = PF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
