
ALL: lib

SOURCEH  = pfimpl.h ../../../include/petscpf.h
DIRS     = interface impls examples
LOCDIR   = src/vec/pf/
MANSEC   = PF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
