-include ../../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC   = ilu.c
SOURCEF   =
SOURCEH   = ilu.h
LIBBASE   = libpetscksp
DIRS      =
MANSEC    = KSP
SUBMANSEC = PC
LOCDIR    = src/ksp/pc/impls/factor/ilu/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
