
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = blockmat.c
SOURCEF  =
SOURCEH  = 
OBJSC    = blockmat.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/blockmat/seq

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
