ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fas.c fasgalerkin.c fasfunc.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES
SUBMANSEC= SNESFAS
LOCDIR   = src/snes/impls/fas/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
