ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fas.c fasgalerkin.c
SOURCEF  =
SOURCEH  =
OBJSC    = fas.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/fas/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
