-include ../../../../petscdir.mk

LIBBASE  = libpetscsnes
MANSEC   = SNES
SUBMANSEC= SNESFAS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
