
ALL: lib

SOURCEH  = ../../../include/private/daimpl.h ../../../include/petscda.h
DIRS     = src  examples utils
LOCDIR   = src/dm/da/
MANSEC   = DA

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test

