# $Id: makefile,v 1.21 1999/01/31 16:11:26 bsmith Exp bsmith $ 

ALL: lib

SOURCEH  = daimpl.h
DIRS     = src  examples utils
LOCDIR   = src/dm/da/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test

