# $Id: makefile,v 1.17 1998/04/23 23:25:50 balay Exp balay $ 

ALL: lib

SOURCEC  =
SOURCEF  =
SOURCEH  = daimpl.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = src  examples utils
LOCDIR   = src/da/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

