-include ../../../../../petscdir.mk

SOURCEC   = devicereg.c memory.c
MANSEC	  = Sys
LIBBASE	  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

