
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = pythonK.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscksp
DIRS     =
LOCDIR   = src/ksp/ksp/impls/python/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
