#requiresdefine 'PETSC_USING_F2003'

ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  = 
DIRS     = fsrc
LIBBASE  = libpetscsys
MANSEC   = Sys
LOCDIR   = src/sys/bag/f2003-src/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
