-include ../../../power_../stability_../petsckdir.mk

LOCDIR          = src/ts/tutorials/power_grid/stability_9bus/
MANSEC          = TS
DIRS            =
CLEANFILES      = TS-data-*

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
