
ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  = 
SOURCEC	  = adebug.c err.c errtrace.c errabort.c errstop.c fp.c signal.c pstack.c
SOURCEF	  =
SOURCEH	  = ../../../include/petscerror.h 
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = examples
LOCDIR	  = src/sys/error/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test



