-include ../../../petscdir.mk
#requirespackage 'PETSC_HAVE_SAWS'

SOURCEH   =
SOURCEC   = pams.c
DIRS      = 
LOCDIR    = src/sys/ams/
MANSEC    = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
