
#requirespackage 'PETSC_HAVE_SAWS'

ALL: lib
SOURCEH   =
SOURCEC   = pams.c
DIRS      = java
LOCDIR    = src/sys/ams/
MANSEC    = Sys

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
