
#requirespackage 'PETSC_HAVE_AMS'

ALL: lib 
SOURCEH   = 
SOURCEC   = pams.c
OBJSC     = pams.o
DIRS      = java
LOCDIR    = src/sys/ams/
MANSEC    = Sys

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
