# $Id: makefile,v 1.20 2001/03/26 18:44:56 bsmith Exp balay $ 

ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = plog.c plogmpe.c ploginfo.c mpitr.c
SOURCEF	  =
SOURCEH	  = ptime.h ../../../../include/petsclog.h
OBJSC	  = plog.o plogmpe.o ploginfo.o mpitr.o
OBJSF	  =
MANSEC	  = Profiling
LIBBASE	  = libpetsc
DIRS	  = 
LOCDIR	  = src/sys/src/plog/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
