# $Id: makefile,v 1.35 1998/06/15 15:56:42 balay Exp bsmith $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = rich.c richscale.c
SOURCEF  =
SOURCEH  = richctx.h
OBJSC    = rich.o richscale.o
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = 5
LOCDIR   = src/sles/ksp/impls/rich/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
