
ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC	  = bag.c
SOURCEF	  =
SOURCEH	  = 
OBJSC	  = bag.o
OBJSF	  =
MANSEC	  = Sys
LIBBASE	  = libpetsc
DIRS	  = 
LOCDIR	  = src/sys/src/bag/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

