-include ../../../../../petsckdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zsnesshellf.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscsnes
LOCDIR   = src/snes/impls/shell/ftn-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
