
ALL: lib 

DIRS	  = viewer draw error dll fileio memory objects time utils plog mpiuni matlabengine f90 adic bag
LOCDIR	  = src/sys/src/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

