-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_CUDA'

SOURCEC  = curand.c
SOURCECU = curand2.cu
LIBBASE  = libpetscsys
MANSEC	 = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
