# $Id: makefile,v 1.5 2000/08/17 04:53:36 bsmith Exp balay $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = 
OBJSC    =  
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = constant string matlab
LOCDIR   = src/pf/impls/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

