# $Id: makefile,v 1.1 2000/02/01 19:33:26 bsmith Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = 
OBJSC    =  
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = constant
LOCDIR   = src/pf/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

