# $Id: makefile,v 1.29 1998/06/15 15:54:47 balay Exp $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = dvecimpl.h
OBJSC    =  
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = seq mpi shared
LOCDIR   = src/vec/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

