
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lmvmmat.c 
SOURCEF  = 
SOURCEH  = lmvmmat.h 
OBJSC    = lmvmmat.o 
OBJSF    = 
LIBBASE  = libtao
MANSEC   = matrix
LOCDIR   = src/matrix/

include ${TAO_DIR}/conf/tao_base


