
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lmvmmat.c adamat.c submatfree.c approxmat.c
SOURCEF  = 
SOURCEH  = lmvmmat.h adamat.h submatfree.h approxmat.h
OBJSC    = approxmat.o lmvmmat.o adamat.o submatfree.o 
OBJSF    = 
LIBBASE  = libtao
MANSEC   = util
LOCDIR   = src/matrix/

include ${TAO_DIR}/conf/tao_base


