#requiresscalar real

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = dgmres.c
SOURCEF  = 
SOURCEH  = dgmresimpl.h
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/gmres/dgmres/
DIRS     =

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
