-include ../../../../../../petscdir.mk
#requiresscalar real

SOURCEC  = dgmres.c
SOURCEF  =
SOURCEH  = dgmresimpl.h
LIBBASE  = libpetscksp
MANSEC   = KSP
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
