-include ../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = crl.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
DIRS     = ftn-kernels
MANSEC   = Mat
LOCDIR   = src/mat/impls/aij/seq/crl/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
