# $Id: makefile,v 1.31 2001/08/22 18:01:29 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS = 
SOURCEC  = icc.c
SOURCEF  =
SOURCEH  = icc.h
OBJSC    = icc.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/icc/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
