ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = mcrl.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = mcrl.o
OBJSF    = 
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
LOCDIR   = src/mat/impls/aij/mpi/crl/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
