# $Id: makefile,v 1.22 2001/08/22 17:58:56 balay Exp $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = stringv.c
SOURCEF  =
SOURCEH  =
OBJSC    = stringv.o
OBJSF    =
MANSEC   = Viewer
LIBBASE  = libpetsc
DIRS     = 
LOCDIR   = src/sys/src/viewer/impls/string/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
