# $Id: makefile,v 1.16 1999/01/31 16:04:43 bsmith Exp balay $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = stringv.c
SOURCEF  =
SOURCEH  =
OBJSC    = stringv.o
OBJSF    =
MANSEC   = Viewer
LIBBASE  = libpetsc
DIRS     = 
LOCDIR   = src/sys/src/viewer/impls/string/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
