
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = miscoloring.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
MANSEC   = MatColoring
LOCDIR   = src/mat/color/impls/mis

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
