# $Id: makefile,v 1.8 1998/04/23 23:47:32 balay Exp balay $ 

ALL:

SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        = 
LIBBASE	        = libpetscsnes
LOCDIR          = src/snes/examples/
DIRS            = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
