#PETSC_DIR = ../../..
ALL:

CFLAGS	        = $(CPPFLAGS) $(CONF) -D__SDIR__='"$(LOCDIR)"'
FFLAGS	        = 
SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        = 
LIBBASE	        = libpetscsnes
LOCDIR          = src/snes/examples/
DIRS            = tests tutorials

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base
