-include ../../../../../petscdir.mk

SOURCEC   = bddc.c bddcprivate.c bddcgraph.c bddcscalingbasic.c bddcnullspace.c bddcfetidp.c bddcschurs.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscksp
DIRS      =
MANSEC    = KSP
SUBMANSEC = PC
LOCDIR    = src/ksp/pc/impls/bddc/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
