# $Id: makefile,v 1.14 1999/02/03 16:12:17 balay Exp bsmith $ 

ALL: lib

MANSEC   = TS
LOCDIR   = src/ts/impls/explicit/
DIRS     = euler

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test

