# $Id: makefile,v 1.4 2001/08/22 18:01:52 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = damg.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = damg.o 
OBJSF    =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/utils/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
