
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = tfqmr.c
SOURCEF  =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/tfqmr/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
