# $Id: makefile,v 1.8 2001/08/22 17:59:28 balay Exp $ 

ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  = 
SOURCEC	  = pams.c aoptions.c
SOURCEF	  =
SOURCEH	  = 
OBJSC	  = pams.o aoptions.o
OBJSF	  =
MANSEC	  = Sys
LIBBASE	  = libpetsc
DIRS	  = 
LOCDIR	  = src/sys/src/objects/ams/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

