# $Id: makefile,v 1.1 2000/01/06 20:33:02 bsmith Exp bsmith $ 

#requirespackage  '-DPETSC_HAVE_AMS'

ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  = 
SOURCEC	  = pams.c aoptions.c
SOURCEF	  =
SOURCEH	  = 
OBJSC	  = pams.o aoptions.o
OBJSF	  =
MANSEC	  = Sys
LIBBASE	  = libpetsc
DIRS	  = 
LOCDIR	  = src/sys/src/objects/ams/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base


