
CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = petscimpl.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = 
LOCDIR   = include/private/
MANSEC   = Sys

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
