
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = unit.c
SOURCEF  = 
SOURCEH  =
OBJSC    = unit.o
OBJSF    = 
LIBBASE  = libtaolinesearch
MANSEC   = Line Search
LOCDIR   = src/linesearch/impls/unit/

include ${TAO_DIR}/conf/tao_base

