-include ../../../../petscdir.mk

SOURCEH   = ../../../../include/petscfv.h ../../../../include/petscfvtypes.h
DIRS      = interface
MANSEC    = DM
SUBMANSEC = FV

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
