-include ../../../../petsckdir.mk
#requirespackage 'PETSC_HAVE_HIP'

SOURCEC  =
SOURCEHIP = mhiphost.hip.cpp
SOURCEF  =
SOURCEH  =
MANSEC   = Sys
LIBBASE  = libpetscsys
DIRS     =
LOCDIR   = src/sys/memory/hip

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
