-include ../../../../../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dmfieldds.c
SOURCEF  =
LIBBASE  = libpetscdm
DIRS     = 
LOCDIR   = src/dm/field/impls/ds/
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
