-include ../../../../../petscdir.mk

SOURCEC  = dmfieldds.c
SOURCEF  =
LIBBASE  = libpetscdm
DIRS     =
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
