
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fe.c fegeom.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscdm
MANSEC   = DM
LOCDIR   = src/dm/dt/fe/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
