-include ../../../../../petscdir.mk

SOURCEC   = fe.c fegeom.c feceed.c
SOURCEF   =
SOURCEH   =
DIRS      =
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = FE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
