# $Id: makefile,v 1.2 2000/02/02 21:21:16 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pf.c pfall.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pf.o pfall.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/pf/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
