# $Id: makefile,v 1.5 2001/03/22 20:33:15 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pf.c pfall.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pf.o pfall.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = PF
LOCDIR   = src/pf/interface/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
