
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = inode.c inode2.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = inode.o inode2.o
OBJSF    = 
LIBBASE  = libpetscmat
DIRS     = Mat
LOCDIR   = src/mat/impls/csr/inode/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
