-include ../../petscdir.mk

DIRS     = impls f90-mod interface tests tutorials dt label field partitioner
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
