-include ../../../../../petscdir.mk

CPPFLAGS  = ${CHACO_INCLUDE}
SOURCEC   = partchaco.c
SOURCEH   =
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
