
#requirespackage  'PETSC_HAVE_MATLAB'
#requiresscalar real 

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = cmatlab.c
SOURCEF  =
SOURCEH  = 
OBJSC    = cmatlab.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/pf/impls/matlab/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


