# $Id: makefile,v 1.1 2000/05/18 17:24:55 bsmith Exp bsmith $ 

#requirespackage  '-DPETSC_HAVE_MATLAB'
#requiresscalar real 

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = cmatlab.c
SOURCEF  =
SOURCEH  = 
OBJSC    = cmatlab.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/pf/impls/matlab/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base


