# $Id: makefile,v 1.4 2000/10/24 20:27:56 bsmith Exp bsmith $ 

#requirespackage  'PETSC_HAVE_MATLAB_ENGINE'
#requiresscalar real 

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = cmatlab.c
SOURCEF  =
SOURCEH  = 
OBJSC    = cmatlab.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/pf/impls/matlab/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test


