-include ../../../../../petsckdir.mk

SOURCEC  = brgn.c
SOURCEF  =
SOURCEH  = brgn.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/leastsquares/impls/brgn/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

