# $Id: makefile,v 1.3 2000/08/17 04:51:56 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fdmatrix.c
SOURCEF  =
SOURCEH  = 
OBJSC    = fdmatrix.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = MatFD
LOCDIR   = src/mat/matfd/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
