-include ../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = fdmatrix.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscmat
SUBMANSEC = MatFD
MANSEC    = Mat
LOCDIR    = src/mat/matfd/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
