# $Id: makefile,v 1.2 1999/03/17 23:23:40 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fdmatrix.c
SOURCEF  =
SOURCEH  = 
OBJSC    = fdmatrix.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = MatFD
LOCDIR   = src/mat/matfd/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
