
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = adaptcfl.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/adapt/impls/cfl/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

