
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = zksp.c zpc.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = zksp.o zpc.o
OBJSF    = 
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/custom/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


