
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sieuler.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/impls/symplectic/sieuler/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

