
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vecpthread.c
SOURCEF  =
SOURCEH  = 
OBJSC    = vecpthread.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/impls/seq/seqpthread/
DIRS     = 

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

