-include ../../../../petscdir.mk

DIRS   = mis hem
LOCDIR = src/mat/coarsen/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

