-include ../../../petscdir.mk

SOURCEC	  =  ftest.c ghome.c mpiuopen.c rpath.c fpath.c fwd.c grpath.c mprint.c sysio.c fretrieve.c smatlab.c fdir.c
SOURCEF	  =
SOURCEH	  = mprint.h
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/fileio/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test



