#requirespackage  'PETSC_HAVE_DXML'
#requireslanguage CONLY

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = dxml.c
SOURCEF  = 
SOURCEH  =
OBJSC    = dxml.o
OBJSF    = 
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
LOCDIR   = src/mat/impls/aij/seq/dxml/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
