# $Id: makefile,v 1.26 1999/03/17 23:22:41 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = matimpl.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = interface impls examples utils matfd partition order color
LOCDIR   = src/mat/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
