# $Id: makefile,v 1.14 1997/09/10 18:48:28 balay Exp balay $ 

ALL: lib

CFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = seq mpi
LOCDIR   = src/mat/impls/bdiag/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
