#PETSC_DIR = ../../../..

ALL: lib

CFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = seq mpi
LOCDIR   = src/mat/impls/bdiag/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base
