# $Id: makefile,v 1.19 2000/08/17 04:51:32 bsmith Exp balay $ 

ALL: lib

DIRS     = seq mpi
LOCDIR   = src/mat/impls/bdiag/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
