-include ../../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_HDF5'

CFLAGS    = ${HDF5_INCLUDE}
MANSEC    = Sys
SUBMANSEC = Viewer
LIBBASE   = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
