-include ../../pde_../../../petscdir.mk

SOURCEC  = lcl.c
SOURCEF  =
SOURCEH  = lcl.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/pde_constrained/impls/lcl/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

