ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lcl.c
SOURCEF  = 
SOURCEH  = lcl.h
OBJSC    = lcl.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/pde_constrained/impls/lcl/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

