
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = owarmijo.c
SOURCEF  = 
SOURCEH  = owarmijo.h
OBJSC    = owarmijo.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/linesearch/impls/owarmijo/

include ${TAO_DIR}/conf/tao_base

