ALL: lib 

ITOOLSDIR = ../../..

CFLAGS   = $(OPT) -I$(ITOOLSDIR) -I$(ITOOLSDIR)/include -I../..
FFLAGS   =
SOURCEC  = cr.c 
SOURCEF  = 
WSOURCEC = 
OBJSC    = cr.o 
WOBJS    =  
OBJSF    =
LIBBASE  = libpetscksp
LOCAL_INCLUDE = 

