ALL: lib 

ITOOLSDIR = ../../..

CFLAGS   = $(OPT) $(CONF) -I$(ITOOLSDIR) -I$(ITOOLSDIR)/include \
           -I$(ITOOLSDIR)/pinclude -I../..
FFLAGS   =
SOURCEC  = cr.c 
SOURCEF  = 
WSOURCEC = 
OBJSC    = cr.o 
WOBJS    =  
OBJSF    =
LIBBASE  = libpetscksp
LINCLUDE = 

include $(ITOOLSDIR)/bmake/$(PARCH)

