# $Id: makefile,v 1.4 1998/06/15 15:44:15 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = 
DIRS     = blas lapack
LOCDIR   = src/blaslapack

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

