-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_MPE'

MANSEC    = Sys
SUBMANSEC = Log

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk

