# $Id: makefile,v 1.35 1998/07/23 22:46:02 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   = ${AMS_INCLUDE}
FFLAGS   =
SOURCEC  = bvec2.c bvec1.c dvec2.c vseqcr.c
SOURCEF  =
SOURCEH  = 
OBJSC    = bvec2.o  bvec1.o dvec2.o vseqcr.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 1
LOCDIR   = src/vec/impls/seq/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

