ITOOLSDIR = ../../../../

ALL: lib

CFLAGS   = $(OPT) -I$(ITOOLSDIR)/include -I.. -I../../.. -I$(ITOOLSDIR) $(COPT)
SOURCEC  = dvec3.c bvec2.c 
SOURCEF  =
WSOURCEC = 
SOURCEH  = 
OBJSC    = dvec3.o bvec2.o 
WOBJS    = 
OBJSF    =
LIBBASE  = libpetscvec
SYSLIB   = $(LDIR)/system.a $(BLAS) $(SLIB) -lm 
LOCAL_INCLUDE = $(SOURCEH)

