# $Id: makefile,v 1.8 1998/04/23 23:25:35 balay Exp balay $ 

ALL: lib

SOURCEC	 =
SOURCEF	 =
SOURCEH	 = aoimpl.h
OBJSC	 =
OBJSF	 =
LIBBASE	 = libpetscvec
DIRS	 = interface impls  examples utils
LOCDIR   = src/is/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

