PETSC_DIR = ../..

ALL: lib

CFLAGS	 = 
SOURCEC	 =
SOURCEF	 =
SOURCEH	 = aoimpl.h
OBJSC	 =
OBJSF	 =
LIBBASE	 = libpetscvec
DIRS	 = interface impls  examples 
LOCDIR   = src/is/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base

