ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sqpcon.c
SOURCEF  = 
SOURCEH  = sqpcon.h
OBJSC    = sqpcon.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = taosolver
LOCDIR   = src/pde_constrained/impls/sqpcon/

include ${TAO_DIR}/conf/tao_base

