-include ../../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = dspacelagrange.c
SOURCEF   =
LIBBASE   = libpetscdm
DIRS      = tests tutorials
LOCDIR    = src/dm/dt/dualspace/impls/lagrange/
MANSEC    = DM
SUBMANSEC = DUALSPACE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
