-include ../../../../../../petscdir.mk

SOURCEC   = dspacelagrange.c
SOURCEF   =
LIBBASE   = libpetscdm
DIRS      = tests tutorials
MANSEC    = DM
SUBMANSEC = DUALSPACE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
