ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pounder.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = pounder.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = taosolver
LOCDIR   = src/unconstrained/impls/pounder/

include ${TAO_DIR}/conf/tao_base

