

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lmvm.c
SOURCEF  =
SOURCEH  = lmvm.h
LIBBASE  = libpetscksp
MANSEC   = KSP
DIRS     = ldfp lbfgs lsr1 lbrdn lmbrdn lsbrdn
LOCDIR   = src/ksp/ksp/utils/lmvm/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
