-include ../../../../../petscdir.mk

SOURCEC  = lmvmimpl.c lmvmutils.c
SOURCEF  =
SOURCEH  = lmvm.h
LIBBASE  = libpetscksp
MANSEC   = KSP
DIRS     = sr1 dfp bfgs symbrdn brdn diagbrdn
LOCDIR   = src/ksp/ksp/utils/lmvm/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
