ALL: lib

CPPFLAGS = 
CFLAGS   = 
FFLAGS   =
SOURCEC  = matdd.c matddaij.c
SOURCEF  = 
SOURCEH  = matdd.h
OBJSC    = matdd.o matddaij.o
OBJSF    =
DIRS     = 
LIBBASE  = libpetscdm
MANSEC   = Mat
LOCDIR   = src/dm/dd/matdd/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
