-include ../../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_HIP'

SOURCEHIP = vecmpicupm.hip.cpp
LIBBASE   = libpetscvec
MANSEC    = Vec
LOCDIR    = src/vec/vec/impls/mpi/cupm/hip/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
