# $Id: makefile,v 1.26 1998/06/12 21:42:42 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS = ${BS_INCLUDE}
SOURCEC  = ilu.c
SOURCEF  =
SOURCEH  = ilu.h
OBJSC    = ilu.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = 4
LOCDIR   = src/pc/impls/ilu/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
