
ALL: lib

DIRS     = tikz x win32 opengl
LOCDIR   = src/sys/classes/draw/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
