-include ../../../../../petscdir.mk

DIRS     = image tikz x win32 null
LOCDIR   = src/sys/classes/draw/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
