#! /bin/csh
# $Id: buildtest,v 1.4 2001/09/07 18:59:02 bsmith Exp $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set TMP=/Users/petsc
set MACH=playstation
set ARCH=macx
set TEST=testexamples_
set NICE=''
set RSH=ssh
set RCP='scp -q -B'
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=g
  set JOBS=(4 9)
else if ($day == Mon) then
  set BOPT=O_c++
  set JOBS=(4 9)
else if ($day == Tue) then
  set BOPT=O_complex
  set JOBS=(4 9)
else if ($day == Wed) then
  set BOPT=O
  set JOBS=(4 9)
else if ($day == Thu) then
  set BOPT=g_c++
  set JOBS=(4 9)
else if ($day == Fri) then
  set BOPT=g_complex
  set JOBS=(4 9)
else if ($day == Sat) then
  set BOPT=g
  set JOBS=(4 9)
endif

