CFLAGS           =
FFLAGS		 =
CPPFLAGS         =
FPPFLAGS         =
LOCDIR		 = src/tao/pde_constrained/tutorials/
MANSEC           =
EXAMPLESC	 = elliptic.c parabolic.c hyperbolic.c
TUTORIALS        = elliptic.c parabolic.c hyperbolic.c
EXAMPLESF	 =
EXAMPLESCH	 =
EXAMPLESFH       =
EXAMPLESMATLAB   =
CLEANFILES       = elliptic parabolic hyperbolic

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
