# $Id: makefile,v 1.22 1999/01/12 23:16:41 bsmith Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetsc
DIRS     = x
LOCDIR   = src/draw/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
