#requirespackage   'PETSC_HAVE_FORTRAN'

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = zoptions.c zplog.c zstart.c zstartf.c zsys.c zviewer.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = zoptions.o zplog.o zstart.o zstartf.o zsys.o zviewer.o
OBJSF    = 
LIBBASE  = libpetsc
MANSEC   = Sys
LOCDIR   = src/sys/ftn-custom/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


