function fig = soln1()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load soln1

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Position',[34 401 560 420]);
h1 = axes('Parent',h0, ...
	'View',[322.5 30], ...
	'CameraUpVector',[0 0 1], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat2, ...
	'VertexNormals',mat3, ...
	'Vertices',mat4);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat5, ...
	'VertexNormals',mat6, ...
	'Vertices',mat7);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat8, ...
	'VertexNormals',mat9, ...
	'Vertices',mat10);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat11, ...
	'VertexNormals',mat12, ...
	'Vertices',mat13);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat14, ...
	'VertexNormals',mat15, ...
	'Vertices',mat16);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat17, ...
	'VertexNormals',mat18, ...
	'Vertices',mat19);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat20, ...
	'VertexNormals',mat21, ...
	'Vertices',mat22);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat23, ...
	'VertexNormals',mat24, ...
	'Vertices',mat25);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat26, ...
	'VertexNormals',mat27, ...
	'Vertices',mat28);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat29, ...
	'VertexNormals',mat30, ...
	'Vertices',mat31);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat32, ...
	'VertexNormals',mat33, ...
	'Vertices',mat34);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat35, ...
	'VertexNormals',mat36, ...
	'Vertices',mat37);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat38, ...
	'VertexNormals',mat39, ...
	'Vertices',mat40);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat41, ...
	'VertexNormals',mat42, ...
	'Vertices',mat43);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat44, ...
	'VertexNormals',mat45, ...
	'Vertices',mat46);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat47, ...
	'VertexNormals',mat48, ...
	'Vertices',mat49);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat50, ...
	'VertexNormals',mat51, ...
	'Vertices',mat52);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat53, ...
	'VertexNormals',mat54, ...
	'Vertices',mat55);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat56, ...
	'VertexNormals',mat57, ...
	'Vertices',mat58);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat59, ...
	'VertexNormals',mat60, ...
	'Vertices',mat61);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat62, ...
	'VertexNormals',mat63, ...
	'Vertices',mat64);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat65, ...
	'VertexNormals',mat66, ...
	'Vertices',mat67);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat68, ...
	'VertexNormals',mat69, ...
	'Vertices',mat70);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat71, ...
	'VertexNormals',mat72, ...
	'Vertices',mat73);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat74, ...
	'VertexNormals',mat75, ...
	'Vertices',mat76);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat77, ...
	'VertexNormals',mat78, ...
	'Vertices',mat79);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat80, ...
	'VertexNormals',mat81, ...
	'Vertices',mat82);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat83, ...
	'VertexNormals',mat84, ...
	'Vertices',mat85);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat86, ...
	'VertexNormals',mat87, ...
	'Vertices',mat88);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat89, ...
	'VertexNormals',mat90, ...
	'Vertices',mat91);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat92, ...
	'VertexNormals',mat93, ...
	'Vertices',mat94);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat95, ...
	'VertexNormals',mat96, ...
	'Vertices',mat97);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat98, ...
	'VertexNormals',mat99, ...
	'Vertices',mat100);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat101, ...
	'VertexNormals',mat102, ...
	'Vertices',mat103);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat104, ...
	'VertexNormals',mat105, ...
	'Vertices',mat106);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat107, ...
	'VertexNormals',mat108, ...
	'Vertices',mat109);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat110, ...
	'VertexNormals',mat111, ...
	'Vertices',mat112);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat113, ...
	'VertexNormals',mat114, ...
	'Vertices',mat115);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat116, ...
	'VertexNormals',mat117, ...
	'Vertices',mat118);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat119, ...
	'VertexNormals',mat120, ...
	'Vertices',mat121);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat122, ...
	'VertexNormals',mat123, ...
	'Vertices',mat124);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat125, ...
	'VertexNormals',mat126, ...
	'Vertices',mat127);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat128, ...
	'VertexNormals',mat129, ...
	'Vertices',mat130);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat131, ...
	'VertexNormals',mat132, ...
	'Vertices',mat133);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat134, ...
	'VertexNormals',mat135, ...
	'Vertices',mat136);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat137, ...
	'VertexNormals',mat138, ...
	'Vertices',mat139);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat140, ...
	'VertexNormals',mat141, ...
	'Vertices',mat142);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat143, ...
	'VertexNormals',mat144, ...
	'Vertices',mat145);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat146, ...
	'VertexNormals',mat147, ...
	'Vertices',mat148);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat149, ...
	'VertexNormals',mat150, ...
	'Vertices',mat151);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat152, ...
	'VertexNormals',mat153, ...
	'Vertices',mat154);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat155, ...
	'VertexNormals',mat156, ...
	'Vertices',mat157);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat158, ...
	'VertexNormals',mat159, ...
	'Vertices',mat160);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat161, ...
	'VertexNormals',mat162, ...
	'Vertices',mat163);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat164, ...
	'VertexNormals',mat165, ...
	'Vertices',mat166);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat167, ...
	'VertexNormals',mat168, ...
	'Vertices',mat169);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat170, ...
	'VertexNormals',mat171, ...
	'Vertices',mat172);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat173, ...
	'VertexNormals',mat174, ...
	'Vertices',mat175);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat176, ...
	'VertexNormals',mat177, ...
	'Vertices',mat178);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat179, ...
	'VertexNormals',mat180, ...
	'Vertices',mat181);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat182, ...
	'VertexNormals',mat183, ...
	'Vertices',mat184);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat185, ...
	'VertexNormals',mat186, ...
	'Vertices',mat187);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat188, ...
	'VertexNormals',mat189, ...
	'Vertices',mat190);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat191, ...
	'VertexNormals',mat192, ...
	'Vertices',mat193);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat194, ...
	'VertexNormals',mat195, ...
	'Vertices',mat196);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat197, ...
	'VertexNormals',mat198, ...
	'Vertices',mat199);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat200, ...
	'VertexNormals',mat201, ...
	'Vertices',mat202);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat203, ...
	'VertexNormals',mat204, ...
	'Vertices',mat205);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat206, ...
	'VertexNormals',mat207, ...
	'Vertices',mat208);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat209, ...
	'VertexNormals',mat210, ...
	'Vertices',mat211);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat212, ...
	'VertexNormals',mat213, ...
	'Vertices',mat214);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat215, ...
	'VertexNormals',mat216, ...
	'Vertices',mat217);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat218, ...
	'VertexNormals',mat219, ...
	'Vertices',mat220);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat221, ...
	'VertexNormals',mat222, ...
	'Vertices',mat223);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat224, ...
	'VertexNormals',mat225, ...
	'Vertices',mat226);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat227, ...
	'VertexNormals',mat228, ...
	'Vertices',mat229);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat230, ...
	'VertexNormals',mat231, ...
	'Vertices',mat232);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat233, ...
	'VertexNormals',mat234, ...
	'Vertices',mat235);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat236, ...
	'VertexNormals',mat237, ...
	'Vertices',mat238);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat239, ...
	'VertexNormals',mat240, ...
	'Vertices',mat241);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat242, ...
	'VertexNormals',mat243, ...
	'Vertices',mat244);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat245, ...
	'VertexNormals',mat246, ...
	'Vertices',mat247);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat248, ...
	'VertexNormals',mat249, ...
	'Vertices',mat250);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat251, ...
	'VertexNormals',mat252, ...
	'Vertices',mat253);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat254, ...
	'VertexNormals',mat255, ...
	'Vertices',mat256);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat257, ...
	'VertexNormals',mat258, ...
	'Vertices',mat259);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat260, ...
	'VertexNormals',mat261, ...
	'Vertices',mat262);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat263, ...
	'VertexNormals',mat264, ...
	'Vertices',mat265);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat266, ...
	'VertexNormals',mat267, ...
	'Vertices',mat268);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat269, ...
	'VertexNormals',mat270, ...
	'Vertices',mat271);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat272, ...
	'VertexNormals',mat273, ...
	'Vertices',mat274);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat275, ...
	'VertexNormals',mat276, ...
	'Vertices',mat277);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat278, ...
	'VertexNormals',mat279, ...
	'Vertices',mat280);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat281, ...
	'VertexNormals',mat282, ...
	'Vertices',mat283);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat284, ...
	'VertexNormals',mat285, ...
	'Vertices',mat286);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat287, ...
	'VertexNormals',mat288, ...
	'Vertices',mat289);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat290, ...
	'VertexNormals',mat291, ...
	'Vertices',mat292);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat293, ...
	'VertexNormals',mat294, ...
	'Vertices',mat295);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat296, ...
	'VertexNormals',mat297, ...
	'Vertices',mat298);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat299, ...
	'VertexNormals',mat300, ...
	'Vertices',mat301);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat302, ...
	'VertexNormals',mat303, ...
	'Vertices',mat304);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat305, ...
	'VertexNormals',mat306, ...
	'Vertices',mat307);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat308, ...
	'VertexNormals',mat309, ...
	'Vertices',mat310);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat311, ...
	'VertexNormals',mat312, ...
	'Vertices',mat313);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat314, ...
	'VertexNormals',mat315, ...
	'Vertices',mat316);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat317, ...
	'VertexNormals',mat318, ...
	'Vertices',mat319);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat320, ...
	'VertexNormals',mat321, ...
	'Vertices',mat322);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat323, ...
	'VertexNormals',mat324, ...
	'Vertices',mat325);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat326, ...
	'VertexNormals',mat327, ...
	'Vertices',mat328);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat329, ...
	'VertexNormals',mat330, ...
	'Vertices',mat331);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat332, ...
	'VertexNormals',mat333, ...
	'Vertices',mat334);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat335, ...
	'VertexNormals',mat336, ...
	'Vertices',mat337);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat338, ...
	'VertexNormals',mat339, ...
	'Vertices',mat340);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat341, ...
	'VertexNormals',mat342, ...
	'Vertices',mat343);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat344, ...
	'VertexNormals',mat345, ...
	'Vertices',mat346);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat347, ...
	'VertexNormals',mat348, ...
	'Vertices',mat349);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat350, ...
	'VertexNormals',mat351, ...
	'Vertices',mat352);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat353, ...
	'VertexNormals',mat354, ...
	'Vertices',mat355);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat356, ...
	'VertexNormals',mat357, ...
	'Vertices',mat358);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat359, ...
	'VertexNormals',mat360, ...
	'Vertices',mat361);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat362, ...
	'VertexNormals',mat363, ...
	'Vertices',mat364);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat365, ...
	'VertexNormals',mat366, ...
	'Vertices',mat367);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat368, ...
	'VertexNormals',mat369, ...
	'Vertices',mat370);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat371, ...
	'VertexNormals',mat372, ...
	'Vertices',mat373);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat374, ...
	'VertexNormals',mat375, ...
	'Vertices',mat376);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat377, ...
	'VertexNormals',mat378, ...
	'Vertices',mat379);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat380, ...
	'VertexNormals',mat381, ...
	'Vertices',mat382);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat383, ...
	'VertexNormals',mat384, ...
	'Vertices',mat385);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat386, ...
	'VertexNormals',mat387, ...
	'Vertices',mat388);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat389, ...
	'VertexNormals',mat390, ...
	'Vertices',mat391);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat392, ...
	'VertexNormals',mat393, ...
	'Vertices',mat394);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat395, ...
	'VertexNormals',mat396, ...
	'Vertices',mat397);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat398, ...
	'VertexNormals',mat399, ...
	'Vertices',mat400);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat401, ...
	'VertexNormals',mat402, ...
	'Vertices',mat403);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat404, ...
	'VertexNormals',mat405, ...
	'Vertices',mat406);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat407, ...
	'VertexNormals',mat408, ...
	'Vertices',mat409);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat410, ...
	'VertexNormals',mat411, ...
	'Vertices',mat412);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat413, ...
	'VertexNormals',mat414, ...
	'Vertices',mat415);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat416, ...
	'VertexNormals',mat417, ...
	'Vertices',mat418);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat419, ...
	'VertexNormals',mat420, ...
	'Vertices',mat421);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat422, ...
	'VertexNormals',mat423, ...
	'Vertices',mat424);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat425, ...
	'VertexNormals',mat426, ...
	'Vertices',mat427);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat428, ...
	'VertexNormals',mat429, ...
	'Vertices',mat430);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat431, ...
	'VertexNormals',mat432, ...
	'Vertices',mat433);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat434, ...
	'VertexNormals',mat435, ...
	'Vertices',mat436);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat437, ...
	'VertexNormals',mat438, ...
	'Vertices',mat439);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat440, ...
	'VertexNormals',mat441, ...
	'Vertices',mat442);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat443, ...
	'VertexNormals',mat444, ...
	'Vertices',mat445);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'FaceVertexCData',mat446, ...
	'VertexNormals',mat447, ...
	'Vertices',mat448);
h2 = patch('Parent',h1, ...
	'FaceColor','interp', ...
	'Faces',[1 2 3 4], ...
	'Fa