# $Id: makefile,v 1.28 2001/08/22 18:01:55 balay Exp $ 

ALL: lib

SOURCEH  = snesimpl.h ../../include/petscsnes.h
DIRS     = interface mf impls examples utils
LOCDIR   = src/snes/
MANSEC   = SNES

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

