# $Id: makefile,v 1.32 1999/01/31 16:08:06 bsmith Exp bsmith $

ALL: lib

LIBBASE  = libpetscsles
DIRS     = jacobi none sor lu shell bjacobi mg eisens ilu icc asm sles composite redundant
LOCDIR   = src/sles/pc/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
