# $Id: makefile,v 1.38 2000/09/25 18:02:22 curfman Exp bsmith $

ALL: lib

LIBBASE  = libpetscsles
DIRS     = jacobi none sor lu shell bjacobi mg eisens ilu icc asm sles composite redundant milu spai is cholesky pbjacobi
LOCDIR   = src/sles/pc/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test

