# $Id: makefile,v 1.27 1998/01/06 20:09:48 bsmith Exp balay $

ALL: lib

CFLAGS   = 
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = jacobi none sor lu shell bjacobi mg eisens ilu icc asm sles composite
LOCDIR   = src/pc/impls/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base
