#! /bin/csh
set DATAFILESPATH=/home/balay/datafiles
set APPEND='2>&1 >>'
#
if ($day == Sun) then
  set BOPT=g
  set JOBS=(1 2 3 6 8)
else if ($day == Mon) then
  set BOPT=O_c++
  set JOBS=(1 2 3 6 13 18)
else if ($day == Tue) then
  set ARCH=win32_borland
  set BOPT=g
  set JOBS=(4)
else if ($day == Wed) then
  set BOPT=O
  set JOBS=(1 2 3 6 8)
else if ($day == Thu) then
  set ARCH=win32_borland
  set BOPT=O_c++
  set JOBS=(4)
else if ($day == Fri) then
  set BOPT=O_complex
  set JOBS=(1 2 3 5 10 13)
else if ($day == Sat) then
  set BOPT=g
  set JOBS=(1 2 3 6 13)
endif






