#! /bin/csh
#
if ($day == Sun) then
  set BOPT=g_c++
else if ($day == Mon) then
  set BOPT=g    
else if ($day == Tue) then
  set BOPT=O        
else if ($day == Wed) then
  set BOPT=g_complex 
else if ($day == Thu) then
  set BOPT=O_c++
else if ($day == Fri) then
  set BOPT=O_complex    
else if ($day == Sat) then
  set BOPT=O        
endif






