#! /bin/csh
# $Id: buildtest,v 1.4 2001/09/07 18:59:02 bsmith Exp $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set DATAFILESPATH=/Users/barrysmith/datafiles
set TMP=/Users/barrysmith/petsc-test
set MACH=localhost
set CONFIGURE='yes'
set TEST=testexamples_
set RSH='ssh -X'
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=g_complex
else if ($day == Mon) then
  set BOPT=O_c++
else if ($day == Tue) then
  set BOPT=g
else if ($day == Wed) then
  set BOPT=O_complex
else if ($day == Thu) then
  set BOPT=g_c++
else if ($day == Fri) then
  set BOPT=O_c++
else if ($day == Sat) then
  set BOPT=O
endif
