# $Id: makefile,v 1.34 1999/02/02 21:22:54 balay Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = axis.c lg.c dscatter.c hists.c zoom.c hue.c
SOURCEF  =
SOURCEH  = 
OBJSC    = axis.o lg.o dscatter.o hists.o zoom.o hue.o
OBJSF    =
LIBBASE  = libpetsc
MANSEC   = Draw
LOCDIR   = src/sys/src/draw/utils/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
