#requirespackage 'PETSC_HAVE_HIP'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEHIP = handle.hip.cpp
SOURCEF  =
SOURCEH  =
MANSEC   = Sys
LIBBASE  = libpetscsys
LOCDIR   = src/sys/objects/hip/
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

