# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = cg.c
SOURCEF  = 
SOURCEH  = cg.h
OBJSC    = cg.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = taosolver
LOCDIR   = src/unconstrained/impls/cg/

include ${TAO_DIR}/conf/tao_base

