# $Id: makefile,v 1.19 1998/06/12 21:33:26 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = impls examples interface utils
LOCDIR   = src/viewer/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

