# $Id: makefile,v 1.18 1998/03/19 02:12:12 balay Exp balay $ 

ALL: lib

SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = impls examples interface utils
LOCDIR   = src/viewer/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

