# $Id: makefile,v 1.29 2001/08/22 17:58:53 balay Exp $ 

ALL: lib

SOURCEH  = viewerimpl.h ../../../../include/petscviewer.h
DIRS     = impls examples interface
LOCDIR   = src/sys/src/viewer/
MANSEC   = Viewer

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
