ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pounder.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = pounder.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/tao/unconstrained/impls/pounder/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

