
ALL: lib

CFLAGS   = #-DPCASA_VERBOSE -DPCASA_ENERGY_ERR -DPCASA_RES_ERR #-DCORR_CHECK
FFLAGS   =
SOURCEC  = asa.c
SOURCEF  =
SOURCEH  = 
OBJSC    = asa.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/asa/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
