# $Id: makefile,v 1.36 1998/05/29 20:35:31 bsmith Exp balay $ 

ALL: lib

SOURCEC  = pbvec.c pdvec.c pvec2.c pmap.c
SOURCEF  =
SOURCEH  = pvecimpl.h 
OBJSC    = pbvec.o pdvec.o pvec2.o pmap.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = 1
LOCDIR   = src/vec/impls/mpi/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

