
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = rich.c richscale.c
SOURCEF  =
SOURCEH  = richardsonimpl.h
OBJSC    = rich.o richscale.o
OBJSF    =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/rich/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
