\
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = binaryMatlab.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = binaryMatlab.o
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMDA
DIRS     = 
LOCDIR   = src/dm/impls/da/utils/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
