
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ell.c fdell.c
SOURCEF  =
SOURCEH  = ell.h
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat
LOCDIR   = src/mat/impls/ell/seq/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
