
#requirespackage 'PETSC_USING_F90'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zblockf90.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    = 
LIBBASE  = libpetscvec
LOCDIR   = src/vec/is/impls/f90-custom/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


