-include ../../../../petscdir.mk

DIRS     = tutorials cuda kokkos
LIBBASE  = libpetscts
MANSEC   = TS
SUBMANSEC= LANDAU

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
