
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lsvi.c lsviparams.c
SOURCEF  =
SOURCEH  = lsviimpl.h
OBJSC    = lsvi.o lsviparams.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/lsvi/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

