
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = asils.c asfls.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/complementarity/impls/asls/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

