-include ../../../../../petscdir.mk

SOURCEC  = asils.c asfls.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetsctao
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

