ALL: lib

CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = swarm.c data_bucket.c
SOURCEF  =
SOURCEH  =
DIRS     = 
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMSWARM
LOCDIR   = src/dm/impls/swarm/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
