
ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = random.c randreg.c dlregisrand.c randomc.c
SOURCEF	  =
SOURCEH	  = 
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = 
LOCDIR	  = src/sys/random/interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

