ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = mpibstream.c
SOURCEF  = 
SOURCEH  = 
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
LOCDIR   = src/mat/impls/baij/mpi/bstream/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
