ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ntl.c
SOURCEF  = 
SOURCEH  = ntl.h
OBJSC    = ntl.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = 
LOCDIR   = src/unconstrained/impls/ntl/

include ${TAO_DIR}/conf/tao_base

