
ALL: lib

DIRS     = unit morethuente  gpcglinesearch armijo owarmijo
LOCDIR   = src/linesearch/impls/
LIBRARY = taolinesearch
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

