
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = aosetlocal.c
SOURCEF  =
SOURCEH  = 
OBJSC    = aosetlocal.o
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = AO
LOCDIR   = src/dm/ao/utils/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

