# $Id: makefile,v 1.11 1999/09/27 21:32:28 bsmith Exp bsmith $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = aopart.c aosetlocal.c
SOURCEF  =
SOURCEH  = 
OBJSC    = aopart.o aosetlocal.o
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = AO
LOCDIR   = src/dm/ao/utils/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test

