
#requiresdefine 'PETSC_USING_F90'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zsnesf90.c
SOURCEF  = 
SOURCEH  = 
LIBBASE  = libpetscsnes
LOCDIR   = src/snes/interface/f90-custom/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


