-include ../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zsnesf90.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
LOCDIR   = src/snes/interface/f90-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


