-include ../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_KOKKOS'

SOURCEC  =
SOURCECU =
SOURCEKOKKOS = kinit.kokkos.cxx
SOURCEF  =
SOURCEH  =
MANSEC   = Sys
LIBBASE  = libpetscsys
LOCDIR   = src/sys/objects/kokkos/
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

