-include ../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_KOKKOS'

SOURCEKOKKOS = kinit.kokkos.cxx
MANSEC   = Sys
LIBBASE  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

