-include ../../../../../../petscdir.mk

SOURCEC   = aobasic.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscvec
DIRS      =
MANSEC    = Vec
SUBMANSEC = AO

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

