
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = aobasic.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscvec
DIRS      =
MANSEC    = Vec
SUBMANSEC = AO
LOCDIR    = src/vec/is/ao/impls/basic/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

