# $Id: makefile,v 1.12 2000/08/17 04:53:26 bsmith Exp balay $ 

ALL: lib

DIRS     = examples src
LOCDIR   = src/contrib/sda/
NOADIC   = true

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
