# $Id: makefile,v 1.8 1998/03/19 02:14:36 balay Exp balay $ 

ALL: lib

SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC    = 
OBJSF    =
LIBBASE  = libpetsccontrib
DIRS     = examples src
LOCDIR   = src/contrib/sda/
NOADIC   = true

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
