PETSC_DIR = ../../..

ALL: lib

CFLAGS   = $(PCONF) $(PETSC_INCLUDE)
SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC    = 
OBJSF    =
LIBBASE  = libpetsccontrib
DIRS     = examples src

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/$(PETSC_ARCH)
