# $Id: makefile,v 1.41 2000/08/17 04:50:24 bsmith Exp balay $ 



LOCDIR	 = src/sys/src/viewer/examples/
LIBBASE	 = libpetscvec
DIRS	 = tutorials tests


include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
