# $Id: makefile,v 1.38 1998/06/13 05:06:14 balay Exp balay $ 

ALL: ex1

CFLAGS   = 
FFLAGS	 = 
SOURCEC	 = 
SOURCEF	 = 
SOURCEH	 = 
OBJSC	 = 
OBJSF	 = 
LOCDIR	 = src/viewer/examples/
LIBBASE	 = libpetscvec
DIRS	 = tutorials tests


include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

