
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = ziscoloringf.c zisltogf.c
OBJSC    = ziscoloringf.o zisltogf.o
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE	 = libpetscvec
LOCDIR	 = src/vec/is/utils/ftn-custom/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
