-include ../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zhdf5io.c zisltogf.c zvsectionisf.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE	 = libpetscvec
LOCDIR	 = src/vec/is/utils/ftn-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
