# $Id: makefile,v 1.3 2000/04/09 03:11:41 bsmith Exp bsmith $ 

ALL: lib

SOURCEH  = pfimpl.h
DIRS     = interface impls examples
LOCDIR   = src/pf/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
