# $Id: makefile,v 1.4 2000/08/17 04:53:35 bsmith Exp bsmith $ 

ALL: lib

SOURCEH  = pfimpl.h ../../include/petscpf.h
DIRS     = interface impls examples
LOCDIR   = src/pf/
MANSEC   = PF

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
