# $Id: makefile,v 1.6 2001/08/22 18:02:54 balay Exp $ 

ALL: lib

SOURCEH  = pfimpl.h ../../include/petscpf.h
DIRS     = interface impls examples
LOCDIR   = src/pf/
MANSEC   = PF

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
