# $Id: makefile,v 1.19 1998/03/19 02:04:40 balay Exp balay $ 

ALL: lib

CFLAGS   =  ${CPPFLAGS}
SOURCEC  =
SOURCEF  =
SOURCEH  = axpy.h bitarray.h dot.h ilu.h setval.h spops.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = 
LOCDIR   = src/inline/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
