
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = dot.h iclsse.h
OBJSC    =
OBJSF    =
LIBBASE  = 
DIRS     = 
LOCDIR   = src/inline/
MANSEC   = Vec

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
