-include ../../../../../../petscdir.mk
#requirespackage   'PETSC_HAVE_SUPERLU'

CFLAGS   = ${SUPERLU_INCLUDE}
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
