# $Id: makefile,v 1.24 1997/08/22 15:17:57 bsmith Exp balay $

ALL: lib

CFLAGS   = 
SOURCEC  =  
SOURCEF  =
SOURCEH  = 
OBJSC    =  
OBJSF    =
LIBBASE  = libpetscsnes
DIRS     = ls tr test umtr umls
LOCDIR   = src/snes/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base


