
ALL: lib

DIRS     = ksponly ls tr test richardson python vi ngmres sorqn qn shell ncg fas gs ms
LOCDIR   = src/snes/impls/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


