
SOURCEH   =
SOURCEC   = sfalltoall.c
LIBBASE   = libpetscvec
DIRS      =
LOCDIR    = src/vec/is/sf/impls/basic/alltoall
MANSEC    = Vec
SUBMANSEC = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
