# $Id: makefile,v 1.3 2000/08/17 04:50:53 bsmith Exp balay $ 

ALL:

LOCDIR   = src/sys/src/matlabengine/examples
DIRS     = tutorials

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
