# $Id: makefile,v 1.2 2000/05/04 16:24:55 bsmith Exp bsmith $ 

ALL:

LOCDIR   = src/sys/src/matlabengine/examples
DIRS     = tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
