#requirespackage 'PETSC_HAVE_VIENNACL'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mpiaijviennacl.cxx
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat
LOCDIR   = src/mat/impls/aij/mpi/mpiviennacl/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
