-include ../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zplexcreate.c zplexdistribute.c zplexsubmesh.c zplexexodusii.c zplexgmsh.c zplexfluent.c zplexextrude.c
LIBBASE  = libpetscdm

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
