# $Id: makefile,v 1.8 1998/06/12 21:08:17 balay Exp balay $ 

ALL:

SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        = 
LIBBASE	        = libpetscmat
LOCDIR          = src/mat/examples/
DIRS            = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
