# $Id: makefile,v 1.13 1999/03/01 04:54:34 bsmith Exp bsmith $ 

ALL:

DOCS     = readme
LOCDIR   = src/mat/examples/
DIRS     = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
