# $Id: makefile,v 1.10 1998/06/15 16:17:29 balay Exp balay $ 

ALL:

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC	 =
OBJSF	 = 
DOCS     = README
LIBBASE	 = libpetscmat
LOCDIR   = src/mat/examples/
DIRS     = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
