ALL: lib

CPPFLAGS =
CFLAGS   = ${P4EST_INCLUDE}
FFLAGS   =
SOURCEC  = dmp4est.c dmp8est.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMFOREST
LOCDIR   = src/dm/impls/forest/p4est/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
