-include ../../../../../../petscdir.mk

SOURCEC   = febasic.c
SOURCEF   =
LIBBASE   = libpetscdm
DIRS      =
MANSEC    = DM
SUBMANSEC = FE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
