
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = const.c
SOURCEF  =
SOURCEH  = 
OBJSC    = const.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/pf/impls/constant/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

