-include ../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = ztsadaptf.c
LIBBASE  = libpetsts

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
