ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  = bagenum.F
SOURCEH  = 
DIRS     = 
LIBBASE  = libpetscsys
MANSEC   = Sys
LOCDIR   = src/sys/bag/f2003-src/fsrc/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
