
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = armijo.c
SOURCEF  = 
SOURCEH  = armijo.h
OBJSC    = armijo.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/linesearch/impls/armijo/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

