-include ../../../../../petscdir.mk

SOURCEC   = armijo.c
SOURCEF   =
SOURCEH   = armijo.h
LIBBASE   = libpetsctao
MANSEC    = Tao
SUBMANSEC = TaoLineSearch
LOCDIR    = src/tao/linesearch/impls/armijo/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

