-include ../../../../../petscdir.mk

SOURCEC  = nls.c
SOURCEH  = nlsimpl.h
LIBBASE  = libpetsctao
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

