ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nls.c
SOURCEF  =
SOURCEH  = nlsimpl.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/unconstrained/impls/nls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

