ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nls.c
SOURCEF  =
SOURCEH  = nls.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/unconstrained/impls/nls/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

