
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = binv.c
SOURCEF  =
SOURCEH  =
OBJSC    = binv.o
OBJSF    =
MANSEC   = Viewer
LIBBASE  = libpetscsys
DIRS     = 
LOCDIR   = src/sys/viewer/impls/binary/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
