
ALL: lib

SOURCEC  = petscglobal.c
DIRS     = 
LOCDIR   = src/sys/adic/
NOADIC   = false
MANSEC   = Sys

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
