-include ../../../../../../petscdir.mk

SOURCEC  = pipecg2.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscksp
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

