#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zhdf5f.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/classes/viewer/impls/hdf5/ftn-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
