-include ../../../petscdir.mk

DIRS     = explicit implicit pseudo python arkimex rosw eimex mimex bdf glee symplectic multirate
MANSEC   = TS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc


