PETSC_DIR = ../../..

ALL: lib

CFLAGS   =  $(PETSC_INCLUDE) $(PCONF) \
           -I../.. $(CONF)
SOURCEC  =  
SOURCEF  =
SOURCEH  = 
OBJSC    =  
OBJSF    =
LIBBASE  = libpetscsnes
DIRS     = ls tr test umtr umls

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/$(PETSC_ARCH)


