# $Id: makefile,v 1.13 1999/02/03 04:31:39 bsmith Exp bsmith $

ALL: lib

DIRS     = explicit implicit pseudo
LOCDIR   = src/ts/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test


