-include ../../../../../petsckdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zvsectionf90.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscvec
LOCDIR   = src/vec/vec/utils/f90-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


