# $Id: makefile,v 1.6 1998/06/13 05:04:22 balay Exp balay $ 

ALL:

CFLAGS   =
FFLAGS   =
SOURCEC	 = 
SOURCEF	 =
SOURCEH	 =
OBJSC	 =
OBJSF	 = 
LIBBASE	 = libpetscec
LOCDIR   = src/ec/examples/
DIRS     = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
