# $Id: makefile,v 1.5 1998/04/24 01:02:53 bsmith Exp balay $ 

ALL:

SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        = 
LIBBASE	        = libpetscec
LOCDIR          = src/ec/examples/
DIRS            = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
