# $Id: makefile,v 1.4 2001/08/22 18:01:32 balay Exp $

CFLAGS   =
FFLAGS   =
LIBBASE  = libpetscsles
DIRS     = nn
LOCDIR   = src/sles/pc/impls/is/
SOURCEC  = is.c
SOURCEH  = is.h
OBJSC    = is.o
MANSEC   = PC

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
