-include ../../../../../../petscdir.mk

SOURCEC  = diagbrdn.c
SOURCEH  = diagbrdn.h
LIBBASE  = libpetscksp
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
