-include ../../../../petscdir.mk

CPPFLAGS = ${NETCFD_INCLUDE} ${EXODUSII_INCLUDE}
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPlex

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
