-include ../../../../petscdir.mk

CPPFLAGS  = ${NETCFD_INCLUDE} ${EXODUSII_INCLUDE}
MANSEC    = DM
SUBMANSEC = DMPlex

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
