-include ../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zdsf.c zdtf.c zdtfef.c
LIBBASE  = libpetscdm
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


