#ifdef PETSC_RCS_HEADER
"$Id: petscconf.h,v 1.26 2001/03/26 19:23:56 balay Exp $"
"Defines the configuration for this machine"
#endif

#if !defined(INCLUDED_PETSCCONF_H)
#define INCLUDED_PETSCCONF_H

#define PARCH_t3d
#define PETSC_ARCH_NAME "t3d"

#define PETSC_HAVE_POPEN
#define PETSC_HAVE_LIMITS_H
#define PETSC_HAVE_PWD_H 
#define PETSC_HAVE_STRING_H 
#define PETSC_HAVE_MALLOC_H 
#define PETSC_HAVE_DRAND48 
#define PETSC_HAVE_UNISTD_H
#define PETSC_HAVE_STDLIB_H
#define PETSC_HAVE_SYS_TIME_H 
#define PETSC_HAVE_UNAME
#define PETSC_HAVE_GETCWD
#define PETSC_HAVE_SYS_PARAM_H
#define PETSC_HAVE_SYS_STAT_H

#define PETSC_HAVE_FORTRAN_CAPS 
#define PETSC_USES_CPTOFCD  
#define PETSC_USES_FORTRAN_SINGLE

#define PETSC_HAVE_READLINK
#define PETSC_HAVE_MEMMOVE

#define PETSC_CANNOT_START_DEBUGGER

#define PETSC_HAVE_DOUBLES_ALIGNED
#define PETSC_HAVE_DOUBLE_ALIGN_MALLOC
#define PETSC_HAVE_FAST_MPI_WTIME
#define PETSC_SIZEOF_VOID_P 8
#define PETSC_SIZEOF_INT 8
#define PETSC_SIZEOF_SHORT 4
#define PETSC_SIZEOF_DOUBLE 8
#define PETSC_BITS_PER_BYTE 8
#define PETSC_SIZEOF_FLOAT 4
#define PETSC_SIZEOF_LONG 8
#define PETSC_SIZEOF_LONG_LONG 8

#define PETSC_HAVE_PXFGETARG
#define PETSC_HAVE_SYS_RESOURCE_H
#define PETSC_HAVE_CLOCK

#define PETSC_WORDS_BIGENDIAN 1

#define PETSC_HAVE_SLEEP
#define PETSC_CAN_SLEEP_AFTER_ERROR
#define PETSC_USE_CTABLE
#define PETSC_USE_SBREAK_FOR_SIZE

#define PETSC_HAVE_F90_H "f90impl/f90_t3e.h"
#define PETSC_HAVE_F90_C "src/sys/src/f90/f90_t3e.c"
#define PETSC_HAVE_CXX_NAMESPACE

#endif
