ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF90= optionenum.F90
SOURCEH  =
DIRS     =
LIBBASE  = libpetscsys
MANSEC   = Sys
LOCDIR   = src/sys/objects/f2003-src/fsrc/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
