
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = theta.c
SOURCEF  =
SOURCEH  = 
OBJSC    = theta.o
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/impls/implicit/theta/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test

