ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gpcg.c
SOURCEF  = 
SOURCEH  = gpcg.h
OBJSC    = gpcg.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = 
LOCDIR   = src/bound/impls/gpcg/

include ${TAO_DIR}/conf/tao_base

