
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = general.c
SOURCEF   =
SOURCEH   = general.h
LIBBASE   = libpetscvec
MANSEC    = Vec
SUBMANSEC = IS
LOCDIR    = src/vec/is/is/impls/general/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

