-include ../../../../../petscdir.mk

SOURCEC  = adaptnone.c
LIBBASE  = libpetscts
MANSEC   = TS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

