# $Id: makefile,v 1.13 1998/06/15 16:12:58 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = beuler.c
SOURCEF  =
SOURCEH  = 
OBJSC    = beuler.o
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/impls/implicit/beuler/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

