# $Id: makefile,v 1.11 1998/04/23 23:46:15 balay Exp balay $ 

ALL: lib

SOURCEC  = beuler.c
SOURCEF  =
SOURCEH  = 
OBJSC    = beuler.o
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = t
LOCDIR   = src/ts/impls/implicit/beuler/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

