#! /bin/csh
# $Id: buildtest,v 1.6 2001/04/05 15:41:00 curfman Exp $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set DATAFILESPATH=/u/ac/balay/datafiles
set TMP=/u/ac/balay/petsc-test
set MACH=balay@user02.ncsa.uiuc.edu # titan.ncsa.uiuc.edu
set ARCH=linux64_intel
set TEST=testexamples_
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=g_complex 
  set JOBS=(1 2 3 5 10 12 13)       
else if ($day == Mon) then
  set BOPT=O        
  set JOBS=(1 2 3 6 8 12)
else if ($day == Tue) then
  set BOPT=g_c++
  set JOBS=(1 2 3 6 8 12 13 )
else if ($day == Wed) then
  set BOPT=O_c++
  set JOBS=(1 2 3 6 8 12 13 )
else if ($day == Thu) then
  set ARCH=linux64
  set BOPT=O        
  set JOBS=(1 2 3 6 8)        
else if ($day == Fri) then
  set ARCH=linux64
  set BOPT=O_complex    
  set JOBS=(1 2 3 5 10 13)
else if ($day == Sat) then
  set BOPT=g    
  set JOBS=(1 2 3 6 8 13)        
endif






