#! /bin/csh
# $Id: buildtest,v 1.4 2001/06/21 21:14:27 bsmith Exp $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set TMP=/sandbox/petsc/petsc-test
set MACH=smash
set TEST=testexamples_
set CONFIGURE='yes'
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=g
else if ($day == Mon) then
  set BOPT=O    
else if ($day == Tue) then
  set BOPT=g        
else if ($day == Wed) then
  set BOPT=O
else if ($day == Thu) then
  set BOPT=g
else if ($day == Fri) then
  set BOPT=O
else if ($day == Sat) then
  set BOPT=g
endif






