#! /bin/csh
# $Id: buildtest,v 1.6 2001/04/05 15:41:00 curfman Exp $ 
#
# Defines the configuration for maint/buildtest, this is sourced by that script
#
set TMP=/sandbox/petsc/petsc-test
set MACH=harley
set CONFIGURE='yes'
set TEST=testexamples_
#
set day=`date | cut -f1 -d" "`
if ($day == Sun) then
  set BOPT=g_c++
else if ($day == Mon) then
  set BOPT=g    
else if ($day == Tue) then
  set BOPT=O        
else if ($day == Wed) then
  set BOPT=g_complex 
else if ($day == Thu) then
  set BOPT=O_c++
else if ($day == Fri) then
  set BOPT=O_complex    
else if ($day == Sat) then
  set BOPT=O        
endif






