#
CFLAGS		 =
FFLAGS		 =
CPPFLAGS   =
FPPFLAGS   =
MANSEC     = Vec
LOCDIR		 = src/vec/vec/utils/tagger/tutorials/
EXAMPLESC	 = ex1.c

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
