-include ../../../../../../petscdir.mk

MANSEC     = Vec
LOCDIR     = src/vec/vec/utils/tagger/tutorials/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
