#ifndef _COMPAT_PETSC_VIEWER_H
#define _COMPAT_PETSC_VIEWER_H

#if (PETSC_VERSION_(3,1,0) || \
     PETSC_VERSION_(3,0,0))
#define PETSCVIEWERSOCKET       PETSC_VIEWER_SOCKET
#define PETSCVIEWERASCII        PETSC_VIEWER_ASCII
#define PETSCVIEWERBINARY       PETSC_VIEWER_BINARY
#define PETSCVIEWERSTRING       PETSC_VIEWER_STRING
#define PETSCVIEWERDRAW         PETSC_VIEWER_DRAW
#define PETSCVIEWERVU           PETSC_VIEWER_VU
#define PETSCVIEWERMATHEMATICA  PETSC_VIEWER_MATHEMATICA
#define PETSCVIEWERSILO         PETSC_VIEWER_SILO
#define PETSCVIEWERNETCDF       PETSC_VIEWER_NETCDF
#define PETSCVIEWERHDF5         PETSC_VIEWER_HDF5
#define PETSCVIEWERMATLAB       PETSC_VIEWER_MATLAB
#endif

#if (PETSC_VERSION_(3,1,0) || \
     PETSC_VERSION_(3,0,0))
#define PetscViewerFileGetName(v,n) \
        PetscViewerFileGetName((v),(char**)(n))
#endif

#endif /* _COMPAT_PETSC_VIEWER_H */
