ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pythonsys.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
DIRS     =
LOCDIR   = src/sys/python/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
