ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = python.c
SOURCEF  =
SOURCEH  = 
OBJSC    = python.o
OBJSF    =
LIBBASE  = libpetsc
DIRS     = 
LOCDIR   = src/sys/python/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
