ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pythonsys.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscsys
DIRS     =
LOCDIR   = src/sys/python/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
