#requirespackage 'PETSC_HAVE_TAU_PERFSTUBS'
-include ../../../petsckdir.mk

SOURCEC	  = pstimer.c
MANSEC    = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
