#requirespackage 'PETSC_HAVE_TAU_PERFSTUBS'
-include ../../../petsckdir.mk

SOURCEC	  = pstimer.c
SOURCEH	  = timer.h
MANSEC    = Sys
LOCDIR    = src/sys/perfstubs/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
