
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mcomposite.c
SOURCEF  =
SOURCEH  = 
OBJSC    = mcomposite.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/composite/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
