-include ../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_HDF5'

MANSEC         = Sys
SUBMANSEC      = Viewer
BFORTSUBMANSEC = IS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
