-include ../../../petscdir.mk

LOCDIR         = share/petsc/matlab/
EXAMPLESMATLAB = generatePetscTestFiles.m laplacian.m launch.m PetscBagRead.m PetscBinaryRead.m PetscBinaryWrite.m PetscReadBinaryMatlab.m PetscReadBinaryTrajectory.m UFgetPetscMat.m

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
