-include ../../../../../petscdir.mk
#requiresdefine 'PETSC_HAVE_CXX'

MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = cupm sycl host

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

