#requiresscalar    real

SOURCEH  =
DIRS     = impls tutorials
LOCDIR   = src/tao/unconstrained/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

