
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC	 = stashij.c matij.c
SOURCEF	 =
SOURCEH	 = stashij.h
LIBBASE	 = libpetscmat
DIRS	 = 
MANSEC	 = Mat
LOCDIR	 = src/mat/impls/ij/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
