
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = index.c isregall.c isreg.c
SOURCEF  = 
SOURCEH  = 
LIBBASE  = libpetscvec
MANSEC   = IS
LOCDIR   = src/vec/is/interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

