# $Id: makefile,v 1.31 1998/06/15 15:48:08 balay Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = index.c 
SOURCEF  = 
SOURCEH  = 
OBJSC    = index.o 
OBJSF    =
LIBBASE  = libpetsc
MANSEC   = 6
LOCDIR   = src/is/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

