-include ../../../../../../petscdir.mk
#requirespackage   'PETSC_HAVE_LUSOL'
#requiresscalar    real
#requiresprecision double

MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
