ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = snesngmres.c
SOURCEF  =
SOURCEH  =
OBJSC    = snesngmres.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/ngmres/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
