# $Id: makefile,v 1.33 2001/08/22 18:01:42 balay Exp $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = preonly.c
SOURCEF  =
OBJSC    = preonly.o
OBJSF    =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/preonly/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
