#requiresdefine   'PETSC_HAVE_MATLAB_ENGINE'

CFLAGS   = ${MATLAB_INCLUDE}
SOURCEC  = gcreatev.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/utils/matlab/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

