
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = schurm.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = schurm.o
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/utils/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
