-include ../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = plextrextrude.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = DMPLEX
LOCDIR    = src/dm/impls/plex/transform/impls/extrude

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
