-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_PARTY'

CPPFLAGS  = ${PARTY_INCLUDE}
MANSEC    = Mat
SUBMANSEC = MatGraphOperations

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
