# $Id: makefile,v 1.37 1999/11/05 14:43:58 bsmith Exp $

#requirespackage '-DPETSC_HAVE_WIN32'

ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  = 
SOURCEC   = win32draw.c 
SOURCEF   = 
SOURCEH   = win32draw.h
OBJSC     = win32draw.o
OBJSF     =
MANSEC    = Draw
LIBBASE   = libpetsc
DIRS      = 
LOCDIR    = src/sys/src/draw/impls/win32/
NOADIC    = true

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
