-include ../../../../petscdir.mk

SOURCEC  = glee.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscts
MANSEC   = TS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

