# $Id: makefile,v 1.30 1998/06/12 21:34:21 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = matrix.c mhas.c fdmatrix.c matcnv.c mgtype.c
SOURCEF  =
SOURCEH  = 
OBJSC    = matrix.o mhas.o fdmatrix.o matcnv.o mgtype.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = 2
LOCDIR   = src/mat/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
