-include ../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_HYPRE'

CFLAGS   = ${HYPRE_INCLUDE}
LIBBASE  = libpetscvec
MANSEC   = Vec

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

