-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_MKL_SPARSE_OPTIMIZE'

MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
