
ALL: lib 

CFLAGS    = 
FFLAGS    =
CPPFLAGS  = 
SOURCEC	  = gcomm.c   gtype.c   olist.c    pname.c  tagm.c \
            destroy.c gcookie.c inherit.c options.c pgname.c prefix.c init.c \
	    pinit.c ptype.c state.c aoptions.c mpinit.c subcomm.c
SOURCEF	  =
SOURCEH	  = ../../../include/petscoptions.h
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = f2003-src
LOCDIR	  = src/sys/objects/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

