
ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  = 
SOURCEC	  = gcomm.c   gtype.c   olist.c    pname.c  tagm.c \
            destroy.c gcookie.c inherit.c options.c pgname.c prefix.c init.c \
	    pinit.c ptype.c state.c aoptions.c mpinit.c subcomm.c pthread.c
SOURCEF	  =
SOURCEH	  = ../../../include/petscoptions.h
OBJSC	  = gcomm.o   gtype.o   olist.o    pname.o  tagm.o \
            destroy.o gcookie.o inherit.o options.o pgname.o prefix.o init.o \
	    pinit.o ptype.o state.o aoptions.o mpinit.o subcomm.o pthread.o
OBJSF	  =
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = 
LOCDIR	  = src/sys/objects/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

