
ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC	  = version.c gcomm.c gtype.c olist.c pname.c tagm.c destroy.c gcookie.c inherit.c options.c optionsyaml.c pgname.c prefix.c init.c pinit.c ptype.c state.c aoptions.c subcomm.c fcallback.c package.c
SOURCEF	  =
SOURCEH	  = ../../../include/petscoptions.h
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = f2003-src cxx kokkos device
LOCDIR	  = src/sys/objects/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

