# $Id: makefile,v 1.11 1999/02/03 04:31:29 bsmith Exp bsmith $ 

ALL:

LOCDIR	 = src/sles/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
