# $Id: makefile,v 1.9 1998/06/13 05:05:34 balay Exp balay $ 

ALL:

CFLAGS	 = 
FFLAGS	 = 
SOURCEC	 = 
SOURCEF	 = 
SOURCEH	 = 
OBJSC	 = 
OBJSF	 = 
LIBBASE	 = libpetscsles
LOCDIR	 = src/sles/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
