# $Id: makefile,v 1.12 2000/08/17 04:52:33 bsmith Exp balay $ 

ALL:

LOCDIR	 = src/sles/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
