#requirespackage 'PETSC_HAVE_HIP'

SOURCEC	  =
SOURCEHIP = cupmcontext.hip.cpp
SOURCEF	  =
SOURCEH   =
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/objects/device/impls/cupm/hip/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

