
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = aobasic.c
SOURCEF  =
SOURCEH  = 
OBJSC    = aobasic.o
OBJSF    =
LIBBASE  = libpetscdm
DIRS     = 
MANSEC   = AO
LOCDIR   = src/dm/ao/impls/basic/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test

