
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = aobasic.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscdm
DIRS     = 
MANSEC   = AO
LOCDIR   = src/dm/ao/impls/basic/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

