-include ../../../../../petscdir.mk

MANSEC         = Mat
SUBMANSEC      = MatGraphOperations
BFORTSUBMANSEC = matcoarsen

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
