# $Id: makefile,v 1.2 2001/09/07 20:08:41 bsmith Exp bsmith $

#requireslanguage  CPP
#requiresscalar    real 
#requiresprecision double
#requirespackage   'PETSC_HAVE_CXX_NAMESPACE'

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = eobject.c
OBJSC    = eobject.o
SOURCEH  = ../../../../include/esi/petsc/object.h
LIBBASE  = libpetsc
MANSEC   = 
LOCDIR   = src/sys/src/esi


include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


