
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = slda.c
SOURCEF  =
SOURCEH  = slda.h
OBJSC    = slda.o
OBJSF    =
LIBBASE  = libpetsccontrib
MANSEC   = SemiLagrange
LOCDIR   = src/semiLagrange/impls/da/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
