-include ../../../../../../../petscdir.mk
#requiresdefine 'PETSC_HAVE_MPI_NEIGHBORHOOD_COLLECTIVES'

SOURCEH   =
SOURCEC   = sfneighbor.c
LIBBASE   = libpetscvec
DIRS      =
MANSEC    = Vec
SUBMANSEC = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

