-include ../../../../../../../petscdir.mk
#requiresdefine 'PETSC_HAVE_MPI_NEIGHBORHOOD_COLLECTIVES'

LIBBASE   = libpetscvec
MANSEC    = Vec
SUBMANSEC = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

