#requirespackage   'PETSC_HAVE_NOTWORKING'

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = virsaug.c
SOURCEF  =
SOURCEH  = virsaugimpl.h
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/vi/rsaug

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

