#requirespackage 'PETSC_HAVE_CUDA'
-include ../../../../../petscdir.mk

LIBBASE  = libpetscts
MANSEC   = TS
SUBMANSEC= LANDAU

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
