#requirespackage 'PETSC_HAVE_CUDA'
-include ../../../../../petscdir.mk

SOURCECU = landaucu.cu
LIBBASE  = libpetscts
MANSEC   = TS
SUBMANSEC= LANDAU

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
