
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = cheby.c 
SOURCEF  =
SOURCEH  = chebyshevimpl.h
OBJSC    = cheby.o 
OBJSF    =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/cheby/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
