
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = bcgs.c
SOURCEF  =
OBJSC    = bcgs.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = fbcgs ifbcgs
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/bcgs/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
