ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = snesrichardson.c
SOURCEF  =
SOURCEH  = snesrichardsonimpl.h
OBJSC    = snesrichardson.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/richardson/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
