ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = picard.c
SOURCEF  =
SOURCEH  = picard.h
OBJSC    = picard.o
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/picard/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
