-include ../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  =
SOURCEF90= somempifort.F90
SOURCEH  =
LIBBASE  = libpetscsys
MANSEC   = Sys
LOCDIR   = src/sys/mpiuni/fsrc/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


