-include ../../../../petscdir.mk

SOURCEC  = product.c productutils.c
SOURCEH  = ../../../../include/petscdmproduct.h ../../../../include/petsc/private/dmproductimpl.h
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPRODUCT

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
