-include ../../../../petscdir.mk

SOURCEC  = product.c productutils.c
SOURCEF  =
SOURCEH  = ../../../../include/petscdmproduct.h ../../../../include/petsc/private/dmproductimpl.h
DIRS     =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPRODUCT
LOCDIR   = src/dm/impls/product/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
