ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lmvm.c
SOURCEF  =
SOURCEH  = lmvm.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/unconstrained/impls/lmvm/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

