-include ../../../../petscdir.mk

SOURCEC  = forest.c
SOURCEF  =
SOURCEH  =
DIRS     = p4est tests tutorials
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMFOREST
LOCDIR   = src/dm/impls/forest/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
