
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pythonsnes.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
DIRS     =
LOCDIR   = src/snes/impls/python/
MANSEC   = SNES

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
