
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = pythonsnes.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pythonsnes.o
OBJSF    =
LIBBASE  = libpetscsnes
DIRS     = ftn-custom
LOCDIR   = src/snes/impls/python/
MANSEC   = SNES

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
