
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = asils.c #asfls.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = asils.o #asfls.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/complementarity/impls/asls/

include ${TAO_DIR}/conf/tao_base

