-include ../../../../../petscdir.mk

LIBBASE  = libpetscksp
DIRS     = fischer pod
LOCDIR   = src/ksp/ksp/guess/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
