
ALL: lib 

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC	  = verboseinfo.c
SOURCEF	  =
SOURCEH	  = 
MANSEC	  = Profiling
LIBBASE	  = libpetscsys
DIRS	  = 
LOCDIR	  = src/sys/verbose/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
