# $Id: makefile,v 1.15 1999/01/31 16:08:25 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = asm.c
SOURCEF  =
SOURCEH  = 
OBJSC    = asm.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/asm/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
