
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = morethuente.c
SOURCEF  = 
SOURCEH  = morethuente.h
OBJSC    = morethuente.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/tao/linesearch/impls/morethuente/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

