
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = morethuente.c
SOURCEF  = 
SOURCEH  = morethuente.h
LIBBASE  = libpetsctao
MANSEC   = 
LOCDIR   = src/tao/linesearch/impls/morethuente/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

