-include ../../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_KOKKOS'

LIBBASE       = libpetscvec
MANSEC        = Vec
SUBMANSEC     = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

