-include ../../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_KOKKOS'

MANSEC        = Vec
SUBMANSEC     = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk

