-include ../../../../../petscdir.mk
ALL: lib

LIBBASE  = libpetscdm
DIRS     = poly ptrimmed tensor point subspace sum
LOCDIR   = src/dm/dt/space/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
