-include ../../../../../petscdir.mk

LIBBASE  = libpetscdm
DIRS     = poly ptrimmed tensor point subspace sum wxy

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
