
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = unit.c
SOURCEF  = 
SOURCEH  = unit.h
OBJSC    = unit.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/linesearch/impls/unit/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

