-include ../../../../../petsckdir.mk

SOURCEC   = unit.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetsctao
MANSEC    = Tao
SUBMANSEC = TaoLineSearch
LOCDIR    = src/tao/linesearch/impls/unit/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

