-include ../../../../../petscdir.mk

SOURCEC   = unit.c
LIBBASE   = libpetsctao
MANSEC    = Tao
SUBMANSEC = TaoLineSearch

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

