# $Id: makefile,v 1.22 2001/04/29 15:15:36 bsmith Exp bsmith $ 

DIRS     = sda oberman fun3d lahaye libtfs
LOCDIR   = src/contrib/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test

