# $Id: makefile,v 1.9 1997/08/22 15:19:04 bsmith Exp balay $ 

CFLAGS   = 
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = sda
LOCDIR   = src/contrib/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

