# $Id: makefile,v 1.21 2001/04/10 19:37:32 bsmith Exp bsmith $ 

DIRS     = sda pc oberman fun3d lahaye libtfs
LOCDIR   = src/contrib/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test

