-include ../../../../../../petscdir.mk

SOURCEC  = brdn.c badbrdn.c
SOURCEH  = brdn.h
LIBBASE  = libpetscksp
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
