#!/usr/local/bin/tcsh
# $Id: addlinks,v 1.15 1998/11/12 16:25:00 balay Exp bsmith $ 
#
# Add the individual links for the PETSc shadow directory.  This script
# should be called from buildlinks.
#
#can be invoked independently as:
#addlinks /home/balay/petsc/ ./bmake/sun4_local 
#(to addlinks in /home/balay/petsc/bmake/sun4_local)
#
set shadowdir=$1
set petscdir=$2
set petscdir=`echo $petscdir | sed s%.%/home/bsmith/petsc%`
set shadowdir=`echo $petscdir | sed s%/home/bsmith/petsc%$shadowdir%`

if (! -e $shadowdir) then
  echo "mkdir $shadowdir"
  mkdir $shadowdir
  chgrp petsc $shadowdir
  chmod g+ws $shadowdir
endif

set allfiles=$petscdir/*
foreach file ($allfiles)

  set short=`echo $file | sed s%$petscdir/%$shadowdir/%` 
  if (! -e $short && -f $file ) then
    set dummy=`echo $file |egrep '(\.a$|\.o$|^PI|\.ln|l\.outa|mputil.mp_|core|\.map|\.log|gmon\.out|trashz|\.tmp|\.b$|\~|\#|\.so$|^so_locations)'`
    if ($dummy != $file) then
#       echo "ln -s $file $short"
       ln -s $file $short
    else      
       echo "rejecting $file"
    endif
  endif
end
