#!/usr/local/bin/expect -f
#
#  Simple PETSc MUD demon
#

#
#   Get the most recent petsc-maint added
# 
    set last_petsc_maint [exec ls /mcs/adm/request/petsc-maint/active | sort -n | tail -1]

#
#  Start up the MUD session
#
     spawn telnet wfg.mcs.anl.gov 7777
     expect "*if you have any problems.\r\n\r\n"

     set timeout 90
     send "@connect Petsc paxyjej \r"
     expect "* reading it.\r\n"
     puts "PETSc successfully connected"
     send "page Barry PETSc has connected\r"

     set timeout 60
#
#   Main loop, looks for certain text strings coming back from the MUD server.
#        eventually for each pattern we can call large sophisticated functions.
#
    while (1) {
#       puts "Waiting for text string"
       expect { 
                "* pages you.*\r\n" { 
#                                   puts $expect_out(buffer)
                                   scan $expect_out(buffer) "%s pages," swho  
#                                   puts "who: $swho"
                                   send "page $swho I have received your page\r"
                 } "* whispers to you, *\r\n" {
#                                   puts $expect_out(buffer)
                                   scan $expect_out(buffer) "%s whispers to you, %s\r\n" swho message
#                                   puts "who: $swho message: $message"
                                   send "mu $swho I have received your whisper\r" 
                 } "* pages,*\r\n" { 
#                                   puts $expect_out(buffer)
                                   scan $expect_out(buffer) "%s pages, %s\r\n" swho  message
#                                   puts "who: $swho message: $message"
                                   send "page $swho I have received your page\r"
                 } "* *to you*: *\r\n" { 
#                                   puts $expect_out(buffer)
                                   scan $expect_out(buffer) "%s \[to you\]: %s\r\n" swho  message
#                                   puts "who: $swho message: $message"
                                   send "\`$swho I acknowledge your message\r"
                 } "* blinks\r\n" { 
#                                   puts $expect_out(buffer)
                                   scan $expect_out(buffer) "%s blinks\r\n" swho
#                                   puts "who: $swho"
                                   send "say Welcome back,  $swho\r"
                 } "* arrives from the hallway.\r\n" { 
#                                   puts $expect_out(buffer)
                                   scan $expect_out(buffer) "%s arrives from the hallway.\r\n" swho
#                                   puts "who: $swho"
                                   send "\`$swho Welcome to PETSc Plaza\r"
                 } "*\r\n" { 
#                                   puts "Irrelevant message"
                 }
       }
#
#   Check petsc-maint, see if anything came in
#
       set last [exec ls /mcs/adm/request/petsc-maint/active | sort -n | tail -1]
       if {$last > $last_petsc_maint} {
          send "say Another pesky petsc-maint has arrived\r"
          set last_petsc_maint $last
          set subject [exec grep Subject: /mcs/adm/request/petsc-maint/active/$last]
          set from [exec grep From: /mcs/adm/request/petsc-maint/active/$last]
       }
    }

    send "@quit\r"
