#!/bin/csh
# $Id: buildbackup,v 1.13 1998/08/04 21:09:44 balay Exp balay $ 

# 
#  Makes a complete backup of PETSc src incase the PETSc disk is lost
#
# /mcs/tmp is used as we need app 100 meg for the tar file, and 
# it is safer to avoid disk contention in ~petsc.
# 
set BACKUPFILE=/mcs/tmp/PetscBackup-`date '+%a'`.tar
set LOGFILE=/ccsthome/petsc/userbackups/PetscBackup-`date '+%a'`.log
set XCLUDEFILE=/home/bsmith/petsc/maint/xcludebackup
set ZIPFILE=PetscBackup-`date '+%a'`.tar.gz
#
date  >& $LOGFILE
cd /home/bsmith/petsc
#make ACTION=clean tree
cd /home/bsmith/petsc/docs/tex
#make clean
#
# Delete the old backup files
#
find /ccsthome/petsc/userbackups -type f -name "PetscBackup-*" -mtime +1 -exec ls -l {} \; -exec rm -f {} \; >>& $LOGFILE
#
# Create a new backup file
#
cd /home/bsmith
tar cFFXf $XCLUDEFILE $BACKUPFILE petsc >>& $LOGFILE
cd /ccsthome/petsc/userbackups
gzip $BACKUPFILE >>& $LOGFILE
#
# Now Copy the backup file over to hsm and /ccsthome/petsc
#
rcp $BACKUPFILE.gz mcshsm:userbackups/ >>& $LOGFILE
cp  $BACKUPFILE.gz /ccsthome/petsc/userbackups >>& $LOGFILE
#
# Now Copy the backup file over to a remote site
#
cd /mcs/tmp
/home/bsmith/petsc/maint/autoftp  mss.ncsa.uiuc.edu barrys  put $ZIPFILE >>& $LOGFILE
/bin/rm -f $BACKUPFILE $BACKUPFILE.gz  >>& $LOGFILE
date  >>& $LOGFILE
#

