#!/bin/csh
# $Id: buildntdist,v 1.3 1997/11/13 17:45:23 balay Exp balay $ 
# 

if ($#argv == 1) then
  set version=$1
  echo "Building ~/petscnt$version.tar"
else
  set version=""
endif

/bin/rm -r -f /mcs/tmp/petscnt
cd /home/bsmith/petsc
make ACTION=clean tree

cd /home/bsmith
tar cFFXf /home/bsmith/petsc/maint/xclude ~/petscnt.tar petsc

cd /home/bsmith/petsc/src
tar cFFXf /home/bsmith/petsc/maint/xcludecblas ~/cblas.tar adic


mkdir /mcs/tmp/petscnt
cd /mcs/tmp/petscnt
tar xf ~/petscnt.tar

cd /mcs/tmp/petscnt/petsc/src
tar xf ~/cblas.tar
mv  adic blaslapack

cd /mcs/tmp/petscnt/petsc
rm -rf bin
find /mcs/tmp/petscnt -type f -name output -exec rm -rf {} \;
rm -rf include/finclude


cd /mcs/tmp/petscnt
chmod -R u+w petsc
/home/bsmith/petsc/maint/makecpp.tcl /mcs/tmp/petscnt/petsc

/bin/rm -f ~/petscnt.tar ~/cblas.tar
if ($#argv == 1) then
  mv petsc petsc$version
endif

tar cf ~/petscnt$version.tar petsc$version
/bin/rm -r -f /mcs/tmp/petscnt

gzip ~/petscnt$version.tar


