#! /bin/csh
# $Id: buildremotetest,v 1.50 1999/04/05 15:26:05 balay Exp balay $ 

# 
# Builds and transports the petsc.tar.gz file for remote 
# automatic testing.
#
#
# send copy off to UCLA, and NERSC for testing
#
cd /home/bsmith/petsc/maint
/bin/rm -f nightlylogs/ftp.log
echo "ftp logging: `date` " > nightlylogs/ftp.log
chmod 660 nightlylogs/ftp.log
builddist >>& /dev/null
/bin/date '+DATE: %m/%d/%y TIME: %H:%M:%S' >>& nightlylogs/ftp.log
autoftp eris.disturbed.net petsc put ~/petsc.tar.gz petsc.tar.gz >>& nightlylogs/ftp.log
#autoscp ~/petsc.tar.gz petsc@eris.disturbed.net:~/  >>& nightlylogs/ftp.log
/bin/date '+DATE: %m/%d/%y TIME: %H:%M:%S' >>& nightlylogs/ftp.log
#autoftp h4p.llnl.gov bsmith put ~/petsc.tar.gz petsc.tar.gz >>& nightlylogs/ftp.log
#/bin/date '+DATE: %m/%d/%y TIME: %H:%M:%S' >>& nightlylogs/ftp.log
#autoftp ursula.cs.msstate.edu curfman put ~/petsc.tar.gz petsc.tar.gz >>& nightlylogs/ftp.log
#/bin/date '+DATE: %m/%d/%y TIME: %H:%M:%S' >>& nightlylogs/ftp.log
#
#  Wait 6.5 hours then retrieve the results
#
echo sleeping 30000 >> nightlylogs/ftp.log
sleep 30000
echo done sleeping >> nightlylogs/ftp.log
/bin/date '+DATE: %m/%d/%y TIME: %H:%M:%S' >>& nightlylogs/ftp.log
autoftp eris.disturbed.net petsc get buildtest.log /home/bsmith/petsc/maint/nightlylogs/freebsd.log >>& nightlylogs/ftp.log
#autoscp  petsc@eris.disturbed.net:~/buildtest.log /home/bsmith/petsc/maint/nightlylogs/freebsd.log >>& nightlylogs/ftp.log
#/bin/date '+DATE: %m/%d/%y TIME: %H:%M:%S' >>& nightlylogs/ftp.log
#autoftp h4p.llnl.gov bsmith get buildtest.log /home/bsmith/petsc/maint/nightlylogs/build_t3d.log >>& nightlylogs/ftp.log
#/bin/date '+DATE: %m/%d/%y TIME: %H:%M:%S' >>& nightlylogs/ftp.log
#autoftp ursula.cs.msstate.edu curfman get buildtest.log /home/bsmith/petsc/maint/nightlylogs/build_linux.log >>& nightlylogs/ftp.log
#/bin/date '+DATE: %m/%d/%y TIME: %H:%M:%S' >>& nightlylogs/ftp.log

#chmod -f g+rw /home/bsmith/petsc/maint/nightlylogs/solaris.log /home/bsmith/petsc/maint/nightlylogs/t3d.log /home/bsmith/petsc/maint/nightlylogs/linux.log >>& nightlylogs/ftp.log
echo "ftp logging complete: `date` " >> nightlylogs/ftp.log


