#! /bin/csh

set RSH=ssh
set RCP=scp
set dir=`dirname $0`
set ARCH=$1
set DASHN=-n
source $dir/buildtests/$1


echo "start build: $MACH $ARCH `date`"
$RSH $MACH $DASHN "$TMP/maint/newbuildtest $ARCH"
echo "end build: $MACH $ARCH  `date`"

