#! /bin/csh
# 
#  Makes distribution version of Petsc 2.0
#
echo "Have you rebuilt: manpages, wwwpages, latexpages,"
echo "by running make allmanpages"
echo "and the users manual (and intro) in .ps and .html"
echo "Deleted TAGS, TAGS_MAKEFILES, and TAGS_NO_EXAMPLES?"
#
pushd ~/petsc; make ACTION=clean tree; popd
#
/bin/rm -f ~/petsc.tar
#
tar cFFXf ~/petsc/maint/xclude ~/petsc.tar -C ~  petsc
#
cd /mcs/tmp
tar xf ~/petsc.tar
chmod -R u+w petsc
/bin/rm -f ~/petsc.tar
tar cf ~/petsc.tar petsc
/bin/rm -r -f /mcs/tmp/petsc
#
#  To test locally and build petsc.solid
#
# mv petsc.solid petsc.solid.old
# mv petsc petsc.good
# tar xf petsc.tar
# mv petsc petsc.solid
# do chmod g+wS petsc.solid
# do chmod -R g+w petsc.solid
# mv petsc.good petsc
# Run du on petsc.solid to make sure there is no garbage
# Test manpages and manual in petsc.solid
# Do builds in petsc.solid
# Remember you must set PETSC_DIR in .cshrc to 
# point to petsc.solid
#
# For local distribution, remember to make etags in petsc.solid





