#!/bin/csh
# $Id: buildntdist,v 1.47 2000/09/08 01:41:08 balay Exp balay $ 
# 

if ($#argv == 1) then
  set version=$1
  echo "Building ~/petscnt$version.tar.gz"
else
  set version=""
endif
#
# If /sandbox/petsc/tmp does not exist create it.
#
set tmpdir = "/sandbox/petsc/tmp"
if (! -d $tmpdir) then
  mkdir -p $tmpdir
endif
if (! -d $tmpdir) then
  echo 'Cannot create $tmpdir. Exiting..'
endif


/bin/rm -r -f $tmpdir/petscnt
/bin/rm -f $tmpdir/petscnt.tar
setenv PETSC_DIR /home/bsmith/petsc
cd /home/bsmith/petsc
make ACTION=clean tree

cd /home/bsmith
/bin/tar cFFXf /home/bsmith/petsc/maint/xclude $tmpdir/petscnt.tar petsc

#
#   Gets the C version of BLAS and LAPACK (these are excluded by the 
#   regular PETSc distribution hence we need to tar them up seperately
#
cd /home/bsmith/petsc/src
/bin/tar cFFXf /home/bsmith/petsc/maint/xcludecblas $tmpdir/cblas.tar blaslapack


mkdir $tmpdir/petscnt
cd $tmpdir/petscnt
/bin/tar xf $tmpdir/petscnt.tar

cd $tmpdir/petscnt/petsc/src
/bin/tar xf $tmpdir/cblas.tar

cd $tmpdir/petscnt/petsc
/bin/rm -rf bin
find $tmpdir/petscnt -type d -name output -exec /bin/rm -rf {} \;
/bin/rm -rf bmake/alpha* bmake/sun4* bmake/solaris* bmake/hpux*
/bin/rm -rf bmake/paragon* bmake/rs6000* bmake/freebsd* bmake/linux*
/bin/rm -rf bmake/win32_cygnus_gnu bmake/t3d* bmake/t3e* bmake/IRIX* bmake/i386*
/bin/rm -rf bmake/ascired* bmake/beos* bmake/mac-x*
/bin/rm -f  bmake/common. bmake/common 
/bin/rm -rf src/blaslapack/examples 
#
# Eliminate the '#requirespackage' stuff
#
/bin/cp -f bmake/win32/req.mak src/mat/impls/rowbs/mpi/makefile
/bin/cp -f bmake/win32/req.mak src/mat/impls/rowbs/makefile
/bin/cp -f bmake/win32/req.mak src/mat/partition/impls/pmetis/makefile
#/bin/cp -f bmake/win32/req.mak src/sys/src/objects/ams/makefile
/bin/cp -f bmake/win32/req.mak src/sys/src/objects/ams/java/makefile
/bin/cp -f bmake/win32/req.mak src/sys/src/viewer/impls/socket/matlab/makefile
/bin/cp -f bmake/win32/req.mak src/sys/src/viewer/impls/ams/makefile
/bin/cp -f bmake/win32/req.mak src/sys/src/draw/impls/x/makefile
/bin/cp -f bmake/win32/req.mak src/sles/pc/impls/spai/makefile
/bin/cp -f bmake/win32/req.mak src/ts/impls/implicit/pvode/makefile
/bin/cp -f bmake/win32/req.mak src/sys/src/matlabengine/makefile
#
# patch up missing dirs
#
/bin/mkdir -p src/dm/usg ;/bin/cp -f bmake/win32/req.mak src/dm/usg/makefile
/bin/rm -rf src/contrib/*; /bin/cp -f bmake/win32/req.mak src/contrib/makefile

#
# Build the tag files
#
cd $tmpdir/petscnt/petsc
make etags etags_examples TAGSDIR=`pwd`
/bin/cp -f bmake/win32/makefile.dos makefile

cd $tmpdir/petscnt
chmod -R u+w petsc
/home/bsmith/petsc/maint/makecpp.tcl $tmpdir/petscnt/petsc

/bin/rm -f $tmpdir/petscnt.tar $tmpdir/cblas.tar


cd $tmpdir/petscnt
if ($#argv == 1) then
  mv petsc petsc$version
endif

/bin/tar cf $tmpdir/petscnt$version.tar petsc$version
cd ~/
/bin/rm -r -f $tmpdir/petscnt

gzip -f $tmpdir/petscnt$version.tar
/bin/cp $tmpdir/petscnt$version.tar.gz ~/
chmod ug+w ~/petscnt$version.tar.gz 
/bin/rm -f $tmpdir/petscnt$version.tar.gz
