#! /bin/csh
# $Id: buildlinks,v 1.26 1998/01/04 15:08:18 bsmith Exp balay $ 

#
# Builds PETSc shadow directory.  This is used in conjunction with addlinks.
#

set shadowdir=$1
set petscdir=/home/bsmith/petsc

#
# If Shadow dir does'nt exist, create one.
#
if ( ! -d $shadowdir ) then 
  echo Creating $shadowdir 
  mkdir -p $shadowdir 
  chgrp pdetools $shadowdir 
  chmod g+w $shadowdir 
  chmod g+s $shadowdir 
endif

cd $petscdir
#
#  remove all garabage from true petsc directory
#
# make ACTION=clean tree >>& /dev/null
#
find . \(  -name man -prune -o -name manualpages -prune \) \
        -o -type d -exec $petscdir/maint/addlinks $shadowdir \{\} \
         \; >>& /dev/null

#
# make links directly to docs/www
#
if (! -e $shadowdir/docs/manualpages) then
        ln -s $petscdir/docs/manualpages $shadowdir/docs/manualpages
endif
if (! -e $shadowdir/src/mat/examples/matrices) then
        ln -s $petscdir/src/mat/examples/matrices $shadowdir/src/mat/examples/matrices 
endif

