#!/usr/bin/env tclsh
# $Id: checknightly,v 1.58 2000/11/15 20:19:09 balay Exp balay $ 
#
# Crontab job that checks if the nightly runs have finished by 7:30 am,
# Checks if the remote jobs are done in the past 2days, and 
# recreates the etags
#

proc CheckNightlyBuilds { } {
    global  tmpfileid

    cd /home/bsmith/petsc/maint/nightlylogs
    set tmp [catch {glob examples_*} files ]
    if { $tmp !=0 } {
        return 0
    }
    
    set machines {ico08 fire denali ico09 lava gaea guido rock }
    foreach machine $machines {
        if { [ string first $machine $files ] < 0 } { #file dos'nt exist
            set mesg "No build on: $machine"
            puts $tmpfileid $mesg
        }
    }

    # check the logfiles of remote builds:
    
    set day(Sun) Sat
    set day(Mon) Sun
    set day(Tue) Mon
    set day(Wed) Tue
    set day(Thu) Wed
    set day(Fri) Thu
    set day(Sat) Fri
    set today [exec date +%a ]
    
     set files {freebsd.log}
     foreach file $files {
         if { [file exists $file ] == 0 } {
             set mesg "$file: File does not exist"
             puts $tmpfileid  $mesg
             continue
         }
         set fileid [ open $file r ]
         if { [gets $fileid line ]< 0 } {
         set mesg "$file: File does not exist"
             puts $tmpfileid $mesg
             close $fileid
             continue
         }
         close $fileid
         if { [ string first $today $line] < 0  && [ string first $day($today) $line ] < 0 } {
             set mesg "**out of date logfile: $file **"
         puts $tmpfileid $mesg
             puts $tmpfileid $line
         }
    }
}

proc CheckFortranAutoMakefile { } {
    global  tmpfileid
    
    set files [ glob /home/bsmith/petsc/src/fortran/auto/*.c ]
    
    set cfiles ""
    set ofiles ""
    foreach file $files {
        set filename [ file tail $file ]
        lappend cfiles $filename
        lappend ofiles  [file rootname $filename].o
        
    }
    
    # Check if the above files are mentioned in the makefile
    set makefileid [ open  /home/bsmith/petsc/src/fortran/auto/makefile r ]
    set makefilebuff [ read $makefileid ]
    close $makefileid
    
    foreach cfile $cfiles {
        if { [string first    $cfile $makefilebuff ] < 0 } {
            puts $tmpfileid "******** could'nt find $cfile in auto/makefile"
        }
    }
    foreach ofile $ofiles {
        if { [string first $ofile $makefilebuff ] < 0 } {
            puts $tmpfileid "******** could'nt find $ofile in auto/makefile"
        }
    }
    return 0
}



proc main { } {
    global  tmpfileid

    set tmpfile /tmp/junk1
    set tmpfileid [ open $tmpfile w ]

    #Check if all the nightlybuilds are done
    CheckNightlyBuilds

    # Check if the fortran/auto/makefile is consistant
    CheckFortranAutoMakefile

    # if errors send out a report to the petsc team
    close $tmpfileid
    if { [ file size $tmpfile] > 0} {
        exec /usr/ucb/mail -s "NIGHTLY BUILD PROBLEM"  balay < $tmpfile
    }
    exec /bin/rm -f $tmpfile

    # Build the TAGS files 
    cd /home/bsmith/petsc
    exec /usr/xpg4/bin/make alletags PETSC_DIR=/nfs/mcs-homes07/bsmith/petsc >>& /dev/null
    return 0
}
##########################################
main
