#!/usr/bin/env tclsh
# $Id: converttosingleprecision,v 1.8 1998/04/01 00:01:52 balay Exp balay $ 
#
#   For a source file, takes a list of function names
# and replaces then with functionname_Single
#
#  The list of functionames is the first argument to
# the routine. The source code to change is the second
# argument.
#

##################################################
####                 main()                  #####    
##################################################

proc main { } {
    global argc argv

    if { $argc !=2 } {
        puts stderr "Insufficient arguments"
        exit
    }
    set tokenfilename  [lindex $argv 0]
    set sourcefilename [lindex $argv 1]
    set suffix _Single

    set head [string range $sourcefilename 0 0]
    if { $head != "s" } {
        puts stderr "Filename does not begin with s $sourcefilename"
        exit
    } else {
        set sourcefilename [string range $sourcefilename 1 end]
    }

    # Open the token file and read in the tokens
    set tokenfileid [ open $tokenfilename r ]
    set tokenfilebuff [ read $tokenfileid ]

    set tokenlist ""
    set replacelist ""
    foreach tokenline [ split $tokenfilebuff \n ] {
        set tmp [ string trim $tokenline]
        if { $tmp == {} } continue
        set oldtoken [lindex $tmp 0]
        set newtoken [lindex $tmp 1]
        if { $newtoken == {} } { 
            lappend tokenlist $oldtoken 
        } else {
            set tmplist {}
            lappend tmplist $oldtoken
            lappend tmplist $newtoken
            lappend replacelist $tmplist
        }
    }
    close $tokenfileid

    # Now open the source file where the tokens need to be replaced
    set sourcefileid [ open $sourcefilename r ]
    set sourcefilebuff [ read $sourcefileid ]
    close $sourcefileid

    # Now replace the tokens in the sourcefile with the new values
    # Note: This is done separately so that word boundary checks can be made
    foreach token $tokenlist {
        regsub -all (\[\ \n\t\,\(\)\"\;\*\])($token)(\[\ \n\t\,\(\)\"\;\*\]) \
                $sourcefilebuff \\1\\2$suffix\\3 sourcefilebuff
    }
    # Now replace the replacelist
    foreach tmplist $replacelist {
        set oldtoken  [lindex $tmplist 0]
        set newtoken  [lindex $tmplist 1]
        regsub -all $oldtoken $sourcefilebuff $newtoken sourcefilebuff
    }
     
    # Write back the modified buffer to a new file
    set outputsourcefilename  s$sourcefilename
    set sourcefileid [ open $outputsourcefilename w ]
    puts $sourcefileid $sourcefilebuff
    close $sourcefileid
    exec /bin/chmod ug+w $outputsourcefilename
    return 0
}
main

