#! /bin/csh
# $Id: copytestlog,v 1.4 2000/03/22 19:58:19 balay Exp $ 
# 
# Copies log files from failed builds.
#
source /home/bsmith/petsc/bmake/$1/buildtest

if ( ! -r /home/bsmith/petsc/maint/nightlylogs/examples_$ARCH.$BOPT.$MACH.log ) then
  rsh $MACH -n "cd $TMP;/bin/cp maint/examples_$ARCH.$BOPT.$MACH.log /home/bsmith/petsc/maint/nightlylogs";
endif
