#! /bin/csh
# $Id: copytestlog,v 1.4 2000/03/22 19:58:19 balay Exp $ 
# 
# Copies log files from failed builds.
#

set RCP='scp -q -B -oProtocol=1'
source /sandbox/petsc/petsc-test/bmake/$1/buildtest

if ( ! -r /home/petsc/logs/nightly/examples_$ARCH.$BOPT.$MACH.log ) then
  $RCP ${MACH}:$TMP/maint/examples_$ARCH.$BOPT.$MACH.log /home/petsc/logs/nightly
  chmod a+r /home/petsc/logs/nightly/examples_$ARCH.$BOPT.$MACH.log
endif

if ("${CONFIGURE}" == "yes") then
    if ( ! -r /home/petsc/logs/nightly/configure_$ARCH.$BOPT.$MACH.log ) then
        $RCP ${MACH}:$TMP/configure.log /home/petsc/logs/nightly/configure__$ARCH.$BOPT.$MACH.log
    endif
endif
