#! /bin/csh
# $Id: copytestlog,v 1.4 2000/03/22 19:58:19 balay Exp $ 
# 
# Copies log files from all nightly builds.
#

set dir=`dirname $0`
set day=`date | cut -f1 -d" "`

foreach CONF ($*)
  set SCP=scp
  source $dir/confignightly/${CONF}

  $SCP $USR@${MACH}:$LOC/build.log /home/petsc/logs/nightly/build_$CONF.$MACH.log &
  $SCP $USR@${MACH}:$LOC/examples.log /home/petsc/logs/nightly/examples_$CONF.$MACH.log &
  $SCP $USR@${MACH}:$LOC/configure.log /home/petsc/logs/nightly/configure__$CONF.$MACH.log &
end
sleep 300
chmod ugo+r /home/petsc/logs/nightly/*
wait
chmod ugo+r /home/petsc/logs/nightly/*
