#! /bin/csh
# $Id: copytestlog,v 1.4 2000/03/22 19:58:19 balay Exp $ 
# 
# Copies log files from failed builds.
#
source /sandbox/petsc/petsc-test/bmake/$1/buildtest

if ( ! -r /home/petsc/logs/nightly/examples_$ARCH.$BOPT.$MACH.log ) then
  rsh $MACH -n "cd $TMP;/bin/cp maint/examples_$ARCH.$BOPT.$MACH.log /home/petsc/logs/nightly";
endif
