#! /bin/csh
# $Id: buildtest,v 1.2 2001/10/19 16:20:25 petsc Exp $
#
# Example usage: killnightly solaris
#
#
set DATAFILESPATH=/home/petsc/datafiles
set NICE=''
set APPEND='>>&'
set RSH='ssh -1'
set RCP='scp -q -B -oProtocol=1'
set CONFIGURE='no'

set dir=`dirname $0`
source $dir/buildtests/$1

$RSH $MACH -n "zapall"

