#! /bin/csh
# $Id: buildtest,v 1.2 2001/10/19 16:20:25 petsc Exp $
#
# Example usage: killnightly solaris
#
#
set SSH=ssh
set ARCH=$1
set dir=`dirname $0`
source $dir/buildtests/$1

$SSH $MACH -n "zapall"

