#!/bin/bash
set -x

export LANG=en_US
export LC=C
export LC_ALL=C

RELEASE=2.3.1
PETSC_DIR=/home/balay/bk-rep/petsc-release-${RELEASE}

#automatically crankup the patchlevel
# ${PETSC_DIR}/maint/createpatch

#create the tarfile
${PETSC_DIR}/maint/builddist ${PETSC_DIR}

Now copy the generated tarfiles over to the website
PATCH_VERSION=`grep '^#define PETSC_VERSION_PATCH ' ${PETSC_DIR}/include/petscversion.h |tr -s ' ' | cut -d ' ' -f 3`
VERSION=${RELEASE}-p${PATCH_VERSION}
scp ~/petsc-${VERSION}.tar.gz petsc@harley.mcs.anl.gov:/nfs/ftp/pub/petsc/release-snapshots/
scp ~/petsc-lite-${VERSION}.tar.gz petsc@harley.mcs.anl.gov:/nfs/ftp/pub/petsc/release-snapshots/

# petsc.tar.gz/petsc-lite.tar.gz links are done manually
ssh petsc@harley.mcs.anl.gov " \
  cd /nfs/ftp/pub/petsc/; \
  /bin/rm -f petsc-${RELEASE}.tar.gz petsc-lite-${RELEASE}.tar.gz ; \
  /bin/ln -s release-snapshots/petsc-${VERSION}.tar.gz petsc-${RELEASE}.tar.gz; \
  /bin/ln -s release-snapshots/petsc-lite-${VERSION}.tar.gz petsc-lite-${RELEASE}.tar.gz"

# Update download/index.html as well
scp ${PETSC_DIR}/src/docs/website/download/index.html petsc@harley.mcs.anl.gov:/nfs/www-unix/petsc/petsc-as/download
