#! /bin/csh
# $Id: removelibs,v 1.12 1997/09/10 19:44:49 balay Exp balay $ 

# 
#  Removes PETSc libraries on some nightly build machines
#
rsh elvis -n /bin/rm -f "/tmp/petsc/lib/lib*/freebsd/*"
rsh violet -n /bin/rm -f "/tmp/petsc/lib/lib*/IRIX/*"
rsh maverick -n /bin/rm -f "/tmp/petsc/lib/lib*/sun4*/*.so.* /tmp/petsc/lib/lib*/sun4_uni/*"
/bin/rm -f /home/curfman/petsc/lib/lib*/alpha/* /home/petsc/petsc/lib/lib*/hpux/* /tmp/petsc/lib/lib*/solaris/*.so


