#! /bin/csh
# $Id: removelibs,v 1.14 1997/12/03 16:55:27 balay Exp balay $ 

# 
#  Removes PETSc libraries on some nightly build machines
#
rsh snowy -n /bin/rm -f "/tmp/petsc/lib/lib*/freebsd*/*"
rsh maple -n /bin/rm -f "/tmp/petsc/lib/lib*/solaris/*"
rsh violet -n /bin/rm -f "/tmp/petsc/lib/lib*/IRIX/*"
rsh maverick -n /bin/rm -f "/tmp/petsc/lib/lib*/sun4*/*.so.* /tmp/petsc/lib/lib*/sun4_uni/*"
/bin/rm -f /home/curfman/petsc/lib/lib*/alpha/*  /home/balay/petsc/lib/lib*/*/* /home/petsc/petsc/lib/lib*/hpux/* /tmp/petsc/lib/lib*/solaris/*.so


