#! /bin/csh

# usage startnightly test1 test2 ...


set dir=`dirname $0`
set pdir=`dirname $dir`
set day=`date | cut -f1 -d" "`

foreach CONF ($*)
  set SSH=ssh
  set SCP=scp
  set DASHN=-n
  set MERCURIAL=yes
  source $dir/confignightly/${CONF}

  echo "start build at `date`:$SSH $USR@$MACH $DASHN $LOC/maint/buildtest $CONF" 
  if ("${MERCURIAL}" == "yes") then
    $SSH $USR@$MACH $DASHN "cd $LOC ; hg revert; hg pull; hg update; $LOC/maint/buildtest $CONF" &
  else
    rsync -e ssh -az --delete  $pdir/ ${USR}@${MACH}:${LOC}
    $SSH $USR@$MACH $DASHN "cd $LOC; $LOC/maint/buildtest $CONF" &
  endif
  sleep 120 # perhaps ease the nfs load
end
wait
