#! /bin/csh

# usage startnightly test1 test2 ...


set dir=`dirname $0`
set day=`date | cut -f1 -d" "`

foreach CONF ($*)
  set SSH=ssh
  set SCP=scp
  set DASHN=-n
  source $dir/confignightly/${CONF}

  echo "start build at `date`:$SSH $USR@$MACH $DASHN $LOC/maint/buildtest $CONF" 
  $SSH $USR@$MACH $DASHN "cd $LOC ; bk -r unedit; bk pull; $LOC/maint/buildtest $CONF" &
  sleep 300 # perhaps ease the load on petsc.bkbits.net by spacing the builds
end
wait
