#! /bin/csh
# $Id: steal,v 1.8 1999/02/09 00:24:41 balay Exp balay $ 

# 
# steals a lock from one person to another.
#
setenv victim `ls -ld $1 | cut -f4 -d" "`
set dirname = `pwd`
set basename = `basename $dirname`
set newname  = /home/bsmith/petsc/maint/stolen/${basename}_$1
/bin/mv $1 $newname
rcs -u $1 
/usr/local/bin/co -l $1
/bin/cp $newname $1
/usr/local/bin/ci -u $1
/usr/local/bin/co -l $1
chmod g+w $newname
