#! /bin/sh
# $Id: torcsl,v 1.8 2000/02/14 22:48:24 bsmith Exp bsmith $ 

# 
# torcs full-file-name [ full-file-name .... ]
#
for file in $* ; do 
 echo "Initial Version" | rcs -i -agropp,bsmith,curfman,balay,kaushik,buschelm -L $file 
 /usr/local/bin/ci -l $file 
done

