#! /bin/sh
# $Id: torcs,v 1.6 2000/06/21 15:47:46 balay Exp balay $ 

# 
# torcs full-file-name [ full-file-name .... ]
#
for file in $* ; do 
 echo "Initial Version" | rcs -i -agropp,bsmith,curfman,balay,kaushik,buschelm -L $file 
 /usr/local/bin/ci  -u $file 
done

