#! /bin/sh
# $Id: torcsl,v 1.9 2001/03/29 15:41:46 bsmith Exp balay $ 

# 
# torcs full-file-name [ full-file-name .... ]
#
for file in $* ; do 
 echo "Initial Version" | rcs -i -agropp,bsmith,curfman,balay,kaushik,buschelm -L $file 
 ci -l $file 
done

