#!/bin/sh

#
# This script updates the petsc-bk repository in terra:/sandbox/petsc/petsc-test
# This repository is used for nightly builds using rsync command
# rsync -C -r terra:/sandbox/petsc/petsc-test /sandbox/petsc
#

export PETSC_ARCH=linux
export PETSC_DIR=/sandbox/petsc/petsc-test 
echo "*************************************************************************************"
cd  /sandbox/petsc/petsc-test/python/BuildSystem
bk pull
bk -r co -q
echo "*************************************************************************************"
cd /sandbox/petsc/petsc-test
bk pull
bk -r co -q
echo "*************************************************************************************"
make allfortranstubs
echo "*************************************************************************************"
