# $Id: makefile,v 1.11 2001/08/22 18:02:27 balay Exp $ 

ALL:

LOCDIR   = src/dm/ao/examples/
DIRS     = tests tutorials
MANSEC   = DA

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
