# $Id: makefile,v 1.13 1997/09/10 19:07:16 balay Exp balay $ 

ALL:

CFLAGS	        = $(CPPFLAGS) -D__SDIR__='"$(LOCDIR)"'
FFLAGS	        = 
SOURCEC	        = 
SOURCEF	        =
SOURCEH	        =
OBJSC	        =
OBJSF	        = 
LIBBASE	        = libpetscvec
LOCDIR          = src/ao/examples/
DIRS            = tests tutorials

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base
