
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sorqn.c
SOURCEF  =
SOURCEH  =
OBJSC    = $(SOURCEC:.c=.o)
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/sorqn

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

