#! /bin/csh

set MACH=blaze
set USR=petsc
set LOC=/sandbox/petsc/petsc-dev
set TAO_LOC=/sandbox/petsc/tao-devel
set CONF=solaris-gnu

if ($day == Sun || $day == Wed || $day == Sat) then
  set CONF=solaris-uni
else if ($day == Thu || $day == Fri) then
  set CONF=solaris-64
endif
