#! /bin/csh
#
set MACH=icrunch
set USR=petsc
set LOC=/sandbox/petsc/petsc-dev
set CONF=macosx-gnu

if ($day == Sun || $day == Wed || $day == Sat) then
  set CONF=macox-gnu
else if ($day == Thu || $day == Mon || $day == Fri) then
  set CONF=macos-ibm
endif
