
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = cgne.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/cg/cgne/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
