
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lgmres.c
SOURCEF  = 
SOURCEH  = lgmresimpl.h
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/gmres/lgmres/
DIRS     =

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
