
LOCDIR	 = src/sys/classes/viewer/examples/
LIBBASE	 = libpetscsys
DIRS	 = tutorials tests

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
