# $Id: makefile,v 1.6 1999/01/12 23:14:15 bsmith Exp balay $ 

ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = mal.c   mem.c   mtr.c
SOURCEF	  =
SOURCEH	  = 
OBJSC	  = mal.o   mem.o   mtr.o
OBJSF	  =
MANSEC	  = Sys
LIBBASE	  = libpetsc
DIRS	  = 
LOCDIR	  = src/sys/src/memory/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base




