# $Id: makefile,v 1.9 2001/08/22 17:59:26 balay Exp $ 

ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = mal.c   mem.c   mtr.c
SOURCEF	  =
SOURCEH	  = 
OBJSC	  = mal.o   mem.o   mtr.o
OBJSF	  =
MANSEC	  = Sys
LIBBASE	  = libpetsc
DIRS	  = 
LOCDIR	  = src/sys/src/memory/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test



