
ALL: lib
CFLAGS   =
FFLAGS   =
LIBBASE  = libpetscksp
DIRS     = nn
LOCDIR   = src/ksp/pc/impls/is/
SOURCEC  = pcis.c
SOURCEH  = pcis.h
MANSEC   = PC

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
