-include ../../../petscdir.mk

LOCDIR          = src/dm/tests/
EXAMPLESMATLAB  = ex12.m
MANSEC          = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
