ALL: lib 
ITOOLSDIR = ../../../

CFLAGS   = $(OPT) -I$(ITOOLSDIR) -I$(ITOOLSDIR)/include -I../../
 
SOURCEC  = bcgs.c
WSOURCEC = 
SOURCEF  =
OBJSC    = bcgs.o
WOBJS    = 
OBJSF    =
LIBBASE  = libpetscksp
LOCAL_INCLUDE = 
