ALL: lib 
ITOOLSDIR = ../../../../

CFLAGS   = $(OPT) $(INCLUDEDIRS) $(CONF)  \
           -I$(ITOOLSDIR)/pinclude -I../../
SOURCEC  = bcgs.c
WSOURCEC = 
SOURCEF  =
OBJSC    = bcgs.o
WOBJS    = 
OBJSF    =
LIBBASE  = libpetscksp
LINCLUDE = 

runexamples:

include $(ITOOLSDIR)/bmake/$(PARCH)/$(PARCH)
