
#requirespackage 'PETSC_HAVE_OPENGL'

ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  = ${OPENGL_INCLUDE}
SOURCEC   = openglops.c
SOURCEF   =
SOURCEH   =
MANSEC    = Sys
SUBMANSEC = Draw
LIBBASE   = libpetscsys
DIRS      =
LOCDIR   = src/sys/classes/draw/impls/opengl/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
