
ALL: lib

SOURCEH  = ../../include/petsc-private/taoimpl.h ../../include/taolinesearchimpl.h
DIRS     = interface util unconstrained constrained bound complementarity linesearch matrix leastsquares pde_constrained
LOCDIR   = src/tao/

include ${PETSC_DIR}/lib/petsc-conf/variables
include ${PETSC_DIR}/lib/petsc-conf/rules
include ${PETSC_DIR}/lib/petsc-conf/test
