
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = lrc.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscmat
DIRS     = 
LOCDIR   = src/mat/impls/lrc/
MANSEC   = Mat

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

