-include ../../../../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pythonmat.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
DIRS     =
LOCDIR   = src/mat/impls/python/
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
