
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = pythonmat.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pythonmat.o
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = ftn-custom
LOCDIR   = src/mat/impls/python/
MANSEC   = Mat

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
