-include ../../../petscdir.mk

MANSEC          = DM
CLEANFILES      = output_file output_file.info swarm_ex[1-3]

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

ex13f90: ex13f90aux.o
