-include ../../../petscdir.mk
#requirespackage  'PETSC_HAVE_SSL'
#requiresdefine   'PETSC_USE_SOCKET_VIEWER'

SOURCEC	  = client.c google.c box.c textbelt.c globus.c tellmycell.c
SOURCEH	  = ../../../include/petscwebclient.h
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = tutorials

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test



