-include ../../../petscdir.mk
#requirespackage  'PETSC_HAVE_SSL'
#requiresdefine   'PETSC_USE_SOCKET_VIEWER'

MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = tutorials

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc



