-include ../../../../../petscdir.mk

CFLAGS    = -Dhello=hello2
LIBBASE   = libpetscsys
MANSEC    = Sys
SUBMANSEC = Viewer

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
