
ALL: lib

CFLAGS    = -Dhello=hello2
FFLAGS    =
SOURCEC   = view.c flush.c viewregall.c viewreg.c viewa.c dlregispetsc.c viewers.c dupl.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscsys
MANSEC    = Sys
SUBMANSEC = Viewer
LOCDIR    = src/sys/classes/viewer/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
