

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lmvm.c
SOURCEF  =
SOURCEH  = lmvm.h
LIBBASE  = libpetscmat
MANSEC   = Mat
DIRS     =
LOCDIR   = src/mat/impls/lmvm/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
