
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dmshell.c
SOURCEF  =
SOURCEH  = ../../../../include/petscdmshell.h
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMSHELL
LOCDIR   = src/dm/impls/shell

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
