-include ../../../../petscdir.mk

SOURCEC  = dmshell.c
SOURCEH  = ../../../../include/petscdmshell.h
LIBBASE  = libpetscdm
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
