-include ../../../../petscdir.mk

SOURCEC  = dmshell.c
SOURCEF  =
SOURCEH  = ../../../../include/petscdmshell.h
LIBBASE  = libpetscdm
MANSEC   = DM
LOCDIR   = src/dm/impls/shell/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
