
#requirespackage 'PETSC_USING_F90'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zbagf.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    = 
LIBBASE  = libpetsc
LOCDIR   = src/sys/bag/f90-custom/


include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test


