-include ../../../../../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fcg.c
SOURCEF  =
SOURCEH  = fcgimpl.h
LIBBASE  = libpetscksp
DIRS     = pipefcg
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/fcg/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
