
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fcg.c
SOURCEF  =
SOURCEH  = fcgimpl.h
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/fcg/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
