-include ../../../../../petscdir.mk

SOURCEC  = fcg.c
SOURCEF  =
SOURCEH  = fcgimpl.h
LIBBASE  = libpetscksp
DIRS     = pipefcg
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
