# $Id: makefile,v 1.19 1998/03/19 02:04:43 balay Exp balay $

ALL: lib

SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = general stride block
LOCDIR   = src/is/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

