-include ../../../../../../petscdir.mk

SOURCECXX = hostdevice.cxx hostcontext.cxx
SOURCEH   = hostdevice.hpp
MANSEC	  = Sys
LIBBASE	  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

