
ALL:

LOCDIR	 = src/tao/leastsquares/examples/
DIRS	 = tutorials matlab


include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
