-include ../../../../petscdir.mk

SOURCEC  = qn.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

