-include ../../petscdir.mk
ALL: lib

SOURCEH  =
DIRS     = pc ksp f90-mod
LOCDIR   = src/ksp/
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
