-include ../../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zadaptdspf.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetsts
LOCDIR   = src/ts/adapt/impls/dsp/ftn-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
