# $Id: makefile,v 1.5 2001/08/22 18:01:44 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fgmres.c modpcf.c
SOURCEH  = fgmresp.h
SOURCEF  = 
OBJSC    = fgmres.o modpcf.o
OBJSF    = 
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/fgmres/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


