
SOURCEC  = taosolver.c taosolver_fg.c taosolverregi.c taosolver_hj.c taosolver_bounds.c dlregistao.c fdiff.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/interface/


include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
