-include ../../../../../../petscdir.mk

SOURCEC  = fischer.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/guess/impls/fischer/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
