
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gl.c
SOURCEF  =
SOURCEH  = gl.h
OBJSC    = gl.o
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/impls/implicit/gl/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test

