
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gl.c gladapt.c
SOURCEF  =
SOURCEH  = gl.h
OBJSC    = $(SOURCEC:.c=.o)
OBJSF    =
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/impls/implicit/gl/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test

