
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gl.c gladapt.c
SOURCEF  =
SOURCEH  = gl.h
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/impls/implicit/gl/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

