
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/dm/examples/tests/
EXAMPLESC       = ex1.c ex2.c ex3.c ex4.c ex5.c ex6.c ex7.c\
                  ex11.c ex12.c ex12.m ex13.c ex14.c ex15.c ex16.c ex17.c ex19.c ex20.c \
	          ex21.c ex22.c ex23.c ex24.c ex25.c ex26.c ex27.c ex28.c ex30.c \
	          ex31.c ex32.c ex34.c ex36.c ex37.c ex38.c ex39.c ex40.c ex41.c \
	          ex42.c ex43.c ex44.c ex45.c
EXAMPLESF       =
MANSEC          = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

ex1: ex1.o   chkopts
	-${CLINKER} -o ex1 ex1.o  ${PETSC_DM_LIB}
	${RM} -f ex1.o

ex2: ex2.o  chkopts
	-${CLINKER} -o ex2 ex2.o  ${PETSC_DM_LIB}
	${RM} -f ex2.o

ex3: ex3.o  chkopts
	-${CLINKER} -o ex3 ex3.o  ${PETSC_DM_LIB}
	${RM} -f ex3.o

ex4: ex4.o   chkopts
	-${CLINKER} -o ex4 ex4.o  ${PETSC_DM_LIB}
	${RM} -f ex4.o

ex5: ex5.o  chkopts
	-${CLINKER} -o ex5 ex5.o  ${PETSC_DM_LIB}
	${RM} -f ex5.o

ex6: ex6.o   chkopts
	-${CLINKER} -o ex6 ex6.o  ${PETSC_DM_LIB}
	${RM} -f ex6.o

ex7: ex7.o   chkopts
	-${CLINKER} -o ex7 ex7.o  ${PETSC_DM_LIB}
	${RM} -f ex7.o

ex11: ex11.o   chkopts
	-${CLINKER} -o ex11 ex11.o  ${PETSC_DM_LIB}
	${RM} -f ex11.o

ex12: ex12.o   chkopts
	-${CLINKER} -o ex12 ex12.o  ${PETSC_DM_LIB}
	${RM} -f ex12.o

ex13: ex13.o   chkopts
	-${CLINKER} -o ex13 ex13.o  ${PETSC_DM_LIB}
	${RM} -f ex13.o

ex14: ex14.o   chkopts
	-${CLINKER} -o ex14 ex14.o  ${PETSC_DM_LIB}
	${RM} -f ex14.o

ex15: ex15.o   chkopts
	-${CLINKER} -o ex15 ex15.o  ${PETSC_DM_LIB}
	${RM} -f ex15.o

ex16: ex16.o   chkopts
	-${CLINKER} -o ex16 ex16.o  ${PETSC_DM_LIB}
	${RM} -f ex16.o

ex17: ex17.o   chkopts
	-${CLINKER} -o ex17 ex17.o  ${PETSC_DM_LIB}
	${RM} -f ex17.o

ex18: ex18.o   chkopts
	-${CLINKER} -o ex18 ex18.o  ${PETSC_DM_LIB}
	${RM} -f ex18.o

ex19: ex19.o   chkopts
	-${CLINKER} -o ex19 ex19.o  ${PETSC_DM_LIB}
	${RM} -f ex19.o

ex20: ex20.o   chkopts
	-${CLINKER} -o ex20 ex20.o  ${PETSC_DM_LIB}
	${RM} -f ex20.o

ex21: ex21.o   chkopts
	-${CLINKER} -o ex21 ex21.o  ${PETSC_DM_LIB}
	${RM} -f ex21.o

ex22: ex22.o   chkopts
	-${CLINKER} -o ex22 ex22.o  ${PETSC_DM_LIB}
	${RM} -f ex22.o

ex23: ex23.o   chkopts
	-${CLINKER} -o ex23 ex23.o  ${PETSC_DM_LIB}
	${RM} -f ex23.o

ex24: ex24.o   chkopts
	-${CLINKER} -o ex24 ex24.o  ${PETSC_DM_LIB}
	${RM} -f ex24.o

ex25: ex25.o   chkopts
	-${CLINKER} -o ex25 ex25.o  ${PETSC_DM_LIB}
	${RM} -f ex25.o

ex26: ex26.o   chkopts
	-${CLINKER} -o ex26 ex26.o  ${PETSC_DM_LIB}
	${RM} -f ex26.o

ex27: ex27.o   chkopts
	-${CLINKER} -o ex27 ex27.o  ${PETSC_DM_LIB}
	${RM} -f ex27.o

ex28: ex28.o   chkopts
	-${CLINKER} -o ex28 ex28.o  ${PETSC_DM_LIB}
	${RM} -f ex28.o

ex29: ex29.o   chkopts
	-${CLINKER} -o ex29 ex29.o  ${PETSC_DM_LIB}
	${RM} -f ex29.o

ex30: ex30.o   chkopts
	-${CLINKER} -o ex30 ex30.o  ${PETSC_DM_LIB}
	${RM} -f ex30.o

ex31: ex31.o   chkopts
	-${CLINKER} -o ex31 ex31.o  ${PETSC_DM_LIB}
	${RM} -f ex31.o

ex32: ex32.o   chkopts
	-${CLINKER} -o ex32 ex32.o  ${PETSC_DM_LIB}
	${RM} -f ex32.o
ex33: ex33.o   chkopts
	-${CLINKER} -o ex33 ex33.o  ${PETSC_DM_LIB}
	${RM} -f ex33.o
ex34: ex34.o   chkopts
	-${CLINKER} -o ex34 ex34.o  ${PETSC_DM_LIB}
	${RM} -f ex34.o
ex35: ex35.o   chkopts
	-${CLINKER} -o ex35 ex35.o  ${PETSC_DM_LIB}
	${RM} -f ex35.o
ex36: ex36.o   chkopts
	-${CLINKER} -o ex36 ex36.o  ${PETSC_DM_LIB}
	${RM} -f ex36.o
ex37: ex37.o   chkopts
	-${CLINKER} -o ex37 ex37.o  ${PETSC_DM_LIB}
	${RM} -f ex37.o
ex38:ex38.o   chkopts
	-${CLINKER} -o ex38 ex38.o  ${PETSC_DM_LIB}
	${RM} -f ex38.o
ex39:ex39.o   chkopts
	-${CLINKER} -o ex39 ex39.o  ${PETSC_DM_LIB}
	${RM} -f ex39.o
ex40:ex40.o   chkopts
	-${CLINKER} -o ex40 ex40.o  ${PETSC_DM_LIB}
	${RM} -f ex40.o
ex41:ex41.o   chkopts
	-${CLINKER} -o ex41 ex41.o  ${PETSC_DM_LIB}
	${RM} -f ex41.o
ex42:ex42.o   chkopts
	-${CLINKER} -o ex42 ex42.o  ${PETSC_DM_LIB}
	${RM} -f ex42.o
ex43:ex43.o   chkopts
	-${CLINKER} -o ex43 ex43.o  ${PETSC_DM_LIB}
	${RM} -f ex43.o
ex44:ex44.o   chkopts
	-${CLINKER} -o ex44 ex44.o  ${PETSC_DM_LIB}
	${RM} -f ex44.o
ex45:ex45.o   chkopts
	-${CLINKER} -o ex45 ex45.o  ${PETSC_DM_LIB}
	${RM} -f ex45.o

include ${PETSC_DIR}/lib/petsc/conf/test
