-include ../../../../../petscdir.mk
#requirespackage        'PETSC_HAVE_FORTRAN'

SOURCEC = ztaolinesearchf.c
LIBBASE = libpetsctao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test 
