#requirespackage        'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS=
FFLAGS=
SOURCEC=ztaolinesearchf.c
SOURCEF=
SOURCEH=
DIR=
LIBBASE=libpetsctao
LOCDIR=src/tao/linesearch/interface/ftn-custom/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test 
