-include ../../../../../petscdir.mk

SOURCEC   = dualspace.c
SOURCEF   =
SOURCEH   =
DIRS      =
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = DUALSPACE
LOCDIR    = src/dm/dt/dualspace/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
