# $Id: makefile,v 1.1 1999/03/30 22:50:22 bsmith Exp bsmith $ 

CFLAGS   = 
FFLAGS   = 
SOURCEC  = agglom.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/contrib/agglom/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

