eagle>grep "\.uk " petsc_ftp_retrivials_to_May_18_1997 | wc
      53     901    6275
eagle>grep "\.fr " petsc_ftp_retrivials_to_May_18_1997 | wc
      98    1666   11730
eagle>grep "\.de " petsc_ftp_retrivials_to_May_18_1997 | wc
     149    2533   18912
eagle>grep "\.edu " petsc_ftp_retrivials_to_May_18_1997 | wc
     409    6953   48428
eagle>grep "\.mil " petsc_ftp_retrivials_to_May_18_1997 | wc
      19     323    2318
eagle>grep "\.gov " petsc_ftp_retrivials_to_May_18_1997 | wc
      98    1666   11361
eagle>grep "\.com " petsc_ftp_retrivials_to_May_18_1997 | wc
     176    2992   21146
eagle>grep "\.au " petsc_ftp_retrivials_to_May_18_1997 | wc
      22     374    2782
eagle>grep "\.ca " petsc_ftp_retrivials_to_May_18_1997 | wc
      58     986    6901
