-include ../../../../../../petscdir.mk
#requiresdefine 'PETSC_USE_WINDOWS_GRAPHICS'

SOURCEC   = win32draw.c
SOURCEF   =
SOURCEH   = win32draw.h
MANSEC    = Sys
SUBMANSEC = Draw
LIBBASE   = libpetscsys
DIRS      =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
