-include ../../../../../../petscdir.mk
#requiresdefine 'PETSC_USE_WINDOWS_GRAPHICS'

MANSEC    = Sys
SUBMANSEC = Draw

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
