
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = zmesh.c
OBJSC    = zmesh.o
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/mesh/ftn-custom/
include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
