# $Id: makefile,v 1.15 2001/08/22 17:58:57 balay Exp $ 



CFLAGS	        =
FFLAGS	        = 
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/sys/src/viewer/examples/tutorials/
EXAMPLESC       = 
MANSEC          = Viewer

include ${PETSC_DIR}/bmake/common/base

TESTEXAMPLES_2  = 
TESTEXAMPLES_4  = 

include ${PETSC_DIR}/bmake/common/test

