
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = pythonts.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pythonts.o
OBJSF    =
LIBBASE  = libpetscts
DIRS     =
LOCDIR   = src/ts/impls/python/
MANSEC   = TS

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
