# $Id: makefile,v 1.11 2000/08/17 04:53:03 bsmith Exp balay $ 

ALL:

LOCDIR	 = src/ts/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
