# $Id: makefile,v 1.8 1998/06/13 05:06:00 balay Exp balay $ 

ALL:

CFLAGS   = 
FFLAGS	 = 
SOURCEC	 = 
SOURCEF	 = 
SOURCEH	 = 
OBJSC	 = 
OBJSF	 = 
LIBBASE	 = libpetscts
LOCDIR	 = src/ts/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
