# $Id: makefile,v 1.10 1999/02/03 04:31:47 bsmith Exp bsmith $ 

ALL:

LOCDIR	 = src/ts/examples/
DIRS	 = tests tutorials

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
