
#requiresdefine 'PETSC_USING_F90'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ziscoloringf90.c
SOURCEF  = 
SOURCEH  = 
LIBBASE  = libpetscvec
LOCDIR   = src/vec/is/utils/f90-custom/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


