#requirespackage 'PETSC_HAVE_VECCUDA'

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vscatcuda.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/utils/veccuda/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

