ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = cartesian.c
SOURCEF  =
SOURCEH  =
OBJSC    = cartesian.o
OBJSF    =
LIBBASE  = libpetscdm
DIRS     =
MANSEC   = Mesh
LOCDIR   = src/dm/mesh/impls/cartesian/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
