-include ../../../petscdir.mk

SOURCEC	  = plog.c xmllogevent.c xmlviewer.c
SOURCEF	  =
SOURCEH	  = ../../../include/petsc/private/logimpl.h ../../../include/petsclog.h xmlviewer.h
MANSEC	  = Sys
SUBMANSEC = Profiling
LIBBASE	  = libpetscsys
DIRS	  = utils
LOCDIR	  = src/sys/logging/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
