-include ../../../petscdir.mk

SOURCEC	  = plog.c xmllogevent.c xmlviewer.c
MANSEC	  = Sys
SUBMANSEC = Profiling
LIBBASE	  = libpetscsys
DIRS	  = utils

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
