#requirespackage 'PETSC_HAVE_RAND'

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = rand.c
SOURCEF  =
SOURCEH  = 
OBJSC    = rand.o
OBJSF    =
LIBBASE  = libpetscsys
DIRS     = 
LOCDIR   = src/sys/random/impls/rand/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

