.PHONY:all
all:
	-${MAKE} -C binary-io
	-${MAKE} -C kspsolve
	-${MAKE} -C bratu2d
	-${MAKE} -C bratu3d
	-${MAKE} -C poisson2d
	-${MAKE} -C poisson3d
	-${MAKE} -C matfree
#	-${MAKE} -C wrap-swig
#	-${MAKE} -C wrap-f2py
