-include ../../../../../../petscdir.mk

SOURCEC  = pipegcr.c
SOURCEH  =
SOURCEF  =
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
