
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pipegcr.c
SOURCEH  =
SOURCEF  =
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/gcr/pipegcr/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
