-include ../../../../../../../petsckdir.mk
#requirespackage 'PETSC_HAVE_HIP'

SOURCEC  =
SOURCEHIP = sfhip.hip.cpp
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscvec
MANSEC   = PetscSF
LOCDIR   = src/vec/is/sf/impls/basic/hip
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
