#
ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS = 
SOURCEC  = coarsen.c scoarsen.c
SOURCEH  = 
OBJSC    = coarsen.o scoarsen.o
LIBBASE  = libpetscmat
LOCDIR   = src/mat/coarsen/
MANSEC   = MatOrderings
DIRS     = impls

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
