-include ../../../../../petscdir.mk

SOURCEC  = bqnk.c bqnkls.c bqnktr.c bqnktl.c
SOURCEH  = bqnk.h
LIBBASE  = libpetsctao
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

