
#requirespackage  'PETSC_HAVE_ESSL'
#requiresscalar    real
#requiresprecision double

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = essl.c
SOURCEF  = 
SOURCEH  =
OBJSC    = essl.o
OBJSF    = 
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
LOCDIR   = src/mat/impls/aij/seq/essl/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
