-include ../../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_ESSL'
#requiresscalar    real
#requiresprecision double

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = essl.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat
LOCDIR   = src/mat/impls/aij/seq/essl/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
