
ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS = -DTAO_LIB_DIR='"${TAO_LIB_DIR}"'
SOURCEC  = tao_util.c
SOURCEF  =
SOURCEH  = 
OBJSC    = tao_util.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = taosolver
DIRS     = 
EDIRS    = 
LOCDIR   = src/util/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

