
ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS =
SOURCEC  = tao_util.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetsctao
MANSEC   = Tao
DIRS     =
EDIRS    =
LOCDIR   = src/tao/util/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

