
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dm.c dmregall.c dmget.c
SOURCEF  = 
SOURCEH  = 
LIBBASE  = libpetscdm
MANSEC   = DM
LOCDIR   = src/dm/interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
