
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dm.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = dm.o
OBJSF    =
LIBBASE  = libpetscdm
MANSEC   = DA
LOCDIR   = src/dm/da/interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
