#requirespackage  'PETSC_HAVE_MOAB'
#requiresprecision double
#requiresscalar    real

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dmmoab.cxx
SOURCEF  =
SOURCEH  =
DIRS     = examples
LIBBASE  = libpetscdm
MANSEC   = DM
LOCDIR   = src/dm/impls/moab/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

