# $Id: makefile,v 1.3 1999/01/31 16:09:06 bsmith Exp bsmith $

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = bicg.c
SOURCEF  =
OBJSC    = bicg.o
OBJSF    =
LIBBASE  = libpetscsles
LOCDIR   = src/sles/ksp/impls/bicg/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
