# $Id: makefile,v 1.4 2000/08/17 04:52:32 bsmith Exp balay $

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = bicg.c
SOURCEF  =
OBJSC    = bicg.o
OBJSF    =
LIBBASE  = libpetscsles
LOCDIR   = src/sles/ksp/impls/bicg/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
