# $Id: makefile,v 1.30 1998/06/15 15:56:06 balay Exp $

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = bcgs.c
SOURCEF  =
OBJSC    = bcgs.o
OBJSF    =
LIBBASE  = libpetscsles
LOCDIR   = src/ksp/impls/bcgs/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
