ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bncg.c
SOURCEF  =
SOURCEH  = bncg.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/bound/impls/bncg/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

