PETSC_DIR = ../../..

ALL: lib

CFLAGS   = 
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = seq
LOCDIR   = src/is/impls/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base

