# $Id: makefile,v 1.7 1998/06/12 21:36:53 balay Exp balay $

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = basic
LOCDIR   = src/ao/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

