# $Id: makefile,v 1.4 1997/08/22 15:19:34 bsmith Exp bsmith $

ALL: lib

CFLAGS   = 
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = basic
LOCDIR   = src/ao/impls/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base

