

LANGUAGES =  c++

CFLAGS = ${BABEL_INCLUDE}

SIDLFILES = ${PETSC_DIR}/src/tops/tops.sidl ${SIDL}

parse-check:
	${BABEL} -R${CCA_REPO} --parse-check ${SIDLFILES}

#-------------------------------------------------------------------------------
clients: 
	for LANGUAGE in $(LANGUAGES); do \
		echo -e "\n### Building $$LANGUAGE client library."; \
		${BABEL} -R${CCA_REPO} --suppress-timestamp -c $$LANGUAGE -o ./client/$$LANGUAGE ${SIDLFILES} ; \
		cat client/$$LANGUAGE/babel.make | sed s/\\.cc/.o/g | sed s/\\.c/.o/g > client/$$LANGUAGE/makefile; \
		echo "include ${PETSC_DIR}/src/tops/makefile.rules" >> client/$$LANGUAGE/makefile; \
		$(OMAKE) -C client/$$LANGUAGE LANGUAGE=$$LANGUAGE libclient-$$LANGUAGE;\
	done
	touch $@

libclient-c: 
	-@${CC} -c ${CC_FLAGS} ${COPTFLAGS} ${CFLAGS} ${CCPPFLAGS}  *.cc
	-@${C_CC} -c ${C_CC_FLAGS} ${COPTFLAGS} ${CFLAGS} ${CCPPFLAGS}  *.c
	$(OMAKE)  LIBNAME=libclient-${LANGUAGE} SHARED_LIBRARY_TMPDIR=. OTHERLIBS="-L${BABEL_LIB} -lsidl ${SL_LINKER_LIBS} ${SYS_LIB}" shared_arch

libclient-c++: libclient-c


libclient-python: 
	python setup.py --include-dirs=${BABEL_INCLUDE} --include-dirs=${BABEL_INCLUDE}/python2.4/babel --library-dirs=${BABEL_LIB}  install   --install-purelib=./ --install-platlib=./ --install-headers=include --install-scripts=scripts --install-data=data

#-------------------------------------------------------------------------------
server-c++:  server/c++/makefile
	cd server/c++; make TLIBNAME=${TLIBNAME} libserver-c++.${SOSUFFIX}

server/c++/makefile: ${SIDLFILES}
	@-${BK} edit server/c++/*_Impl.cc server/c++/*_Impl.hh
	-${BABEL} -R ${CCA_REPO} --suppress-timestamp --server=c++ --output-directory=./server/c++ ${SIDLFILES}
	@-${RM} ${REMOVEFILES}
	echo "include ${PETSC_DIR}/src/tops/makefile.rules" > server/c++/makefile

libserver-c++.${SOSUFFIX}: 
	${CC} -c ${CC_FLAGS} ${COPTFLAGS} ${CFLAGS} ${CCPPFLAGS} -I${PETSC_DIR}/src/tops/server/c++ *.cc
	${C_CC} -c ${C_CC_FLAGS} ${COPTFLAGS} ${CFLAGS} ${CCPPFLAGS} -I${PETSC_DIR}/src/tops/server/c++  *.c
	$(OMAKE)  LIBNAME=${TLIBNAME} SHARED_LIBRARY_TMPDIR=. OTHERLIBS="-L${BABEL_LIB} -lsidl ${SL_LINKER_LIBS} ${SYS_LIB}" shared_arch
#-------------------------------------------------------------------------------

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test



