
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = dspacebdm.c
SOURCEF   =
LIBBASE   = libpetscdm
DIRS      =
LOCDIR    = src/dm/dt/dualspace/impls/bdm/
MANSEC    = DM
SUBMANSEC = DUALSPACE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
