# $Id: makefile,v 1.19 2000/08/17 04:41:40 bsmith Exp bsmith $ 

CFLAGS	        = 
FFLAGS          =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/sles/pc/examples/tutorials/
DOCS            = readme 

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test

