# $Id: makefile,v 1.15 1999/01/31 16:08:33 bsmith Exp balay $ 

ALL: ex1

CFLAGS	        = 
FFLAGS          =
CPPFLAGS        = ${BS_INCLUDE}
FPPFLAGS        =
LOCDIR          = src/sles/pc/examples/tutorials/

TESTEXAMPLES_1  =
TESTEXAMPLES_2  =
TESTEXAMPLES_4  =
BUILDEXAMPLES_1 =
BUILDEXAMPLES_2 =
BUILDEXAMPLES_4 =

EXAMPLESC       =
DOCS            = README 

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base


