
ALL: lib

CFLAGS   =
FFLAGS   =
DIRS     = 
LOCDIR   = src/mat/impls/is/
SOURCEH  = matis.h
SOURCEC  = matis.c 
OBJSC    = matis.o
LIBBASE  = libpetscmat
MANSEC   = Mat

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
