
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mmbdiag.c mpibdiag.c
SOURCEF  =
SOURCEH  = mpibdiag.h
OBJSC    = mmbdiag.o mpibdiag.o
OBJSF    =
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/bdiag/mpi/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
