-include ../../../../../petscdir.mk

SOURCEC  = mpibaij.c mmbaij.c baijov.c mpb_baij.c mpiaijbaij.c
LIBBASE  = libpetscmat
DIRS     = baijmkl
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
