-include ../../../../petscdir.mk

CLEANFILES  = eptorsion1 eptorsion2 minsurf2 rosenbrock1 eptorsion2f rosenbrock1f rosenbrock2 rosenbrock3

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

rosenbrock4.o: rosenbrock4.h

rosenbrock4cu.o: rosenbrock4.h
