-include ../../../../petscdir.mk

LOCDIR		 = src/tao/unconstrained/tutorials/
MANSEC		 = Tao
DOCS		 =
DIRS		 =
CLEANFILES       = eptorsion1 eptorsion2 minsurf2 rosenbrock1 eptorsion2f rosenbrock1f rosenbrock2 rosenbrock3

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
