-include ../../../../petscdir.mk
CFLAGS		 =
FFLAGS		 =
CPPFLAGS         =
FPPFLAGS         =
EXAMPLESC        = eptorsion1.c eptorsion2.c minsurf2.c rosenbrock1.c rosenbrock2.c rosenbrock3.c spectraladjointassimilation.c
EXAMPLESF        = eptorsion2f.F rosenbrock1f.F90
EXAMPLESCH       =
EXAMPLESFH       = eptorsion2f.h rosenbrock1f.h
LOCDIR		 = src/tao/unconstrained/tutorials/
MANSEC		 =
DOCS		 =
DIRS		 =
CLEANFILES       = eptorsion1 eptorsion2 minsurf2 rosenbrock1 eptorsion2f rosenbrock1f rosenbrock2 rosenbrock3

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
