
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = shellpc.c 
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscksp
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/shell/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
