
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/vec/is/ao/tests/
DIRS            = ex3d
EXAMPLESC       = ex1.c ex2.c ex4.c ex5.c ex7.c
EXAMPLESF       = ex4f.F
MANSEC          = Vec
SUBMANSEC       = AO

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
