# $Id: makefile,v 1.10 2001/08/22 18:01:30 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pcsles.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pcsles.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/sles/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
