
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = tr.c
SOURCEF  =
SOURCEH  = trimpl.h
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/tr/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

