-include ../../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_SYCL'

MANSEC	  = Sys
LIBBASE	  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

