#requiresdefine 'PETSC_HAVE_CUSP_SMOOTHED_AGGREGATION'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCECU  = bicgstabcusp.cu
SOURCEF  =
SOURCEH  = 
OBJSCU   = bicgstabcusp.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/bicgstabcusp/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
