
CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = petsc.h petscsys.h private/petscimpl.h petscbag.h petscmath.h petscbt.h \
 petscblaslapack.h petscf90.h petscversion.h zpetsc.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = finclude f90impl
LOCDIR   = include/
MANSEC   = Sys

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
