# $Id: makefile,v 1.38 1998/04/23 23:23:17 balay Exp balay $ 

SOURCEC  =
SOURCEF  =
SOURCEH  = draw.h is.h ksp.h mat.h options.h pc.h petsc.h sys.h \
           vec.h sles.h mg.h viewer.h snes.h dfvec.h  ec.h ao.h\
           da.h petsclog.h petschead.h petscerror.h ts.h gvec.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = pinclude finclude
LOCDIR   = include/
MANSEC   = p

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

runexamples:



