# $Id: makefile,v 1.47 2000/05/08 15:09:50 balay Exp bsmith $ 

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = petscdraw.h petscis.h petscksp.h petscmat.h petscoptions.h petscpc.h petsc.h petscsys.h \
           petscvec.h petscsles.h petscmg.h petscviewer.h petscsnes.h  ec.h petscao.h\
           petscda.h petsclog.h petschead.h petscerror.h petscts.h \
	   petscmath.h petscbt.h petscpf.h petscengine.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = pinclude finclude
LOCDIR   = include/
MANSEC   = Profiling

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

runexamples:



