-include ../../../../petsckdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zptimef.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/time/ftn-custom/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
