
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zptimef.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/time/ftn-custom/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
