
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pipecr.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/cr/pipecr/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
