-include ../../../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zbinvf90.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/classes/viewer/impls/binary/f90-custom/


include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


