#requiresdefine   'PETSC_HAVE_FORTRAN'
#requiresdefine   'PETSC_USING_F90'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zbinvf90.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/classes/viewer/impls/binary/f90-custom/


include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


