-include ../../../../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pack.c packm.c
SOURCEF  =
SOURCEH  = packimpl.h
LIBBASE  = libpetscdm
MANSEC   = DM
DIRS     = tests
LOCDIR   = src/dm/impls/composite/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
