-include ../../../../petscdir.mk

SOURCEC  = pack.c packm.c
SOURCEH  = packimpl.h
LIBBASE  = libpetscdm
MANSEC   = DM
DIRS     = tests

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
