# $Id: makefile,v 1.9 2000/05/04 19:02:40 balay Exp bsmith $ 

ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = cputime.c fdate.c nt_time.c rs6000_time.c
SOURCEF	  =
SOURCEH	  = 
OBJSC	  = cputime.o fdate.o nt_time.o rs6000_time.o
OBJSF	  =
MANSEC	  = Sys
LIBBASE	  = libpetsc
DIRS	  = 
LOCDIR	  = src/sys/src/time/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
