#requirespackage  'PETSC_USE_MATFWK'
#requireslanguage CXXONLY

ALL: lib

CPPFLAGS = 
CFLAGS   = 
FFLAGS   =
SOURCEC  = matfwk.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = matfwk.o
OBJSF    =
DIRS     = 
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/framework/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
