ALL: lib

CPPFLAGS = 
CFLAGS   = 
FFLAGS   =
SOURCEC  = matfwk.c
SOURCEF  = 
SOURCEH  = matfwk.h
OBJSC    = matfwk.o
OBJSF    =
DIRS     = 
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/fwk/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
