
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = drawimpl.h ../../../include/petscdraw.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetsc
DIRS     = interface impls examples utils
LOCDIR   = src/sys/draw/
MANSEC   = Draw

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
