
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = submat.c
SOURCEF  =
SOURCEH  = 
OBJSC    = submat.o
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = 
LOCDIR   = src/mat/impls/submat/
MANSEC   = Mat

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test

