-include ../../../../petscdir.mk

SOURCEC  = submat.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
DIRS     =
LOCDIR   = src/mat/impls/submat/
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

