ALL: lib

CFLAGS   = ${BLOPEX_INCLUDE} 
FFLAGS   =
SOURCEC  = petsc-interface.c
SOURCEF  =
SOURCEH  = petsc-interface.h
OBJSC    = petsc-interface.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = 
LOCDIR   = src/contrib/blopex/petsc-interface/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
