
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gcr.c
SOURCEH  = 
SOURCEF  = 
OBJSC    = gcr.o
OBJSF    = 
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/gcr/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
