-include ../../../../../petscdir.mk
#requiresdefine   'PETSC_USE_FORTRAN_BINDINGS'
#requiresdefine   'PETSC_USING_F2003'

LIBBASE  = libpetscsys
MANSEC   = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
