# $Id: makefile,v 1.22 1999/01/27 19:46:04 bsmith Exp bsmith $

ALL: lib

LIBBASE  = libpetscsles
DIRS     = cr bcgs cg cgs gmres cheby rich lsqr preonly tcqmr tfqmr qcg bicg
LOCDIR   = src/sles/ksp/impls/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
