# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lmvm.c
SOURCEF  = 
SOURCEH  = lmvm.h
OBJSC    = lmvm.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/unconstrained/impls/lmvm/

include ${TAO_DIR}/conf/tao_base

