
ALL: lib

SOURCEC   = sfutils.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscvec
LOCDIR	  = src/vec/is/sf/utils/
MANSEC	  = Vec
SUBMANSEC = PetscSF

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
