-include ../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'
#

LIBBASE	   = libpetscksp
MANSEC	   = KSP
CLEANFILES = *.mod

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
