-include ../../../petscdir.mk

DIRS      = ephemeral
LOCDIR    = src/dm/label/impls/
MANSEC    = DM
SUBMANSEC = DMLabel

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
