-include ../../../../../petscdir.mk

SOURCEC  = schurm.c
SOURCEF  =
SOURCEH  = schurm.h
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
