
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = schurm.c
SOURCEF  =
SOURCEH  = schurm.h
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/utils/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
