-include ../../../../../petscdir.mk

SOURCEC  = gpcg.c
SOURCEF  =
SOURCEH  = gpcg.h
LIBBASE  = libpetsctao
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

