-include ../../../../petscdir.mk

SOURCEH  = dvecimpl.h
LIBBASE  = libpetscvec
DIRS     = seq mpi shared hypre nest

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

