
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = dvecimpl.h
LIBBASE  = libpetscvec
DIRS     = seq mpi shared hypre nest
LOCDIR   = src/vec/vec/impls/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

