# $Id: makefile,v 1.5 1998/04/23 23:49:57 balay Exp balay $ 

ALL: lib

SOURCEC  = 
SOURCEF  = fmaxpy.F fmdot.F fnorm.F fmult.F fmultadd.F fsolve.F
SOURCEH  = 
OBJSC    = 
OBJSF    = fmaxpy.o fmdot.o fnorm.o fmult.o fmultadd.o fsolve.o
LIBBASE  = libpetsckernels
MANSEC   = 7
LOCDIR   = src/fortran/kernels/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base


