# $Id: makefile,v 1.11 1999/01/31 16:12:16 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  = fmaxpy.F fmdot.F fnorm.F fmult.F fmultadd.F fsolve.F fsolvebaij.F \
           sgemv.F
SOURCEH  = 
OBJSC    = 
OBJSF    = fmaxpy.o fmdot.o fnorm.o fmult.o fmultadd.o fsolve.o fsolvebaij.o \
           sgemv.o
DOCS     = README
LIBBASE  = libpetsc
MANSEC   = 7
LOCDIR   = src/fortran/kernels/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base


