ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = tron.c
SOURCEF  = 
SOURCEH  = tron.h
OBJSC    = tron.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = taosolver
LOCDIR   = src/bound/impls/tron/

include ${TAO_DIR}/conf/tao_base

