PETSC_DIR = ../

CFLAGS   = $(OPT) -I$(PETSC_DIR)/include -I.. -I$(PETSC_DIR) $(CONF) $(PCONF)
SOURCEC  =
SOURCEF  =
SOURCEH  = tex/manual.tex www/www.html tex/part1.tex tex/part2.tex tex/intro.tex \
           tex/abstract.tex tex/acknowl.tex tex/manual_tex.tex
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
LINCLUDE = $(SOURCEH)
DIRS     = 

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/$(PETSC_ARCH)

runexamples:


