# $Id: makefile,v 1.53 2000/02/01 18:37:11 bsmith Exp bsmith $ 

DIRS     = inline sys vec mat sles snes ts dm contrib benchmarks pf fortran 
LOCDIR   = src/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
