ITOOLSDIR = ../

CFLAGS   = $(OPT) -I$(ITOOLSDIR)/include -I.. -I$(ITOOLSDIR) $(CONF)
SOURCEC  =
SOURCEF  =
WSOURCEC = 
SOURCEH  = 
OBJSC    =
WOBJS    = 
OBJSF    =
LIBBASE  = libpetscvec
LINCLUDE = $(SOURCEH)
DIRS     = inline is vec ksp sys pc mat sles options draw 

include $(ITOOLSDIR)/bmake/$(PARCH)/$(PARCH)

runexamples:

