# $Id: makefile,v 1.41 1998/03/19 02:04:38 balay Exp bsmith $ 

CFLAGS   = 
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = inline is vec ksp sys pc mat sles draw ts dfvec \
           viewer snes da contrib benchmarks ao gvec
LOCDIR   = src/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

