

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gasm.c
SOURCEF  =
SOURCEH  = 
OBJSC    = gasm.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
SUBMANSEC= PCGASM
LOCDIR   = src/ksp/pc/impls/gasm/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
