
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = nash.c
SOURCEF  =
SOURCEH  = nashimpl.h
OBJSC    = nash.o
OBJSF    =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/cg/nash/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
