-include ../../../../../../petscdir.mk

SOURCEC  = nash.c
SOURCEF  =
SOURCEH  = nashimpl.h
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/cg/nash/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
