# $Id: makefile,v 1.2 2001/08/22 18:01:45 balay Exp $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = symmlq.c
SOURCEF  =
OBJSC    = symmlq.o
OBJSF    =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/symmlq/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
