-include ../petscdir.mk
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = symmlq.c
SOURCEF  =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/symmlq/
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
