
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = symmlq.c
SOURCEF  =
OBJSC    = symmlq.o
OBJSF    =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/symmlq/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
