# $Id: makefile,v 1.5 1998/06/12 21:43:25 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pcsles.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pcsles.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = 4
LOCDIR   = src/pc/impls/sles/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
