# $Id: makefile,v 1.2 1998/01/06 20:10:01 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   = ${CPPFLAGS} ${CONF} -D__SDIR__='"${LOCDIR}"'
SOURCEC  = pcsles.c
SOURCEF  =
SOURCEH  = 
OBJSC    = pcsles.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = 4
LOCDIR   = src/pc/impls/sles/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
