-include ../../../../petscdir.mk

SOURCEC  =
SOURCEF90= f90_fwrap.F90
SOURCEH  =
DIRS     =
LIBBASE  = libpetscsys
MANSEC   = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
