# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pounders.c
SOURCEF  = dgqt.f
SOURCEH  = pounders.h taolapack.h
OBJSC    = pounders.o dgqt.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = solver
LOCDIR   = src/leastsquares/impls/pounders/

include ${TAO_DIR}/conf/tao_base

