# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pounders.c gqt.c
SOURCEF  = 
SOURCEH  = pounders.h 
OBJSC    = pounders.o gqt.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = taosolver
LOCDIR   = src/leastsquares/impls/pounders/

include ${TAO_DIR}/conf/tao_base

