#! /bin/csh 
#
# This Utility converts the static ".a" library files to dynamic ".so" files
# invoked as make_dso_IRIX $(LIBRARY_PATH)
#
echo  making dynamic libraries in $argv[1]
cd $argv[1]
foreach LIBNAME (mpiuni petsccontrib petscdraw petscksp petscmat \
  petscsles petscsnes petscsys petscts petscvec petscfortran)
  if ( -e lib$LIBNAME.a) then 
    ld -elf -shared -rdata_shared -all lib$LIBNAME.a -o lib$LIBNAME.so
  endif
end

