# $Id: base.g,v 1.17 1998/01/28 20:59:10 bsmith Exp balay $ 

CC         = ${C_CC}
FC         = ${C_FC}
CLINKER    = ${C_CLINKER}  ${COPTFLAGS}
FLINKER    = ${C_FLINKER}  ${FOPTFLAGS}
SYS_LIB    = ${C_SYS_LIB}

PETSCFLAGS = ${G_PETSCFLAGS}
COPTFLAGS  = ${G_COPTFLAGS}
FOPTFLAGS  = ${G_FOPTFLAGS}

