##
#requirespackage  'PETSC_HAVE_CGNS'

ALL: lib

CFLAGS    = ${CGNS_INCLUDE}
MANSEC    = Sys
SUBMANSEC = Viewer

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
