# $Id: makefile,v 1.23 1997/08/22 15:15:29 bsmith Exp $ 

ALL: lib

CFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = mpi
LOCDIR   = src/mat/impls/rowbs/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base
