# $Id: makefile,v 1.12 1998/03/19 02:07:30 balay Exp balay $ 

ALL: lib

SOURCEC  =
SOURCEF  =
SOURCEH  = 
OBJSC    =
OBJSF    =
LIBBASE  = libpetscmat
DIRS     = mpi
LOCDIR   = src/mat/impls/rowbs/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
