
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = posindep.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/impls/pseudo/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

