# $Id: makefile,v 1.28 1998/06/15 16:08:41 balay Exp bsmith $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = filev.c
SOURCEF  =
SOURCEH  =
OBJSC    = filev.o
OBJSF    =
MANSEC   = v
LIBBASE  = libpetscsys
DIRS     = 
LOCDIR   = src/viewer/impls/ascii/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
