# $Id: makefile,v 1.29 1998/12/03 04:04:57 bsmith Exp bsmith $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = filev.c
SOURCEF  =
SOURCEH  =
OBJSC    = filev.o
OBJSF    =
MANSEC   = v
LIBBASE  = libpetsc
DIRS     = 
LOCDIR   = src/viewer/impls/ascii/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
