# $Id: makefile,v 1.22 1999/02/03 04:29:46 bsmith Exp bsmith $ 

ALL: lib

DIRS     = seq mpi
LOCDIR   = src/mat/impls/dense/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
