#PETSC_DIR = ../..

ALL: lib

CFLAGS   = 
SOURCEC  =
SOURCEF  =
SOURCEH  = tsimpl.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscts
DIRS     = interface impls  examples
LOCDIR   = src/ts/

include $(PETSC_DIR)/bmake/$(PETSC_ARCH)/base

