# $Id: makefile,v 1.29 1998/06/15 15:59:29 balay Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = jacobi.c
SOURCEF  =
SOURCEH  = 
OBJSC    = jacobi.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = 4
LOCDIR   = src/pc/impls/jacobi/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
