# $Id: makefile,v 1.5 2000/08/17 04:52:15 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = milu.c
SOURCEF  =
SOURCEH  = 
OBJSC    = milu.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/sles/pc/impls/milu/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
