# $Id: makefile,v 1.2 1998/09/25 03:16:23 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = milu.c
SOURCEF  =
SOURCEH  = 
OBJSC    = milu.o
OBJSF    =
LIBBASE  = libpetscsles
DIRS     = 
MANSEC   = PC
LOCDIR   = src/contrib/pc/milu

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
