-include ../../../petscdir.mk
#requiresdefine   'PETSC_USE_FORTRAN_BINDINGS'

LIBBASE	   = libpetscsnes
MANSEC	   = SNES
CLEANFILES = *.mod

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
