
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vector.c veccreate.c vecreg.c vecregall.c dlregisvec.c rvector.c
SOURCEF  =
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
DIRS     =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/interface/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
