ALL: lib

CPPFLAGS = 
CFLAGS   = 
FFLAGS   =
SOURCEC  = matim.c
SOURCEF  = 
SOURCEH  = matim.h
OBJSC    = matim.o
OBJSF    =
DIRS     = 
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/im/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
