ITOOLSDIR = ../../

ALL: lib

CFLAGS   = $(OPT) -I.. -I$(ITOOLSDIR) -I$(ITOOLSDIR)/include
SOURCEC  = itcl.c itfunc.c iguess.c itcreate.c iterativ.c itres.c itregis.c 
WSOURCEC = 
SOURCEF  =
SOURCEH  = 
OBJSC    = itcl.o itfunc.o iguess.o itcreate.o iterativ.o itres.o itregis.o 
WOBJS    =
LIBBASE  = libpetscksp
LOCAL_INCLUDE = 
DIRS =

