# $Id: makefile,v 1.34 1998/04/23 23:29:29 balay Exp balay $ 

ALL: lib

CFLAGS   = 
SOURCEC  = itcl.c itfunc.c iguess.c itcreate.c iterativ.c itres.c itregis.c \
           xmon.c eige.c dlregis.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = itcl.o itfunc.o iguess.o itcreate.o iterativ.o itres.o itregis.o \
           xmon.o eige.o dlregis.o
LIBBASE  = libpetscsles
DIRS     =
MANSEC   = 5
LOCDIR   = src/ksp/interface/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
