-include ../../../../../petscdir.mk

SOURCEC   = owarmijo.c
SOURCEH   = owarmijo.h
LIBBASE   = libpetsctao
MANSEC    = Tao
SUBMANSEC = TaoLineSearch

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

