
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = owarmijo.c
SOURCEF  = 
SOURCEH  = owarmijo.h
LIBBASE  = libpetsctao
MANSEC   = 
LOCDIR   = src/tao/linesearch/impls/owarmijo/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

