-include ../petscdir.mk
ALL: lib

DIRS     = seq mpi
LOCDIR   = src/mat/impls/sell/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
