-include ../../../../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = zbvec2f.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscvec
LOCDIR   = src/vec/vec/impls/seq/ftn-custom/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
