-include ../../../../../../petscdir.mk

SOURCEC  = rander48.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
DIRS     =
MANSEC	 = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
