ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bqpip.c
SOURCEF  = 
SOURCEH  = bqpip.h
OBJSC    = bqpip.o
OBJSF    = 
LIBBASE  = libtaosolver
MANSEC   = taosolver
LOCDIR   = src/bound/impls/bqpip/

include ${TAO_DIR}/conf/tao_base

