-include ../../../../../../petsckdir.mk

SOURCEC   = drawimage.c
SOURCEF   =
SOURCEH   = drawimage.h
MANSEC    = Sys
SUBMANSEC = Draw
LIBBASE   = libpetscsys
DIRS      =
LOCDIR    = src/sys/classes/draw/impls/image/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
