
#requireslanguage  CPP
#requiresscalar    real 
#requiresprecision double
#requirespackage   'PETSC_HAVE_CXX_NAMESPACE'

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = esles.c
OBJSC    = esles.o
SOURCEH  = ../../../include/esi/petsc/solveriterative.h
LIBBASE  = libpetscksp
MANSEC   = 
LOCDIR   = src/ksp/esi/


include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


