-include ../../../../petscdir.mk

SOURCEH  =
DIRS     = pounders brgn

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

