
ALL: lib

CFLAGS   = 
FFLAGS   = 
SOURCEC  = run-map.c run-alloc.c
SOURCEF  =
SOURCEH  = ../../../../include/adic/run-map.h ../../../../include/adic/run-alloc.h
LIBBASE  = libpetscsys
DIRS     = 
LOCDIR   = src/sys/adic/adic/
MANSEC   = Sys

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

