ALL: lib

DIRS     = blmvm tron bncg bnk

LOCDIR   = src/tao/bound/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

