-include ../../../../petscdir.mk

DIRS     = blmvm tron bncg bnk bqnk bqnls
LOCDIR   = src/tao/bound/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

