-include ../../../../../petscdir.mk

SOURCEC  = owlqn.c
SOURCEF  =
SOURCEH  = owlqn.h
LIBBASE  = libpetsctao
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

