ITOOLSDIR = ../../../../

ALL: lib

CFLAGS   = $(OPT) $(INCLUDEDIRS) -I../.. -I$(ITOOLSDIR)/pinclude\
           $(CONF)
SOURCEC  = direct.c
SOURCEF  =
WSOURCEC = 
SOURCEH  = 
OBJSC    = direct.o
WOBJS    = 
OBJSF    =
LIBBASE  = libpetscpc
LINCLUDE = $(SOURCEH)
DIRS     = 
MANSEC   = 4

include $(ITOOLSDIR)/bmake/$(PARCH)/$(PARCH)
