#requirespackage 'PETSC_HAVE_KOKKOS_KERNELS'
-include ../../../../../petscdir.mk

SOURCEC      =
SOURCEF      =
SOURCEKOKKOS = dagetov.kokkos.cxx
SOURCEH      =
LIBBASE      = libpetscdm
MANSEC       = DM
SUBMANSEC    = DMDA
DIRS         =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
