-include ../../../../petscdir.mk

SOURCEC   = tssen.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscts
MANSEC    = TS
SUBMANSEC = Sensitivity

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
