-include ../../../../petsckdir.mk

SOURCEH	  = ../../../../include/petsc/private/sectionimpl.h ../../../../include/petscsection.h ../../../../include/petscsectiontypes.h
SOURCEC   =
LIBBASE	  = libpetscvec
DIRS	    = interface
LOCDIR    = src/vec/is/section/
MANSEC    = Vec
SUBMANSEC = PetscSection

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
