ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  = bagenum.F
SOURCEH  =
DIRS     =
LIBBASE  = libpetscsys
MANSEC   = Sys
LOCDIR   = src/sys/classes/bag/f2003-src/fsrc/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
