ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = projection.c  isutil.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = projection.o  isutil.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/bound/utils/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

