
SOURCEC  = isutil.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/bound/utils/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

