
SOURCEH   =
DIRS      = viewer draw matlabengine random bag
LOCDIR    = src/sys/classes/
MANSEC    = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
