#requiresdefine 'PETSC_HAVE_CXX'
ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCECXX = demangle.cxx
SOURCEF	  =
SOURCEH	  =
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS      =
LOCDIR	  = src/sys/dll/cxx

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
