-include ../../../../petscdir.mk
#requiresdefine 'PETSC_HAVE_CXX'

SOURCECXX = demangle.cxx
SOURCEF	  =
SOURCEH	  =
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS      =
LOCDIR	  = src/sys/dll/cxx

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
