-include ../../../../petscdir.mk
#requiresdefine 'PETSC_HAVE_CXX'

SOURCECXX = demangle.cxx
MANSEC	  = Sys
LIBBASE	  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
