-include ../../../petscdir.mk
#requiresdefine   'PETSC_USE_FORTRAN_BINDINGS'

DIRS     = fsrc
LIBBASE  = libpetscsys
MANSEC   = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
