#requirespackage 'PETSC_USE_F90_SRC_IMPL'

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  = f90_cwrap.c
SOURCEH  =
OBJSC    =
OBJSF	 = f90_cwrap.o
DIRS     = fsrc
LIBBASE  = libpetsc
MANSEC   = Sys
LOCDIR   = src/sys/f90-src/

include ${PETSC_DIR}/conf/base
include ${PETSC_DIR}/conf/test
