-include ../../../petscdir.mk
#requiresdefine   'PETSC_HAVE_FORTRAN'

SOURCEC  = f90_cwrap.c
SOURCEF  =
SOURCEH  =
DIRS     = fsrc
LIBBASE  = libpetscsys
MANSEC   = Sys
LOCDIR   = src/sys/f90-src/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
