
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = zgeneralf.c
OBJSC    = zgeneralf.o
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscvec
LOCDIR   = src/vec/is/impls/general/ftn-custom/
include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
