-include ../../../../../petscdir.mk
#requirespackage   'PETSC_HAVE_SUNDIALS2'

LIBBASE  = libpetscts
MANSEC   = TS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

