
ALL: lib

#requirespackage   'PETSC_HAVE_SUNDIALS2'

CFLAGS   =
FFLAGS   =
CPPFLAGS =
SOURCEC  = sundials.c
SOURCEF  =
SOURCEH  = sundials.h
LIBBASE  = libpetscts
MANSEC   = TS
LOCDIR   = src/ts/impls/implicit/sundials/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

