# $Id: makefile,v 1.2 2000/08/01 20:57:14 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = damg.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = damg.o 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = SLES
LOCDIR   = src/sles/utils/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
include ${PETSC_DIR}/bmake/common_test
