# $Id: makefile,v 1.3 2000/08/17 04:52:38 bsmith Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = damg.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = damg.o 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = SLES
LOCDIR   = src/sles/utils/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test
