# $Id: makefile,v 1.1 2000/07/11 19:23:37 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = damg.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = damg.o 
OBJSF    =
LIBBASE  = libpetscsles
MANSEC   = SLES
LOCDIR   = src/sles/utils/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
