#define SNESNRICHARDSON  "nrichardson"
#define SNESVIRS         "virs"
#define SNESVISS         "viss"
#define SNESQN           "qn"
#define SNESSHELL        "shell"
#define SNESNCG          "ncg"
#define SNESFAS          "fas"
