-include ../../../petscdir.mk

SOURCEC	  = verboseinfo.c
MANSEC	  = Sys
SUBMANSEC = Profiling
LIBBASE	  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
