-include ../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_SAWS'

SOURCEC  = kspsaws.c
LIBBASE  = libpetscksp
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
