-include ../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_SAWS'

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = kspsaws.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscksp
DIRS     =
LOCDIR   = src/ksp/ksp/interface/saws/
MANSEC   = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
