
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = zdraw.c zoptions.c zplog.c zstart.c zstartf.c zsys.c zviewer.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = zdraw.o zoptions.o zplog.o zstart.o zstartf.o zsys.o zviewer.o
OBJSF    = 
LIBBASE  = libpetsc
MANSEC   = Sys
LOCDIR   = src/sys/custom/

include ${PETSC_DIR}/bmake/common/base
include ${PETSC_DIR}/bmake/common/test


