# $Id: makefile,v 1.28 1998/06/12 21:07:11 balay Exp balay $ 

ALL: lib 

SOURCEC  = lsqr.c
SOURCEF  =
OBJSC    = lsqr.o
OBJSF    =
LIBBASE  = libpetscsles
LOCDIR   = src/ksp/impls/lsqr/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
