-include ../../../../petscdir.mk

SOURCEH	  = ../../../../include/petsc/private/isimpl.h ../../../../include/petscis.h ../../../../include/petscistypes.h
LIBBASE	  = libpetscvec
DIRS	  = interface impls  tests tutorials utils
LOCDIR    = src/vec/is/is/
MANSEC    = Vec
SUBMANSEC = IS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

