
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = reduced.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscts
MANSEC   = TS
DIRS     = 
LOCDIR   = src/ts/impls/semiexplicit/reduced

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


