-include ../../../../../../petscdir.mk

SOURCEC  = basfactor.c spbas.c
SOURCEF  =
SOURCEH  = spbas.h spbas_cholesky.h
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat
LOCDIR   = src/mat/impls/aij/seq/bas/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
