
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = gltr.c
SOURCEF  =
SOURCEH  = gltrimpl.h
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/cg/gltr/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
