# $Id: makefile,v 1.2 2000/02/02 21:21:18 bsmith Exp bsmith $ 

ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = const.c
SOURCEF  =
SOURCEH  = 
OBJSC    = const.o
OBJSF    =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/pf/impls/constant/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base

