-include ../../../../../petscdir.mk

CFLAGS   = ${MATLAB_INCLUDE}
LIBBASE  = libpetscvec
MANSEC   = Vec

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
