-include ../../../../../../../petscdir.mk

LIBBASE       = libpetscvec
MANSEC        = Vec
SUBMANSEC     = PetscSF
DIRS          = cuda hip

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc


