-include ../../../petscdir.mk

SOURCEC  = dmts.c dmlocalts.c dmdats.c dmplexts.c tsconvest.c dmnetworkts.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscts
MANSEC   = TS
DIRS     = dmplexlandau
EDIRS    =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
