
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = dmts.c dmdats.c
SOURCEF  =
SOURCEH  = 
OBJSC    = $(SOURCEC:.c=.o)
OBJSF    =
LIBBASE  = libpetscsnes
MANSEC   = SNES
DIRS     = 
EDIRS    = 
LOCDIR   = src/snes/utils/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

