
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dspacesimple.c
SOURCEF  =
LIBBASE  = libpetscdm
DIRS     = 
LOCDIR   = src/dm/dt/dualspace/impls/simple/
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
