#ifdef PETSC_RCS_HEADER
"$Id: petscconf.h,v 1.10 2000/11/02 22:27:54 bsmith Exp $"
"Defines the configuration for this machine"
#endif

#if !defined(INCLUDED_PETSCCONF_H)
#define INCLUDED_PETSCCONF_H

#define PARCH_ascired
#define PETSC_ARCH_NAME "ascired"
#define PETSC_HAVE_SYS_WAIT_H
#define PETSC_HAVE_VPRINTF
#define STDC_HEADERS
#define PETSC_HAVE_FORTRAN_UNDERSCORE
#define PETSC_HAVE_DRAND48
#define PETSC_HAVE_GETCWD
#define PETSC_HAVE_GETHOSTNAME
#define PETSC_HAVE_GETWD
#define PETSC_HAVE_MEMMOVE
#define PETSC_HAVE_SIGACTION
#define PETSC_HAVE_SIGNAL
#define PETSC_HAVE_STRSTR
#define PETSC_HAVE_UNAME
#define PETSC_HAVE_FCNTL_H
#define PETSC_HAVE_LIMITS_H
#define PETSC_HAVE_MALLOC_H
#define PETSC_HAVE_PWD_H
#define PETSC_HAVE_SEARCH_H
#define PETSC_HAVE_STDLIB_H
#define PETSC_HAVE_STRING_H
#define PETSC_HAVE_STRINGS_H
#define PETSC_HAVE_STROPTS_H
#define PETSC_HAVE_SYS_TIME_H
#define PETSC_HAVE_UNISTD_H
#define PETSC_HAVE_SWAPPED_BYTES
#define PETSC_HAVE_SYS_RESOURCE_H

#define BITS_PER_BYTE 8

#define PETSC_HAVE_SLOW_NRM2
#define PETSC_USE_DCLOCK

#define PETSC_NEED_SETSOCKETOPT_PROTO
#define PETSC_NEED_CONNECT_PROTO
#define PETSC_NEED_SOCKET_PROTO

#define PETSC_HAVE_STAT_NO_CONST
#define PETSC_USE_KBYTES_FOR_SIZE

#define PETSC_CANNOT_START_DEBUGGER
#define PETSC_MISSING_GETPWUID

#define PETSC_MISSING_SOCKETS

#endif
