#ifdef PETSC_RCS_HEADER
"$Id: petscconf.h,v 1.10 2000/11/02 22:27:54 bsmith Exp $"
"Defines the configuration for this machine"
#endif

#if !defined(INCLUDED_PETSCCONF_H)
#define INCLUDED_PETSCCONF_H

#define PARCH_ascired
#define PETSC_ARCH_NAME "ascired"
#define HAVE_SYS_WAIT_H
#define HAVE_VPRINTF
#define STDC_HEADERS
#define PETSC_HAVE_FORTRAN_UNDERSCORE
#define HAVE_DRAND48
#define HAVE_GETCWD
#define HAVE_GETHOSTNAME
#define HAVE_GETWD
#define HAVE_MEMMOVE
#define HAVE_SIGACTION
#define HAVE_SIGNAL
#define HAVE_STRSTR
#define HAVE_UNAME
#define HAVE_FCNTL_H
#define HAVE_LIMITS_H
#define HAVE_MALLOC_H
#define HAVE_PWD_H
#define HAVE_SEARCH_H
#define HAVE_STDLIB_H
#define HAVE_STRING_H
#define HAVE_STRINGS_H
#define HAVE_STROPTS_H
#define HAVE_SYS_TIME_H
#define HAVE_UNISTD_H
#define HAVE_SWAPPED_BYTES
#define HAVE_SYS_RESOURCE_H
#define HAVE_SLEEP
#define HAVE_SYS_PARAM_H
#define HAVE_SYS_STAT_H

#define BITS_PER_BYTE 8

#define HAVE_SLOW_NRM2
#define PETSC_USE_DCLOCK

#define PETSC_NEED_SETSOCKETOPT_PROTO
#define PETSC_NEED_CONNECT_PROTO
#define PETSC_NEED_SOCKET_PROTO

#define PETSC_HAVE_STAT_NO_CONST
#define PETSC_USE_KBYTES_FOR_SIZE

#define PETSC_CANNOT_START_DEBUGGER
#define MISSING_GETPWUID

#define MISSING_SOCKETS

#endif
