-include ../../../../../petscdir.mk

LOCDIR          = src/ts/utils/dmplexlandau/tutorials/
EXAMPLESC       = ex1.c ex2.c
EXAMPLESF       = ex1f90.F90
MANSEC          = TS
SUBMANSECi      = LANDAU

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
