-include ../../../../petsckdir.mk

LOCDIR          = src/vec/is/tests/
DIRS            =
MANSEC          = Vec
SUBMANSEC       = IS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
