
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/vec/is/tests/
DIRS            =
EXAMPLESC       = ex1.c ex2.c
EXAMPLESF       =
MANSEC          = Vec
SUBMANSEC       = IS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
