
LOCDIR          = src/vec/is/tests/
DIRS            =
EXAMPLESC       = ex1.c ex2.c ex3.c ex5.c ex6.c
EXAMPLESF       = ex4f.F90
MANSEC          = Vec
SUBMANSEC       = IS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
