
ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = qcg.c
SOURCEF  =
SOURCEH  = qcgimpl.h 
LIBBASE  = libpetscksp
LINCLUDE = 
LOCDIR   = src/ksp/ksp/impls/qcg/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
