
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pgmres.c
SOURCEH  = pgmresimpl.h
SOURCEF  =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/gmres/pgmres/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test


