-include ../../../../../petscdir.mk

SOURCEC  = lcd.c
SOURCEF  =
SOURCEH  = lcdimpl.h
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/lcd/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
