# $Id: makefile,v 1.22 1999/01/31 16:04:42 bsmith Exp balay $ 

ALL: lib 

CFLAGS   =
FFLAGS   =
SOURCEC  = binv.c
SOURCEF  =
SOURCEH  =
OBJSC    = binv.o
OBJSF    =
MANSEC   = Viewer
LIBBASE  = libpetsc
DIRS     = 
LOCDIR   = src/sys/src/viewer/impls/binary/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
