ALL: lib

SOURCEH	 = 
SOURCEC  = dlregisthreadcomm.c threadcomm.c threadcommregi.c
OBJSC	 = $(SOURCEC:.c=.o)
OBJSF	 =
LIBBASE	 = libpetscsys
DIRS	 = 
LOCDIR   = src/sys/threadcomm/
MANSEC   = PetscThreadComm

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules

