
#if !defined(INCLUDED_PETSCCONF_H)
#define INCLUDED_PETSCCONF_H

#define PETSC_HAVE_F90_H "f90impl/f90_win32.h"
#define PETSC_HAVE_F90_C "src/sys/src/f90/f90_win32.c"

#define W_OK 02
#define S_ISREG(a) (((a)&_S_IFMT) == _S_IFREG)
#define X_OK 01
#define R_OK 04
#define S_ISDIR(a) (((a)&_S_IFMT) == _S_IFDIR)
#define STDC_HEADERS 1
#define PETSC_MISSING_SIGSTOP 1
#define PETSC_MISSING_SIGSYS 1
#define PETSC_REPLACE_DIR_SEPARATOR '/'
#define PETSC_HAVE_CLOSESOCKET 1
#define PETSC_USE_CTABLE 1
#define PETSC_HAVE_NO_GETRUSAGE 1
#define PETSC_MISSING_SIGPIPE 1
#define PETSC_HAVE_GETPROCADDRESS 1
#define PETSC_MISSING_SIGCONT 1
#define PETSC_HAVE_GETCOMPUTERNAME 1
#define PETSC_MISSING_SIGCHLD 1
#define PETSC_MISSING_SIGQUIT 1
#define PETSC_USE_32BIT_INT 1
#define PETSC_HAVE_WINDOWS_H 1
#define PETSC_MISSING_SIGURG 1
#define PETSC_HAVE_LARGE_INTEGER_U 1
#define PETSC_MISSING_SIGHUP 1
#define PETSC_MISSING_SIGTSTP 1
#define PETSC_CANNOT_START_DEBUGGER 1
#define PETSC_MISSING_SIGKILL 1
#define PETSC_MISSING_SIGBUS 1
#define PETSC_MISSING_SIGALRM 1
#define PETSC_USE_NT_TIME 1
#define PETSC_HAVE_GZIP 1
#define PETSC_HAVE_O_BINARY 1
#define PETSC_MISSING_SIGTRAP 1
#define PETSC_DIR_SEPARATOR '\\'
#define PETSC_PATH_SEPARATOR ';'
#define PETSC_HAVE_WSAGETLASTERROR 1
#define PETSC_MISSING_SIGUSR2 1
#define PETSC_MISSING_SIGUSR1 1
#define PETSC_HAVE_GET_USER_NAME 1
#define PETSC_HAVE_WINSOCK2_H 1
#define PETSC_HAVE_LOADLIBRARY 1
#define PETSC_HAVE_SOCKET 1
#define PETSC_STDCALL __stdcall
#define PETSC_HAVE_FORTRAN_MIXED_STR_ARG 1
#define PETSC_HAVE_FORTRAN_CAPS 1
#define PETSC_HAVE_FORTRAN_STDCALL 1
#define PETSC_SIZEOF_MPI_COMM 4
#define PETSC_BITS_PER_BYTE 8
#define PETSC_SIZEOF_MPI_FINT 4
#define PETSC_SIZEOF_VOID_P 4
#define PETSC_RETSIGTYPE void
#define PETSC_SIZEOF_LONG 4
#define PETSC_HAVE_COMPLEX 1
#define PETSC_SIZEOF_DOUBLE 8
#define PETSC_SIZEOF_FLOAT 4
#define PETSC_SIZEOF_INT 4
#define PETSC_SIZEOF_SHORT 2
#define PETSC_HAVE_MALLOC_H 1
#define PETSC_HAVE_TIME_H 1
#define PETSC_HAVE_LIMITS_H 1
#define PETSC_HAVE_STRING_H 1
#define PETSC_HAVE_FCNTL_H 1
#define PETSC_HAVE_DIRECT_H 1
#define PETSC_HAVE_SYS_STAT_H 1
#define PETSC_HAVE_WINDOWSX_H 1
#define PETSC_HAVE_WS2TCPIP_H 1
#define PETSC_HAVE_DOS_H 1
#define PETSC_HAVE_FLOAT_H 1
#define PETSC_HAVE_STDLIB_H 1
#define PETSC_HAVE_SEARCH_H 1
#define PETSC_HAVE_SYS_TYPES_H 1
#define PETSC_HAVE_IO_H 1
#define PETSC_HAVE_ACCESS 1
#define PETSC_HAVE__FULLPATH 1
#define PETSC_HAVE_SIGNAL 1
#define PETSC_HAVE__GETCWD 1
#define PETSC_HAVE_MEMMOVE 1
#define PETSC_HAVE_RAND 1
#define PETSC_HAVE_VPRINTF_CHAR 1
#define PETSC_HAVE_TIME 1
#define PETSC_HAVE_GETCWD 1
#define PETSC_HAVE_LSEEK 1
#define PETSC_HAVE__LSEEK 1
#define PETSC_HAVE_VPRINTF 1
#define PETSC_HAVE__SLEEP 1
#define PETSC_HAVE_STRICMP 1
#define PETSC_HAVE__SNPRINTF 1
#define PETSC_SIGNAL_CAST  
#define PETSC_HAVE__ACCESS 1
#define PETSC_HAVE_CLOCK 1
#define PETSC_ARCH_NAME "win32_ms_hpvm"
#endif
