-include ../../../../../petscdir.mk

SOURCEC  = ssls.c ssils.c ssfls.c
SOURCEH  = ssls.h
LIBBASE  = libpetsctao
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

