
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ssls.c ssils.c ssfls.c
SOURCEF  =
SOURCEH  = ssls.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/complementarity/impls/ssls/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

