-include ../../../../petscdir.mk

LOCDIR		 = src/tao/bound/tutorials/
MANSEC		 =
DOCS		 =
DIRS		 =
CLEANFILES       = plate2 jbearing2 plate2f jbearing2f

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
