ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = neldermead.c
SOURCEF  = 
SOURCEH  = neldermead.h
OBJSC    = neldermead.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = 
LOCDIR   = src/unconstrained/impls/neldermead/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

