-include ../../../../../petscdir.mk

SOURCEC  = neldermead.c
LIBBASE  = libpetsctao
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

