# $Id: makefile,v 1.22 1998/06/12 21:32:49 balay Exp balay $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = slesimpl.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscvec
DIRS     = interface examples
LOCDIR   = src/sles/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
