# $Id: makefile,v 1.24 1999/01/27 19:48:14 bsmith Exp bsmith $ 

ALL: lib

SOURCEH  = slesimpl.h
DIRS     = interface pc ksp examples
LOCDIR   = src/sles/

include ${PETSC_DIR}/bmake/${PETSC_ARCH}/base
